### ISSUE TITLE
Replace observeStore with listener middleware

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10099]
I'd like to replace our `observeStore` function with a "listener middleware" inspired by https://github.com/reduxjs/redux-toolkit/blob/0678c2e195a70c34cd26bddbfd29043bc36d1362/packages/toolkit/src/listenerMiddleware/index.ts#L427

This would allow us to break an import chain between code that uses observeStore and all reducers, which makes tests and chunk splitting more complicated than necessary.

**Comment by ryan-rushton** [comment]
Going to take a look at this. Haven't played around with redux in a while.

**Comment by ryan-rushton** [comment]
Ok so after having a bit of a read and play I just want to make sure we are aligned on what you are actually after.

## Problem

Currently for features to observer changes to the store, they need to import the `observeStore` function which is awkward because it creates a weird dependency graph.

## Solution

We want to create a middleware that lets features register a listener. Here a listener is a pair of two functions
1. A state retrieval function/predicate, which identifies the piece of the store it is interested in
2. A side effect function, which will be called if the retrieved state differs between current and next versions, with the appropriate values of course

This basically allows features to inject a observer into redux without needing to import anything.

### Proposed API

```ts
type StoreObserver<T> = {
  id: string,
  getObserved: (rootState: RootState) => T,
  sideEffect: (current: T, next: T) => void,
}

type ObserveAction = {
  type: 'observe',
  observer: StoreObserver,
}

type UnobserveAction = {
  type: 'unobserve',
  id: string,
}

type ClearObservers = {
  type: 'clearObservers',
}
```

## Questions

1. Some of these observers dispatch redux actions. I don't think this is a concern and we could just dispatch the action without the middleware knowing it is dispatching an action, but figure you would probably know if there was something to consider.
1. One thought is that side effect could return a promise and we chain the listeners in order to ensure a predictable order of operations. Maybe this would be good to do anyway?
1. The redux middleware is significantly more complex because it needs to be generic, the above is the simplest API that I can think would cover the needs of a couple of the observers I looked at. Did I miss anything you can think of.

**Comment by bhollis** [comment]
Thanks, yeah, I'd love some help here. [I started playing with directly using the listenerObserver from redux-toolkit](https://github.com/DestinyItemManager/DIM/tree/listener-middleware), but I did feel that it brought in too much stuff and didn't have exactly the same useful signature as our observeStore did.

Your proposed API looks good!

As for the questions - I think as long as the observer kicks off some async process, it can go back and re-dispatch actions, and I don't think there's any need to set them up to run in any particular order or dependency. Most of these actions are just saving to IndexedDB (which I guess could be its own separate middleware, though the generally available ones are not really my favorite).

**Comment by ryan-rushton** [comment]
Ah yeah, I see the what you were trying there. I think it still has the same pitfall using the `startListener` API that our current `observeStore` has. Namely that if you want to use that you either need to export/import the middleware (same as `observeStore`) or set all listeners up in a central file.

I was eyeballing [this](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/listenerMiddleware/index.ts#L443-L445) part.

```ts
  const middleware: ListenerMiddleware<S, D, ExtraArgument> =
    (api) => (next) => (action) => {
      // ...

      if (addListener.match(action)) {
        return startListening(action.payload)
      }
```

Looking at the [docs](https://redux-toolkit.js.org/api/createListenerMiddleware#addlistener) they have the ability to add listeners both dynamically and statically.

I agree that it seems to bring in too much stuff. I think building it ourselves will only take a few hours and will be much more fit for our purpose. RTK is good in the limited experience I have from a few years ago, but I think it generally requires going all in.
