### ISSUE TITLE
Prevent/recover from accidentally overwriting a loadout

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#10222]
### Proposed change

Replace button "save as new" loadout with a toggle instead

### How does this fit into your workflow?

Too often I meant to duplicate/copy a build (when making a variant), but I end up replacing it instead by accident, with no way to recover....

**Comment by bhollis** [comment]
It's definitely frustrating if that happens, and it sucks that you can't currently recover from it. I don't think the solution is a toggle, and we don't want to add overwrite confirmation since it's such a common workflow. Here are some other thoughts:

1. You could change your workflow to always start out saving as new to make a copy, then editing the copy. That way you won't make a mistake later after you've customized the loadout. 

2. We could allow undoing an overwrite of a loadout, either from a notification or something else. This would pair well with the task to add a Notification Center.

**Comment by Revadike** [comment]
1. I usually do this, but it's quite cumbersome and sometimes I forget
2. Version history could also work, but it'd increase the storage amount

**Comment by nev-r** [comment]
definitely have exact same problem sometimes. and it's a bummer when it happens. a button to [copy loadout and immediately edit the copy] could be cool

**Comment by Revadike** [comment]
yeah something like that

**Comment by bhollis** [comment]
"Copy and Edit" landed earlier this year.

**Comment by Revadike** [comment]
> "Copy and Edit" landed earlier this year.

It's only available on the loadout page (as well as the share button) sadly. Could you make it available in the inventory page as well?
