### ISSUE TITLE
when adding raid mods to the loadout optimizer, sometimes it adds stat mods that do not fit in the armor.

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10229]
Not sure if it's related to this issue, but when adding raid mods to the loadout optimizer, sometimes it adds stat mods that do not fit in the armor.

Example.
![image](https://github.com/DestinyItemManager/DIM/assets/26772074/8d3647bf-def8-4bd6-a448-37fe92c02a0a)

This loadout is supposed to reach 100 resilience when masterworked, but even when masterworked, the resilience mod doesn't fit.

![image](https://github.com/DestinyItemManager/DIM/assets/26772074/b9cbb35c-3bf4-4517-9612-2a6862bbd74f)

_Originally posted by @5c0rp5 in https://github.com/DestinyItemManager/DIM/pull/10017#issuecomment-1902140165_

**Comment by robojumper** [comment]
@5c0rp5 Additional screenshots of the entire Loadout Optimizer page and the whole loadout would be useful - you can also try hovering over the T10 Resilience in Loadout Optimizer to see how it's calculated. Most often these discrepancies happen because of Subclass fragments that give a +10 or -10 to some stat, so the whole context is needed to help with this issue.

**Comment by bhollis** [comment]
@5c0rp5 feel free to reopen if you can share more details.

**Comment by 5c0rp5** [comment]
Sorry, forgot to add the new screenshots. Please see below.

How this happens: 
Select an exotic.
Fill in the raid mods.
Fill in all the other mods you need. 
Increase minimum stat tiers.

Check the top loadouts by clicking on "Compare Loadouts" then "How Mod Placement"

![DIM1](https://github.com/DestinyItemManager/DIM/assets/26772074/cf2aa475-7d47-4ceb-b8a3-4a2fcf11a95f)
![DIM2](https://github.com/DestinyItemManager/DIM/assets/26772074/a725403f-578f-46c1-b3c4-bccb38b0d284)
![DIM3](https://github.com/DestinyItemManager/DIM/assets/26772074/e5d081de-8fe6-4a67-bda1-2cfc4711afb3)

You can also see this issue is happening if a tier stat is available, but clicking on it gives you zero results.
as you can see, my top result has 10 res, and 9 recov when filtered to 8 rec, but when I increase the tiers to 10 and 9, nothing shows.

![image](https://github.com/DestinyItemManager/DIM/assets/26772074/549dd0dc-e66d-4506-95f7-c9d297f1d336)
