### ISSUE TITLE
Farming Mode / Loadouts

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1023]
Equipping a loadout during `farming mode` cancels `farming mode`

**Comment by kyleshay** [comment]
it's been intentionally like that.

https://github.com/DestinyItemManager/DIM/commit/264187a29cc357b93b48d6b9845969425420912d#diff-05c08d226cb720f46488bab9fc25296fL142

we could remove that line, but i think it was added since equipping a loadout and farming mode may fight each other (though it's all part of the queue, so maybe not...) either way you'll end up with things in strange places.
