### ISSUE TITLE
inventory page character headers get smaller, after loading vendor page css

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#10254]
![image](https://github.com/DestinyItemManager/DIM/assets/68782081/867e31ca-f314-4549-937b-7389680826f1)

steps:
- load inventory page fresh with a page refresh
- click over to vendors page
- return to inventory
  - now the emblem headers are smaller

**Comment by bhollis** [comment]
I'm able to reproduce this, but only on Beta (not dev) and only if character columns are set to 4 or 5.

**Comment by bhollis** [comment]
This is caused by Webpack deciding to duplicate CSS across chunks for some reason (it didn't want to make a common chunk I guess?) so when the vendors CSS loads, it redeclares the same `.character` selector from `CharacterButton`, but it now is a later declaration than the `.characterHeader` from `StoreHeading`, and since both have the same specificity, the later declaration wins.
