### ISSUE TITLE
Add Weapon Frame to "Sort By" settings

### ISSUE THREAD

**Issue by danmckinley** [DestinyItemManager/DIM#10304]
### Proposed change

In the settings of DIM, I would like the ability to sort weapons by their instrinsic frame and/or RPM. So grouping all rapid-fire frame fusions would be much easier. This is desireable as the instrinsic frame has a massive impact on how a weapon feels.

### How does this fit into your workflow?

I could group all my handcannons in the kinetic slot by their archetype, aggressive/adaptive/precision frames. Warden's Law would stick out, whereas all my 120 handcannons for PvP would be easier to notice at a glance

**Comment by bhollis** [comment]
Thanks for the suggestion. This request has actually come up frequently on our Discord, and the response we've given is that it doesn't make for a good inventory sort parameter because there's nothing on the item tile to distinguish between one frame and the next. Thus it doesn't fit the purpose of the inventory screen, which is to help you quickly find the items you're looking for. 

If you want this to help with comparing items, it is already available in the Compare and Organizer screens, and of course frame type is also available as a search.

**Comment by danmckinley** [comment]
Respectfully, I don't find that a good reason for this useful change to be discarded entirely. 
Doesn't the "nothing on the item tile to distinguish between one frame and the next" condition apply to soem of the other sort-by filters? Specifically class restriction? How often does class restriction factor into weapons, for example - around 10~ weapons are restricted by class, so it doesn't make that much sense to have that as a sort option. On the other hand, intrinsict frame / RPM is something that applies to literally every single weapon in the game and would only allow users more granular control over their weapons.
Please reconsider :)
