### ISSUE TITLE
[FEATURE] Built-in wish list editor

### ISSUE THREAD

**Issue by tekkeon** [DestinyItemManager/DIM#10311]
### Proposed change

Wish lists right now require a lot of manual effort for users to create with built-in tools for DIM. DIM recommends using Little Light's wish list editor which is a good stopgap, but it'd be great to have it all in one place. Ideally in the future it could be even better supported with more features like hosting, searching for others' wish lists, duplicating, etc, but I figured a basic editor would be a good starting point.

I have an early demo I spent a 4-5 hours on today and yesterday as a starting point: 

https://github.com/DestinyItemManager/DIM/assets/26357774/4fe90226-76c1-4300-a7aa-594b0fd924d5

If you're interested in the feature, I am happy to continue building it in my free time. I expect I could have a full demo by a couple weeks from now.

### How does this fit into your workflow?

This would give wish lists a more first-class citizen status as a feature for DIM. Rather than having to leave DIM to go to Little Light's wish list builder, it can be done directly in DIM. Additionally, we can support armor and DIM-specific features like trash lists, category-based rolls, and wildcard. This would greatly enhance the wishlist features for users of DIM.

**Comment by bhollis** [comment]
Thanks for starting to work on this! We'd definitely love some help working on this - I've had a lot of plans in my head but haven't had the time to work on them.

I haven't done a good job of listing out all the work we had planned for the next version of wish lists (which we really need help on!), so I've done that here: https://github.com/DestinyItemManager/DIM/issues/10313. We've avoided trying to replace the Little Light builder until we're able to offer significantly more functionality than it already does (e.g. integration with stored per-user wishlists). I think your demo is aimed at the last task in the list.

Regarding some of the future ideas - one thing to point out is that we won't be supporting wish lists on armor since it doesn't really have "rolls" the same way weapons do.

**Comment by mkossoris** [comment]
So I know armor doesn't have rolls like weapons do, but my thinking around also including armor is that someone could build a wishlist even for a specific build/loadout for example. And when we have hosted wish lists for users, they could use that to track progress toward creating that build. Alternatively, while armor doesn't have perks, they do have important stats, so if for example I wanted a specific helmet with a high resilience, I could add that to my wishlist. Just some ideas though!

**Comment by bhollis** [comment]
Thanks! Nobody's working on any of those tasks right now. The first step would be finalizing the new format.
