### ISSUE TITLE
Allow wishlisting any item with reusable perks

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10570]
Right now we restrict wish listing to weapons, but we could support anything with random-rolled reusable perks, which would include exotic class items, ghosts, sparrows, etc.

**Comment by Prometheus3375** [comment]
A bit related issue with Exotic Class Item card: it displays only two traits (curated?) instead of all of possible ones. Initially Light.gg also have such issue, but now it is fixed. This affects wishlist display: only present perks are displayed in wishlists.

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/5b66b359-757e-4532-aaec-4a950e932a9a)
