### ISSUE TITLE
Dupe exotic class items

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#10632]
### Proposed change

`is:dupe` is probably not suitable for this, but I'm proposing something similar to check for duplicate exotic class item rolls. 

### How does this fit into your workflow?

I have to keep checking manually if I got another duplicate exotic class item to drop, so I can get disappointed again. It would be nice if this was automated.

**Comment by bhollis** [comment]
My position is that a search is particularly bad for this use case, since the search will not show *which* items are duplicates, just which items have duplicates. Until this is paired with some extra tooling in Compare/Organizer to sort duplicates next to each other, I'm hesitant to keep adding new `dupe:` searches (see #9906).

I am considering finally implementing `is:dupeperks` though, which would inherently cover class items.

**Comment by Revadike** [comment]
Good idea!

For inspiration, or people wanting an alternative solution in the meantime, I recommend this tool from Blue Engram:
https://engram.blue/catchemall/classitem

**Comment by bhollis** [comment]
The Organizer now allows sorting by perks, there is an `is:dupeperks` search, and we have #10638 for adding perk sort in Compare. And the engram.blue site is more useful than all of those :-)
