### ISSUE TITLE
Max light function equips items which cannot be "dequiped" (unequipped) afterwards

### ISSUE THREAD

**Issue by doktor5000** [DestinyItemManager/DIM#1144]
When trying the "max light" function on a fresh lv8 alt, DIM moved an 393LL iron gjallarhorn from my primary character to the alt. Although now it cannot be moved/unequipped there anymore (presumably because currently I don't have any blue heavy weapon at all)
The message from DIM is

> **Iron Gjallarhorn**
> Cannot find another item to equip in order to dequip Iron Gjallarhorn.

 Maybe there should be a warning or a pre-check before maxing light, when one of the objects cannot be unequipped afterwards? (On a related note, this pre-check does exist already for other cases - e.g. when I now try to directly equip that iron gjallarhorn back to my primary character, DIM will move away any exotic weapon that this character has equipped, only to tell me afterwards what I already quoted above)

**Comment by bhollis** [comment]
That's an interesting corner case. I'm not sure what we should do here - more generally if there's only one weapon that could be equipped by a character, should we equip it.

**Comment by tcurtin** [comment]
Since this is a desireable action in some cases, but could cause real
problems (in this case, a low level character hogging your gally)... is
there any possibility of a confirmation dialog?  It seems like that breaks
the UI flow.  If not possible to confirm, I guess I'd vote for an error on
equip attempt.


*Tim Curtin*
Custom Logic Test Data Analysis
*T *+1 802.769.2791 <1.802.769.2791> | Tim.Curtin@GlobalFoundries.com
*GLOBALFOUNDRIES* 1000 River Road, Essex Junction, VT 05452

IBM/GF Contact tool: https://unity.btv.ibm.com/Applications/GFContacts/
Useful info for ex-IBMers: https://unity.btv.ibm.com/Documents/GF/

**Comment by doktor5000** [comment]
> If not possible to confirm, I guess I'd vote for an error on equip attempt.
Yup, sounds good. And people would still be able to equip such a weapon ingame if they really want it ...

**Comment by bhollis** [comment]
You could always go buy a heavy?

**Comment by doktor5000** [comment]
At that point in time there was no heavy for sale, had to play like an hour until the first one for that character dropped during the storyline.

**Comment by kyleshay** [comment]
Would be nice to cover this corner case for D2 as it seems fit.
