### ISSUE TITLE
Weapon comparison should allow for perk experimentation

### ISSUE THREAD

**Issue by bradchoate** [DestinyItemManager/DIM#1175]
It would be useful if you could toggle the perks on each weapon to further compare them, even if those perks have not been unlocked. Stats shown should reflect the enabled perk set.

**Comment by bhollis** [comment]
We don't currently know how to read the stat differences off the perks. It may be in there, but we haven't yet determined that.

**Comment by kyleshay** [comment]
it would largely need to be hard-coded:

https://github.com/adtennant/destiny-weapon-calculator

**Comment by brunnopleffken** [comment]
When creating my [Destiny Weapons Comparison](http://destiny-weapons-comparison.herokuapp.com/) app I read almost the entire JSON response to figure out how each perk affects the stats. There's no way to get these values because they're embedded into the game source-code.

For example: shotguns have a maximum allowed range of 32, regardless the base range stat. I can use Rifled Barrel + Aggressive Ballistics in my Matador 64 to reach 32 of range. Even if I change the barrel to CQB Ballistics (it increases range), it remains as 32 because there's an intrinsic limit.

The same way with snipers' stability. The lower limit is 15.

Even the barrels works differently depending on the weapon's class. In sniper rifles, these barrels increases/decreases a certain amount. In shotguns, they work some other way. It also depends on the weapon's archetype. Anyway... Is a great mess to figure out!

**Comment by bhollis** [comment]
@brunnopleffken that's great info, thanks!

Personally I'd like to avoid anything that requires us hardcoding or maintaining tables of data that doesn't come directly from Bungie.
