### ISSUE TITLE
DIM prompts for Bungie login, but login is already active, even with signing out and signing back in

### ISSUE THREAD

**Issue by colindashots** [DestinyItemManager/DIM#1185]
For the last few days, DIM has not allowed me to access content, prompting me that Bungie login required. I've ensure I am already logged in every time, as well as signing out and then signing back in. Is this a known bug?

**Comment by bhollis** [comment]
Nope. Could you post a screenshot, ideally with the developer console open?

**Comment by colindashots** [comment]
I am already logged in to my Bungie.net account at this point before opening DIM. DIM then prompts me to login with the error message stating Bungie.net login is required and opens an additional Bungie.net tab.

<img width="1248" alt="screen shot 2016-11-24 at 6 55 23 am" src="https://cloud.githubusercontent.com/assets/23445748/20602643/168a1100-b213-11e6-8de9-c8a1a3afebcb.png">

**Comment by SunburnedGoose** [comment]
Clear your cache & cookies, and log into Bungie.net again.

@bhollis This is related to adding 'www.' to the domain when looking for the bungie.net cookie, at Bungie's request.  The reason we used wildcards in the past is because for some reason, and I am not sure why, the cookie gets set on 'bungie.net' and not 'www.bungie.net'.  Atm, I'm just telling people to clear their cache until we get OAuth enabled.

**Comment by colindashots** [comment]
Tried clearing cache previously as well, but I'll give it another shot.

**Comment by SunburnedGoose** [comment]
Let me know if it works out.

**Comment by colindashots** [comment]
This time it worked. Not sure why previously it didn't. Thanks for the help!
