### ISSUE TITLE
Ghost Perfection Spreadsheet

### ISSUE THREAD

**Issue by WelshWillisGaming** [DestinyItemManager/DIM#1206]
Hi there,

I have created a Google Spreadsheet that factors in the relationship between the material and glimmer bonus. Basically anything that is related ie Relic Iron and Cabal glimmer bonus is perfect while Spin Metal and Vex is imperfect. I would love to share this with the community and I would only like to highlight the stats section according to your tier 12 colour code, with your permission of course.
If you want I can link you to the page and if you like it and think it's possible, you can use it in DIM.

I look forward to your response

Welsh_Willis (PS4)

**Comment by bhollis** [comment]
Cool! I think we could do this automatically (without a spreadsheet) by using a table of which enemies live in which locations, and then looking at the perks on the ghost. One question is where we'd put that info though, since we already reserve the rating and color for the actual int/dis/str stats.

**Comment by simonefranza** [comment]
@bhollis What about simply adding under "Stats quality {{percentage}} of max roll" something like "Material/Glimmer {{rating}}"?

**Comment by delphiactual** [comment]
what happens with a crucible ghost that gives bonus glimmer on warlock kills, etc. Does it automatically get an imperfect rating, it should instead be shown as a crucible ghost.

**Comment by bhollis** [comment]
Closing this because D2 is where it's at.
