### ISSUE TITLE
Yarn.lock for local dev? 

### ISSUE THREAD

**Issue by chuckreynolds** [DestinyItemManager/DIM#1208]
Using YarnPkg.com more recently instead of npm... wondering if adding the lock file for package control is okay with you guys as you seem to use npm? 
I'll do a PR for it; if you use it yay, if not i'll just ignore it locally for this repo.

see: https://yarnpkg.com/en/docs/migrating-from-npm

**Comment by bhollis** [comment]
Hi Chuck, Yarn is pretty cool, but I'm not aware of any problems we're having with NPM or that switching to Yarn would help out anything. I'll let the other contributors reopen this if they want, but my preference is to keep things simple by not adding support for everyone's individual dev preferences.

**Comment by jflayhart** [comment]
I would second this only because I have professionally experienced much faster installs (saves time for installs) and better deps management using yarn. I haven't used it cause "it's new and cool", but rather it was a practical choice. I wouldn't call it a life saver or anything ground-breaking to where we need it, but like you said, it is nice and it is slightly more enjoyable to use than npm.

**Comment by bhollis** [comment]
Thanks for the concern, but we'll stick with npm, which will absorb yarn's features soon.
