### ISSUE TITLE
[i18n] MovePopup

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1280]
@brunnopleffken, @simonefranza, @Korben85, @JaviG1105, @yannickguillemot 

| EN | EQUIP | STORE | TAKE | SPLIT | STATUS |
|-----|--------|--------|-------|--------|---------|
| DE | AUSR | LAGERN* | HABEN | TEILT | |
| ES | PONER | METER | TOMAR | PARTIR** | ![es](https://cloud.githubusercontent.com/assets/4798491/21238875/ed8b3e72-c2c1-11e6-8996-d61f06554c0b.png) |
| FR | ÉQUIPER* | DÉPÔT | FAIRE | DIVISÉ** | |
| IT | USA | MOUVI | PRENDI | DIVIDI | ![it](https://cloud.githubusercontent.com/assets/4798491/21238814/aaaf1f1a-c2c1-11e6-840d-1fa02b76f6fc.png) |
| PT-BR | EQUIP | MOVER | TOMAR | DIVIDIR*** | ![pt-br](https://cloud.githubusercontent.com/assets/4798491/21238835/ca538176-c2c1-11e6-95c1-5b16e0f0b607.png) |

*If we can get these words down to 5 characters in length, we can then translate the `MovePopup` completely.

** fits due to the `i`

*** kind of fits see screenshot

`FR` - `ÉQUIP` ?

**Comment by JaviG1105** [comment]
For spanish it could be:
EN: EQUIP - STORE
ES: **PONER** - **METER**

**Comment by delphiactual** [comment]
@JaviG1105 Do the other 2 translations make sense for Spanish?

**Comment by JaviG1105** [comment]
@delphiactual TOMAR is great, RAJAR is kind of weird but it gets the job done, "CORTAR" or "PARTIR" would be perfect but they're six letters long. RAJAR is the best most accurate you're gonna get with 5 letters. 👍

**Comment by delphiactual** [comment]
PARTIR will fit because of the I, so I'll change the table above to reflect that
![screenshot 2016-12-14 19 22 15](https://cloud.githubusercontent.com/assets/4798491/21209654/c3920248-c232-11e6-82c6-6a6ca717d9f5.png)

**Comment by simonefranza** [comment]
For Italian it's a bit tough..
EN: EQUIP - STORE - TAKE -SPLIT
IT: USA(it's like utilize, it's not so nice, but there isn't another word with 5/6 letters) - MUOVI (like move, again kind of weird) - UNISCI/PRENDI (I don't know what is meant. unisci is like merge and prendi is the exact translation for take) - DIVIDI

**Comment by brunnopleffken** [comment]
To PT-BR is not that easy:
- EQUIP = EQUIPAR, maybe change it to USAR (means _use_), but doesn't sound as cool because you equip equipments. Leave it as "EQUIP", because seems and sounds like an abbreviation of EQUIPAR.
- STORE = This is really tough! Actually is ARMAZENAR in Portuguese ("loja" is the store where they sell things) - it's definitely not short. GUARDAR has the exact same meaning but is also too long. Well... MOVER (means _move_) is the better I can think and it do what it says.
- TAKE = This meaning of _take_ is TOMAR. What this action does in DIM also works with JUNTAR (merge/join).
- SPLIT = The better is DIVIDIR ("cisão" is a way too formal word). Maybe it fits because of the 3 `i`.

**Comment by delphiactual** [comment]
@brunnopleffken, @simonefranza: see screenshot in main post

**Comment by Korben85** [comment]
EN	EQUIP	STORE	TAKE	SPLIT
DE	AUSR	**LAGER**	**NIMM**	**TEILE**

**Comment by delphiactual** [comment]
@Korben85 added these to transifex today with the length requirement
