### ISSUE TITLE
Tracking completion of armour and weapon sets.

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#1298]
The one last thing that I struggle with in Destiny is tracking what raid items I've collected so far. I'm wondering if a feature that helped with this, by tracking completion of various armour and weapon sets (RoI raid normal/hard, Days of Iron, etc) would be in the scope of DIM?

As there's no API for sets, this data would need to be manually maintained and updated every time Destiny updates with new content, which is annoying. I guess tooling could make this process easier.

Anyway, is this something that you think this project to manage? I would love to contribute and help out with this feature, but the codebase is pretty unforgiving to newcomers...

**Comment by bhollis** [comment]
I've got something like this in a branch from way back. There actually is API data for sets, and it's pretty easy to get. That said, I haven't really found a great display for this. There are a *lot* of sets, and a "collection" screen as I had mocked it out was super overwhelming and didn't give the sense of "cool" that I was hoping for. For me it was mostly stressful because it was a ton of stuff that I didn't have. We could add a bunch of configuration data, but that's something we'd have to master and honestly Destiny has enough inventory management that we shouldn't be adding to it.

Let's use this issue to discuss more ideas around this, and I'll ressurect my branch if somebody wants to poke at it.

**Comment by joshhunt** [comment]
Oh interesting - what's the API/data source for this? I'm assuming this is in the mobileWorldContent dump?

**Comment by bhollis** [comment]
Yeah it's in the manifest with the rest of the item data. 

-Ben

**Comment by bhollis** [comment]
I'm closing this because I don't think it's something that fits, at least until some day when we have unlimited vault space!
