### ISSUE TITLE
Option to replace T1..5 bars with text, e.g. "T4: 4:39"

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1378]
It'd be nice if I could replace the visual T1..5 indicators with the text "4:39 (T4)" or "T2: 0:39" or whatever, so that the most valuable piece of information when crafting loadouts - the time for recharge - is right there in front of me, rather than having to constantly mouse-over it to try and learn.

**Comment by bhollis** [comment]
In general we try to avoid a lot of options. Since the game displays these as bars from 1-5, we figured it made more sense to do that too. Showing just the time doesn't give you a good sense of what the next jump will be, or whether you've maxed it out (plus it's just too visually noisy). That's why that info is in a tooltip.

**Comment by floatingatoll** [comment]
Cool, WFM.
