### ISSUE TITLE
Notifications Support

### ISSUE THREAD

**Issue by EffortlessFury** [DestinyItemManager/DIM#1424]
My idea is to have a central notification service that supports registering two other types of services:

A. Notification generators. Ex. New loot received, roll quality xx%.
B. Notification recipients. Ex. Chrome, Pushbullet.

Either of these services will have their module register with the notifications service in a "run" step. They'll provide description information and hooks into configurable settings. This way, the notifications service can expose these generators and recipients in a settings window and allow users to configure what notifications they want and where they want them to go.

Then, the notifications service can return a hook to each notification generator after its registered (to prevent a notification from getting pushed to the service if it hasn't registered). The notifications service will then hand it off to each of the configured recipients.

**Comment by bhollis** [comment]
What sorts of things would you like to do with this framework?

**Comment by EffortlessFury** [comment]
The impetus for the idea was to notify a user of the quality of their new gear. The intention is to design it so that other developers can create new notifications easily.

**Comment by EffortlessFury** [comment]
Prototype in a fork branch https://github.com/EffortlessFury/DIM/tree/notification-prototype

**Comment by delphiactual** [comment]
@effortlessfury you should submit a PR so this does not get lost

**Comment by bhollis** [comment]
Linking #1874 which is how I think I'd like this to look.

**Comment by bhollis** [comment]
(specifically, I think we should have a saved-searches menu, and you should be able to toggle a button to enable notifications on those searches)

**Comment by jamieisboss** [comment]
This is exactly the feature I was hoping for! 

Issue is labeled need more details so in case my thoughts are useful to you:

My main use case would be to have a saved search for  "is:weapon rating:>4" which would notify me.

Quite a few times, especially when I was still getting the hang of the D2 weapons system, I've gotten a weapon which didn't seem particularly special and dismantled it, only to realise it's usefulness later. 

Very specifically, I'm pretty sure I dismantled a Uriel's Gift before I got to the endgame and haven't had another one drop since, prompting me to come checking for a "Tell me if I get something good in case I didn't realise" feature.

Other Search Notifications I thought of that I would be using at the moment:

- is:masterwork is:helmet is:warlock (or similar) Just because I'm grinding to get one at the moment 
- stack:>=10 Radiolarian Culture
- "Gift of" - because i often dont notice "Gift of Vanguard Tokens"

**Comment by bhollis** [comment]
Thanks for responding! It's very useful to understand the "why" of a feature request rather than the "what".

In your scenario, how would you have known to set up a notification for Uriel's Gift, though? Wouldn't our ratings system have been better equipped to tip you off that you're discarding a well-regarded weapon?
