### ISSUE TITLE
Logic error with some T12 alternatives

### ISSUE THREAD

**Issue by TerraReef** [DestinyItemManager/DIM#1475]
DIM will show me that I could have a Tier 12 setup using a particular ghost or class item, but only show one particular ghost or class item when there are others with identical Intellect/discipline/strength rolls.  

I am guessing maybe there is an error in the logic or alternatively it was decided including all of these would add immensely to the options/clutter.  I have a lot of options and want to collect glimmer in crucible, use a class item that gives me more rep in the crucible, and for my character to not look ugly.  (I know picky on some of these and won't matter to a lot of people, but I am sure I am not completely alone)  Class items significantly impact how a hunter(my main) looks.  If there was a decision that was made to make these alternatives hidden can we have a box to select this as an option?  

Here is an example:  
![image](https://cloud.githubusercontent.com/assets/2903942/22868677/788ec232-f166-11e6-80cb-da0696445ea9.png)

**Comment by TerraReef** [comment]
Here is an additional example: 
![image](https://cloud.githubusercontent.com/assets/2903942/22868746/465bc3f4-f167-11e6-8c2f-9b64126f5998.png)
If I could use the one class item, I could really use any of the ones with red X on them, but DIM doesn't show this as a possibility.

**Comment by tcurtin** [comment]
I've always wondered about this too.  I've always handled it by the kludge of adding items to the Exclude list until no more options are found, and then choosing from the ones added.

(Also, I'l acknowledge that every issue I've found previously had already been solved in some way I hadn't caught, so looking forward to the answer here!)

**Comment by TerraReef** [comment]
As I started it may seem like a trivial thing to not see all ghost or class item choices, but it makes me curious about why they are missing and what other things may be missing/ignored.  One of the biggest benefits to using DIM is the load out builder but is the load out builder even working as intended?

**Comment by delphiactual** [comment]
@TerraReef clicked on `Advanced` and what is your processing mode set to? `Full` or `Fast`?

**Comment by bhollis** [comment]
Sorry, I'm not 100% sure what's being pointed out here. Are the alternate items not showing up when you expand "Show all configurations"? Phrasing this bug report in the form "I expected to see X, but instead I saw Y" will help us figure out what could be fixed.

**Comment by TerraReef** [comment]
I am using full.  
Sometimes DIM shows multiple load out as the bottom, sometime just one.  If I have locked everything but the helmet and I only see one option I assume there is only one 552 option.  I would expect to see more then one option if there was more then one option.  Example:  
![image](https://cloud.githubusercontent.com/assets/2903942/23390057/b9062862-fd39-11e6-9227-be8dce115ee2.png)
Now after seeing the above you would expect that if I dragged the red helmet to the Exclude area... I wouldn't have any more 552 and DIM would go on to offer a 444 or a 551 or something.  
![image](https://cloud.githubusercontent.com/assets/2903942/23390124/28eaad24-fd3a-11e6-8e18-c3d293d9b71b.png)
Why didn't it show me this helmet before?  Crap this one only has PVE and I am trying for a PVP build.  
![image](https://cloud.githubusercontent.com/assets/2903942/23390149/57317794-fd3a-11e6-9ed9-45dabdd49505.png)
There is yet another helmet that would give me a T12 552 build, but it also didn't show up.  In all of the above images I had just refreshed the browser and as you can see "full" is checked as the processing mode.

**Comment by TerraReef** [comment]
In all of the above images I had scrolled all the way down.

**Comment by bhollis** [comment]
Makes sense, I think. Let's see if I can rephrase it:

"I would expect to see a separate suggested loadout for every possible combination of items, including when they have exactly the same stats. Instead, I see only one combination per item with the same stat."

Seems like something we could try to change. I'm not sure if the original intention was to cut down on duplicates or not.

**Comment by kyleshay** [comment]
Right, this is currently expected behavior. To iterate every combination would require a bit more processing power (thus it would take MUCH longer time.) We currently look for your best equipment, and build sets out of that. If you want a specific helmet, you have the option lock that item and build sets around it.

A better option, if you're building a PvP or PvE set, would be to lock the perks that you'd like to see on each equipment. You have the option or AND/OR them. 

I don't see us adding in showing additional sets as is would not only show way too many options, but it would also take much longer to process. Two identical sets, one with a 24/25 ghost, and another 25/25 ghost both might give you a 5/5/2 set, so we'll only show the 25/25 option because showing the 24/25 option is pointless. If that 24/25 gives you glimmer for killing titans, and thats what you wanted, then you should lock those perks, and it would have showed up as an option instead.

Agreed that UX flow could be streamlined a bit, and I think that is where we should focus our efforts. Ideally we'd show even less options. More options = not always a great thing, especially for new users.
