### ISSUE TITLE
A suggestion for current loadouts in DIM.

### ISSUE THREAD

**Issue by mohvmvd** [DestinyItemManager/DIM#1545]
First of all, I'm new and I apologize if this is not the right place to submit the suggestion.

I think I have a very useful suggestion for DIM developer/s: can you make an update that give us the ability to see (Int/Dis/Str) configurations when editing current loadout? Just like what we see when building the loadout. That would really be helpful to figure out what to change since many of us have more than one loadout with the same gear. I hope you know what I mean. If not, I would be pleased to take screenshots with some details. Wish that you can make this happen. Anyway, what a great tool is this for Destiny's community. Thanks a lot! you guys are awesome.

screenshot to what I mean: https://ibb.co/fU2W8v

**Comment by kyleshay** [comment]
Makes sense. We'd only be able to show it for equipped items if you have one of each equipped though.

**Comment by weborican** [comment]
Isn't this the same as issue https://github.com/DestinyItemManager/DIM/issues/720 ?

**Comment by bhollis** [comment]
@weborican, no, this is for when you're making a load out normally, not the loadout optimizer

-Ben

**Comment by weborican** [comment]
Both his description and his screenshot show an edit to a current loadout, not creating one normally.

**Comment by weborican** [comment]
I predict this would be a rather tricky implementation since you would have to change the data structure of the loadouts to include that information. Calculating it on the fly wouldn't work since that exact armor set that gives you a 5/5/2 loadout could also possibly give you a 5/2/5, a 5/4/3, etc.

At the moment I handle this by equipping my loadout, going to the Loadout Builder, clicking on Locked Equipped, and then clicking on the Filter Sets pulldown menu to see what other builds I can have for that loadout. Kind of tedious, which is why I wanted something similar to what @mohvmvd is asking for. I believe his and my request back on issue #720 could be one of the same, and in that way we wouldn't need to duplicate loadouts using the same gear (one for 4/4/4, one for 5/5/2, etc.). Ii would be dope if we could equip a loadout and somehow easily see what I/D/S nodes need to be selected for all possible combinations :-)

**Comment by bhollis** [comment]
@weborican it doesn't sound too hard to me, and I'm sure it's a different thing.

**Comment by bhollis** [comment]
Implemented in #1599.
