### ISSUE TITLE
Move `Record Books` to right in header

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1576]
Using icon fa-book

en - `Record Book`
es - `Libros de records`
fr - `Livre des Records`
it - `Registri`
ja - `記録ブック`
pt-br - `Livro de Recordes`

**Comment by bhollis** [comment]
Here's how I think about the header (absent a real spec). The left is for information about your stuff in the game - vendors, inventory, record books, etc. all nice and spelled out. Right side icons are for tools and other more obscure stuff. loadout Builder is an advanced feature, as is settings. Given that interpretation the about and support pages are a bit weird on the left but I don't think they'd survive as icons. 

Philosophy aside, text is better than icons in general - people often miss the load out builder because they don't realize what it is. Both is even better. If we have a problem with header space we should just implement a responsive menu. 

-Ben
