### ISSUE TITLE
Weapon Ratings only from trusted reviewers

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1749]
Add option to weapon-reviews to only display trusted-reviewers reviews, and only calculate rating based on trusted-ratings.

**Comment by bhollis** [comment]
Do we have a concept of trusted reviewers?

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/issues/1713#issuecomment-308497442

**Comment by kyleshay** [comment]
we do, i think it's the `isHighlighted` flag on a reviewer - will verify with DTR

**Comment by kyleshay** [comment]
So that option is there with that flag `review.isHighlighted`:
<img width="320" alt="screen shot 2017-07-11 at 9 09 24 am" src="https://user-images.githubusercontent.com/424158/28078146-c4a32790-6618-11e7-8bca-632179b43419.png">

----

For this issue are you suggesting that on the reviews tab of a weapon you can click to filter out every review except for the highlighted reviewers stuff? 

We don't get the reviews for an item until you open the move popup.

**Comment by tcurtin** [comment]
An alternative thought that might accomplish the same thing would be the ability to filter on a count of reviews.  At least for now, there are a lot of weapon/perk combos with only a single rater -- I'd personally rather not trust the reviews until there's a consensus.  (I'm sure this will improve quickly with static perks and more users in D2.)
For instance, I only want to see rating:<=4 with ratingcount:>5

**Comment by delphiactual** [comment]
@kyleshay no I mean ratings are calculated based on highlighted reviewers only... i.e. 3.6

**Comment by kyleshay** [comment]
should be possible, but that would require a server side (DTR) change.

**Comment by kyleshay** [comment]
cc @48klocs - any thoughts?

**Comment by 48klocs** [comment]
The API for D2 returns a highlighted reviewers flag, but there aren't any reviewers actually marked as highlighted on their end. We could add that search flag, but it would only work in D1. It would confuse the bulk of D2-using folks, so I'm not going to add that.
