### ISSUE TITLE
How are reviews tied to a specific weapon / roll?

### ISSUE THREAD

**Issue by SublymeRick** [DestinyItemManager/DIM#1828]
What actually defines the weapon you are reviewing? I ask because I have two different palindromes that have different reviews on them. I initially thought the reviews were based on the the specific perk rolls of the gun, which would be awesome.... however I have a hawksaw and the reviews are for all different perk loadouts. See attached screen shots:

![image](https://user-images.githubusercontent.com/3813238/27576276-12f8d5bc-5ae2-11e7-9b08-55369a4ad610.png)

![image](https://user-images.githubusercontent.com/3813238/27576286-219cc45c-5ae2-11e7-8d89-a95422783656.png)

![image](https://user-images.githubusercontent.com/3813238/27576316-34d4d76c-5ae2-11e7-84e9-a190886133f0.png)

**Comment by SublymeRick** [comment]
I do notice that all the hawksaw reivews seem to have "full auto" in common. Is the defining factor a single "main" perk such as the hawksaw's main middle park?

I really think the reviews should be specific to the full perk set of each gun. You could easily do this by hashing all the perks with the gun name and then using that as the identifier to link reviews and ratings.

**Comment by bhollis** [comment]
@48klocs any idea?

**Comment by 48klocs** [comment]
@SublymeRick at a high level, we're passing over the weapon ID and collecting all of the perks it has available on it, so reviews that come back should be tied to one of the selected perk loadouts you can choose for a given weapon.

The text of the review isn't tied to the roll of the weapon, so user error could be a thing (but if you see all of the reviews mentioning full auto and your roll isn't, I'd want to investigate).

It gets more complex because the API folks are dropping some perks (ones that aren't randomly-rolled and other perks which we've decided can't affect ratings) behind the scenes, so it's possible that there could be some bleed-over there.

We've been waiting for more reviews to come in to see if visualizing the different ratings that different perk loadouts for a single roll is a thing that makes sense.

To answer the logical next question, we send not only available perks, but selected perks on a given item.

**Comment by SublymeRick** [comment]
Thats perfect, because using the selected perk would be my ultimate goal if I were programming it 👍

**Comment by elviswolcott** [comment]
It seems like reviews take into account the 1st and 3rd perk on a traditional weapon and drop the middle tree. I think it should consider the middle tree because especially with hand cannons if you don't have middle tree rifled is the difference between a 2 or 3 star and a 4 or 5 star.

**Comment by sgtfrankieboy** [comment]
What 48klocs said is true, we only use the selected perks in the talent grid. A problem however is the definition of perk.

Each Perk in a Talent Grid _can_ have a hash that can be used to identify it. We currently use the selected perks that have a hash to return the review data.

However, not all perks actually have that hash. Because of this those nodes are ignored. Which can include perks or stuff like Reinforced Barrel.

We are also filtering out a lot of hashes that have a null name in the Destiny Manifest file.

**Comment by bhollis** [comment]
Can we put together a wiki for this and link to it from the app?

**Comment by bhollis** [comment]
@sgtfrankieboy we should brainstorm on this a bit - it'd be neat for the reviews to tell me I have a great roll even if I have the wrong perks selected.

**Comment by SublymeRick** [comment]
Normally I would agree @bhollis, however in d2 there is not going to be varying perk rolls per weapon so I guess its kind of moot at this point.

**Comment by 48klocs** [comment]
@bhollis the API is giving us the information, it's more on us to interpret and visualize it sensibly. 

I think that guiding users to better perk selections will be something useful with D2 as well.

**Comment by SublymeRick** [comment]
@48klocs if we even have the ability to change perks in D2... That latest interview with Luke Smith made it seem like each weapon has pre-defined perk set ups on them and to me it kind of seemed like they are not only static but sans-optional switches like we have now. Its all about balance for them now. I could be wrong on the not being able switch but they definitely did say that the perks for each weapon are hand crafted and random rolls are staying in D1.

**Comment by kyleshay** [comment]
D2 we could consider doing reviews by item hash, allow reviews, and let people upvote the best perk roll combo
