### ISSUE TITLE
Export spreadsheet for D2

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2189]
Players are looking to export their data again as they did for D1 from settings.

**Comment by burnsdg** [comment]
YES!
And PLEASE PLEASE PLEASE can you make the export order the same as is displayed in DIM itself?

**Comment by rslifka** [comment]
Yep, the buttons are there but when you press them nothing happens.

**Comment by rslifka** [comment]
The issue is that this line is triggered:

https://github.com/DestinyItemManager/DIM/blob/6a29b1b793a3866251c9361061f37aa0e52eac00/src/app/inventory/dimCsvService.factory.js#L201-L204

...and the function aborts there. Not super well versed in Angular, just hoping to provide a starting point for the developers :)

**Comment by delphiactual** [comment]
this is because we have yet to update this code to work with D2

**Comment by rslifka** [comment]
https://github.com/DestinyItemManager/DIM/blob/6a29b1b793a3866251c9361061f37aa0e52eac00/src/app/settings/settings.component.js#L86

...is where `getStores()` returns `[]`. It looks like stores are implemented for the D1 API and not the D2 API, which makes sense given it's only been out for two weeks :)

**Comment by rslifka** [comment]
@delphiactual Gotcha, thank you and thank you for all your hard work on DIM! Heading over to donate now :)
