### ISSUE TITLE
[Feature Request] When loadout is applied move items not included it in to Vault

### ISSUE THREAD

**Issue by pogarek** [DestinyItemManager/DIM#2230]
I have 3 loadouts and I love them. However when I apply one of them, the items, which are not in the loadout stay on character. I would like to get them transffered to Vault.

**Comment by bhollis** [comment]
Linking #224. Out of curiosity, why do you want to have all the other items moved to the vault?

**Comment by pogarek** [comment]
Yes, everything which is not in loadout. Imaging that you switch 2-3 layouts with different gear. The not used one will stay , so new drops would go to Postman, because slots are used.

**Comment by bhollis** [comment]
Why not just turn on Farming Mode so drops don't go to the Postmaster? That's what it's for.

**Comment by pogarek** [comment]
Yes, I know that. I just like to have specific items on my character for different modes. I have a 2 PvE and 2 PvP loadouts. I don't want to carry anything else, that items in that sets.  Maybe I don't understand Farming mode fully, but I like to have a control on my equipment :-)

**Comment by mcdonamw** [comment]
I would like this as well.  I have a preferred set of gear and like to leave a few slots open for drops so I can manage them as I get them.  It would just be nice add on to the build functionality.

**Comment by daveequalscool** [comment]
I've been hoping for this feature as well, or at least some option to quickly send all of a character's stowed weapons to the vault. To expand on the answer @pogarek gave, let's say I have a loadout with three good kinetic weapons that I'll want to switch between based on encounters. If I equip the loadout but I'm still carrying 7 other kinetic weapons, I have to wade through them in the character screen to find the guns I intentionally brought along. Right now the only way to have a "lean" loadout like this is dragging the undesired weapons to the vault one by one.

**Comment by bhollis** [comment]
Linking #224 but I think this ("clean loadouts") is nicer than having to manually add empty slots.

**Comment by nessus42** [comment]
Hi. I've been waiting for this feature for a long time! It's really my only complaint with DIM, which in almost every other respect I love.

However, I would prefer [https://github.com/DestinyItemManager/DIM/issues/224](#224), rather than this version. For instance, I often have separate weapons and armor loadouts, so I wouldn't want my weapons loadout to move all of my armor into the vault.

**Comment by bhollis** [comment]
My plan was to avoid lots of options, and instead have one checkbox for "clean loadout", and then I'd clean out any bucket that the loadout touches. So if your loadout only has weapons, it'd clear out other weapons but not armor, etc.

**Comment by daveequalscool** [comment]
I'm warming up to your approach, @bhollis . It sounds like you would be adding this as a boolean property that would be saved along with each loadout, so some loadouts would be "clean" and others wouldn't. Have you considered instead allowing any loadout to be equipped either way? In other words, let the user decide while equipping the loadout whether to do it cleanly or not? Just putting it out there even though i'm happy with either approach.

**Comment by bhollis** [comment]
Yeah I'm thinking it's a property of a loadout. This is already a pretty fringe feature, so making it a split button option or prompt for applying every single loadout would be too much. Plus you'd have to remember which one you want every time. 

-Ben

**Comment by nessus42** [comment]
@bhollis Your idea sounds great to me!

**Comment by noahkretz** [comment]
I would love this "clean loadout" option for my PvP guns.  It's not unusual to swap guns based on the map or whatever the enemy team is doing, and you don't want to spend a lot of time looking through the guns you wouldn't even consider.

This would also help me combat the "unused item creep" that happens when I shuffle loadouts around from character to character.  I'm sure this is because you can't leave your character with nothing on, so at times DIM pulls something from the vault to equip it, just so it can move something you want to move, but eventually I've got 5 oddball weapons clogging up my inventory that I had in the vault just for the sake of having them.

**Comment by walkerjam** [comment]
This would be really handy for the reasons mentioned above, plus to accommodate us OCD types 😄

**Comment by nessus42** [comment]
Hi. I'd just like to chime in that this would be incredible feature for DIM to include. I love DIM and think it is one of the best programs ever made, but I find the lack of this feature to be a huge annoyance and to greatly decrease the value of loadouts. When I currently apply a loadout, I typically end up with all my weapon slots filled, and I find it unpleasant to play that way. I.e., I either have to move stuff off the character manually, which somewhat defeats the purpose of the loadout, or new weapon drops end up going to the Post Office,  which I don't like, since I want to immediately examine the drop.

Also, if you get multiple Powerful Grear drops at the same time, like from doing a Nightfall, the first drop could increase your max LL, which would increase the LL of the second drop, but this doesn't work if the drops go to the Post Office. (Maybe Destiny is smart enough to include drops in your Post Office for calculating your max LL, but I wouldn't put any money on that bet.)

**Comment by delphiactual** [comment]
@nessus42 before you apply your loadout you can cleanout your extra weapons and armor by searching `is:incurrentchar not:equipped is:haspower` vault drop-down -> transfer search... Then apply your loadout... And if you want the other items that were equipped but are now sitting in your inventory removed `is: incurrentchar not:in loadout is:haspower` vault drop-down -> transfer search

**Comment by bhollis** [comment]
There’s also farming mode which will keep one slot open at all times.

**Comment by nessus42** [comment]
@delphiactual Thanks for that tip! (There's no way to save and name searches in DIM is there, however? Sure, I can type the search into a document and cut and paste from the document to save some typing, but....)

@bhollis I'm excited to see the "Move other items away" option in the new Loadout Creator!
