### ISSUE TITLE
D2 - global vault sorting

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2311]
my current vault:
![dim](http://zoggy.net/firefox_2017-10-04_23-51-00.png)

You can augment how its displayed by the DIM setting 'sort items by'.. 
So it *should* be sorting by `Primary Stat`, but its not. It is actually sorting by `Name`.

I'm asking to have the 'vault' have its own sorting option.
I would assume most people dont want to sort the vault (mods/shaders/etc) the same way as what is on the player..

FYI, In the game you can sort the vault by quantity, newest, rarity.

**Comment by kyleshay** [comment]
When you have the primary stat sort enabled, what is not being sorted by the primary stat?

That's what I'm seeing here:
<img width="212" alt="screen shot 2017-10-05 at 8 54 39 am" src="https://user-images.githubusercontent.com/424158/31237136-e2efffea-a9aa-11e7-9cc2-8adb769263b7.png">

Do you mean specifically for the items in the general section? If so, that is because they don't actually have a 'primary stat' so they fallback to name. 

In D1 we had a custom sort for the general type items, which we still need to manually curate for D2. 

Eventually we will have some additional sorting options implemented from #573 and #647
