### ISSUE TITLE
Problem with orientation/rotation screen (portrait/landscape) 

### ISSUE THREAD

**Issue by marcello** [DestinyItemManager/DIM#2402]
I have the problem with orientation screen. I'm waiting for a long time to change from portrait to landscape.

**I would like suggestion to create one button to lock the orientation.**

I love DIM and you make the great job.

Thanks to all!

**Comment by nki2bpz** [comment]
+1 This started in 4.21. i should have posted it then. It hangs on switch and leaves the graphics shown in pics. What has been making it really impossible is every time you do something it refreshes and starts the process all over again. ive been using laptop since 4.21
![screenshot_20171025-072046](https://user-images.githubusercontent.com/15946723/32478758-878b67b6-c354-11e7-94be-e90ba9ed0e3a.png)
![screenshot_20171104-104604](https://user-images.githubusercontent.com/15946723/32478765-8cb89ec0-c354-11e7-8571-779f1ee2eb68.png)
![screenshot_20171026-032752](https://user-images.githubusercontent.com/15946723/32478771-917c2cba-c354-11e7-8cf0-8c8e69ce3e5c.png)

**Comment by bhollis** [comment]
So we’re talking about Chrome on Android then?

-Ben

**Comment by nki2bpz** [comment]
For me yes, latest version of both. same for #2408

**Comment by duckmanBR** [comment]
I talked about this on Discord when someone asked about it.  I believe it's related to memory consumption.

On my phone (Moto G4Plus / Android 7.0 / Chrome Beta 63.0.3239.31) the full transition between portrait to landscape takes around 15 seconds (almost half of that from landscape to portrait). And also unloads all the persistent notifications. (that's why I think it's memory related).

@nki2bpz not even a full refresh (pulling from top, not the refresh icon in app) solves the problem? I also didn't understand the "is every time you do something it refreshes and starts the process all over again"...

@marcello since DIM is not an app (the icon on the homepage is simply a shortcut to chrome in full screen) it's probably not possible to force a no-rotation rule.  What I usually do is to keep the android rotation toggle as close as possible and toggle it when needed.

**Comment by marcello** [comment]
The discussion was to the loadouts although (#2408) I think that's better pass the control to the hands of the users. Create possibilities to use the auto and manual mode. I would like to control the behavior and do not use the auto mode. I understand that many users are going to use auto mode but the other users the opposite mode. Thanks for good jobs!

**Comment by marcello** [comment]
@duckmanBR Is it possible to lock into the landscape mode? It is my problem but I could not do it. The overview in landscape mode is very useful in comparing sortable items. The best for me and the reason for the use DIM intensely. I teach all my friends this features. :-)

**Comment by duckmanBR** [comment]
@marcello, no the Android/global lock is only to portrait.
but this is not the main subject of the issue, if you want to talk more about it create a new issue (like a request/idea).

**Comment by marcello** [comment]
@duckmanBR :+1:

**Comment by bhollis** [comment]
FWIW on iOS the transition takes about a second. 

-Ben

**Comment by nki2bpz** [comment]
Same on android prior to 4.21 only time it really took longer is if it was refreshing during the rotation

-------- Original message --------

**Comment by bhollis** [comment]
I'd look at https://github.com/DestinyItemManager/DIM/commit/c7a677e1582c3237cfd3f5c69442fdcd246daa4f for a cause. Or, the recent upgrades in dependencies.

**Comment by bhollis** [comment]
@marcello I don't want to add a lock feature to fix this - instead, I'd like it to just be fast, like it is on iOS.

**Comment by marcello** [comment]
@bhollis I like the two options. Fast and controlable!

**Comment by duckmanBR** [comment]
Don't know if it helps, but closing all the main sections (darker background) the rotation change becomes almost instant.
But as I open the weapons section the time becomes almost as long as all of them open.

**Comment by bhollis** [comment]
Yeah, it does have to rebuild all the items into a new display when it rotates.

**Comment by bhollis** [comment]
There's a fix for the performance issue in #2512.

**Comment by bhollis** [comment]
Try it now? It should be way faster thanks to #2512.

**Comment by duckmanBR** [comment]
Not as fast a before (maybe because of the ratings or maybe I just have x2 more items). Now takes 2-3 seconds to redraw the page.

**Comment by nki2bpz** [comment]
Wayyyy better than last week.
