### ISSUE TITLE
Search: is:<class> is not finding <class> specific mods 

### ISSUE THREAD

**Issue by 3rd-Eden** [DestinyItemManager/DIM#2438]
**Steps to reproduce**

1. Have an item mod that is specific to a class like a hunter cloak mod or a titan butt rag. 
2. In the search bar enter: `is:titan`

**Expected result**

- The `is:<class>` search option includes the Inventory slot and finds the titan specific butt towel/rag mod is highlighted.
- User is happy

**Actual result**

- No mods are highlighted. 
- User has a sadface

<img width="1429" alt="screen shot 2017-11-30 at 12 12 30" src="https://user-images.githubusercontent.com/28071/33428066-c9566c9c-d5c7-11e7-812b-bdc2923e65c1.png">

**Comment by bhollis** [comment]
Yup, we don't have any extra information about mods (from the API). Try searching "Titan" which will match in their type description.

**Comment by 3rd-Eden** [comment]
This information could be parsed from the mod description.

**Comment by duckmanBR** [comment]
DIM is a multi language app...  Unless I'm mistaken parsing kanji/hangul/cyrillic and others is not exactly the same as parsing latin...

**Comment by 3rd-Eden** [comment]
Maintaining a list of ID's and mapping them to class's is also an option. There's enough ways to solve this imho.

**Comment by bhollis** [comment]
We've generally avoided hand-maintaining mappings to fill in missing data (with some exceptions) in favor of using the Bungie-provided database, because they change it fairly often with patches and expansions, and it can be a lot of work to keep up to date. If there's someone willing to carefully own that data and make sure to update it frequently, it can be OK.

**Comment by delphiactual** [comment]
This is now returned by the API
