### ISSUE TITLE
Locked Weapons getting deleted?

### ISSUE THREAD

**Issue by chrismo2001** [DestinyItemManager/DIM#2439]
So I think your app deleted my Uriel's Gift on PC. This was a locked gun, so I don't understand what happened. I have reproduce the issue for you that I saw. 

Now I don't keep track of all my weapons and their names so I may have lost more during the process.   

First, the way I use this app is to make room for the postmaster. It suppose to move guns to the vault, which is fine. 

The second portion of this app that I use is the delete duplicate weapons with "is:dupe"
 
Now here is the issue that I can replicate.

This past Tuesday I decided to clean out my vault with is:dupe. I only had one slot available in my Energy slot to transfer a weapon, I dragged the duplicate gun from your app (with my iPad FYI) from my vault to my titans slot. Then delete the gun in game. Without refreshing your app, I dragged another gun, it updated in app, then deleted it, I did the same to another gun and all of a sudden I have 2 slots open. What happened to the other gun that was there? where did it go? Then at that point I decided to refreshed your app and there were 2 slots open, not sure how that happened. 

I did the same to my power slot, and with the same steps. one open slot, drag a gun, delete in game, then drag another gun without refreshing, an extra slot was open. 

I assumed another gun was brought to the vault, since i didn't think the app will ever delete any of my guns, at this point I still had my Uriel's gift. Now, Last night when I played, I was grinding away and I had my Uriel's gift on me but not equipped. When I was making room in my vault for the postmaster, I think the app moved my gun. The only problem now is that.... I CAN'T FIND IT! It's stressing me out, I looked all over the place, my vault and character... IT'S GONE! I know for a fact that I locked it and I never in my 3 years of playing Destiny have I accidentally deleted a weapon. I checked my PS4 and I still have the gun there, as I'm working to have a similar loadout for the nightfall on PC. Now I look at my vault and it looks thin. I think your app may be deleting weapons by mistake and I here to raise this concern. Can you please look into this to see if your app is deleting weapons by mistake based on the steps I provided? I hope it's in limbo and can be recovered without having to wait for it to drop again.

 Thank you.

**Comment by m-s-y** [comment]
You cannot delete ANYTHING via the API. You can only delete in-game, by design. DIM is not where you should be concentrating your investigative effort.

On Nov 30, 2017, at 5:40 PM, chrismo2001 <notifications@github.com<mailto:notifications@github.com>> wrote:


So I think your app deleted my Uriel's Gift on PC. This was a locked gun, so I don't understand what happened. I have reproduce the issue for you that I saw.

Now I don't keep track of all my weapons and their names so I may have lost more during the process.

First, the way I use this app is to make room for the postmaster. It suppose to move guns to the vault, which is fine.

The second portion of this app that I use is the delete duplicate weapons with "is:dupe"

Now here is the issue that I can replicate.

This past Tuesday I decided to clean out my vault with is:dupe. I only had one slot available in my Energy slot to transfer a weapon, I dragged the duplicate gun from your app (with my iPad FYI) from my vault to my titans slot. Then delete the gun in game. Without refreshing your app, I dragged another gun, it updated in app, then deleted it, I did the same to another gun and all of a sudden I have 2 slots open. What happened to the other gun that was there? where did it go? Then at that point I decided to refreshed your app and there were 2 slots open, not sure how that happened.

I did the same to my power slot, and with the same steps. one open slot, drag a gun, delete in game, then drag another gun without refreshing, an extra slot was open.

I assumed another gun was brought to the vault, since i didn't think the app will ever delete any of my guns, at this point I still had my Uriel's gift. Now, Last night when I played, I was grinding away and I had my Uriel's gift on me but not equipped. When I was making room in my vault for the postmaster, I think the app moved my gun. The only problem now is that.... I CAN'T FIND IT! It's stressing me out, I looked all over the place, my vault and character... IT'S GONE! I know for a fact that I locked it and I never in my 3 years of playing Destiny have I accidentally deleted a weapon. I checked my PS4 and I still have the gun there, as I'm working to have a similar loadout for the nightfall on PC. Now I look at my vault and it looks thin. I think your app may be deleting weapons by mistake and I here to raise this concern. Can you please look into this to see if your app is deleting weapons by mistake based on the steps I provided? I hope it's in limbo and can be recovered without having to wait for it to drop again.

Thank you.

**Comment by chrismo2001** [comment]
That's what I was hoping for, thanks for the quick response. I'll take this up with Bungie.

**Comment by bhollis** [comment]
I assume you tried to search for the gun across all characters using DIM’s search feature? 

-Ben
