### ISSUE TITLE
Please add a +5 icon for items with powermods.

### ISSUE THREAD

**Issue by Green-Bug** [DestinyItemManager/DIM#2457]
I know I can tag them via is:powermod but that is a manual process and it requires re-tagging when getting new items. Having an icon by default would help.

Thanks.

**Comment by taralx** [comment]
An option to display these items as "300+5" instead of "305" would work great for me.

**Comment by bhollis** [comment]
They have a gold border already 

-Ben

**Comment by Green-Bug** [comment]
That's right, they do. I've never noticed it... I'm not sure what to say, It might be a bit too discreet. A notice or hint in some place might help.

**Comment by kyleshay** [comment]
we're tight on space so we opted for the gold border. we've been considering an overall refresh to handle the crazy amount of data we try to put on the little ~50px icon.

I'll close this for now because we're sort of tracking that issue separately, and for now the gold border solves the issue in a roundabout way.
