### ISSUE TITLE
Feature Request: Move all to vault

### ISSUE THREAD

**Issue by h3adache** [DestinyItemManager/DIM#2468]
I like to move all my items to vault to help me see them sorted for dups and level easier.
Would be nice if there was a single button for this so it's easier/faster to do especially on mobile.
Thanks!

**Comment by duckmanBR** [comment]
You can't move "all" because you need to have something equipped on each slot (unless you never equipped anything there, as in a new char).
With that in mind you may achieve what you want with a ``is:equippable not:equipped`` search and on the vault menu select the magnifying glass row.  All the highlighted items will be transferred there.

**Comment by kyleshay** [comment]
> With that in mind you may achieve what you want with a is:equippable not:equipped search and on the vault menu select the magnifying glass row. All the highlighted items will be transferred there.

**Comment by h3adache** [comment]
Wow thank you! I had no idea that you could do that. That's exactly what I was looking for. Now if only it was easier to do on iphone haha

**Comment by h3adache** [comment]
@duckmanBR because I hate typing into tiny input prompts in mobile.
