### ISSUE TITLE
Changing Character Order on Mobile Breaks Swiping Characters

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2536]
I reversed my character order, and when I swipe, I get the wrong character.

**Comment by bhollis** [comment]
On the inventory or progress pages?

**Comment by duckmanBR** [comment]
@SunburnedGoose I'm getting a different kind of error when changing the char order, not when I swipe, but when you change character order, DIM stays on the same column (that's also happens on progress), and the content is refreshed.  The problem I'm getting is that in the inventory page only the characters title/selector/emblem is refreshed.  The content isn't.
So if I'm on my Warlock (third column) and change the order, the selector changes to my Hunter, but the weapons I'm seeing are the ones on my warlock.  If I swipe left I get all the info for the Titan...

**Comment by SunburnedGoose** [comment]
@bhollis Inventory, on phone.

**Comment by duckmanBR** [comment]
Tested more and got you error @SunburnedGoose ... But I it's related to the error I described above.

What's happening is that when you change the sort order, swipe and the char selector becomes disjointed...

The selector updates to show you on the same column as before (but in a new order, your prev/next tip of characters will change), but the swipe is updated with you new order, so you swipe left/right will bring you the position related where is your character on the new order.

Example:
H T **W** V <- this is my  _most recent character (reversed)_ order (**bold** is the current viewed column)
W H **T** V <- when I change to _character age_ 

If I swipe left nothing happens, and if I swipe right I go to the Hunter column, that's because Wizard is now the leftmost column.
But, if instead of swipe you tap on the left character "tip" on the selector, I'll be transferred to Hunter and on the right, to the Vault.

Better or worse?  A gif/movie of this would be better... :(

**Comment by bhollis** [comment]
Sounds pretty straightforward- I bet when we update the character sort setting we don’t recon pure `currentCharacter`.

**Comment by bhollis** [comment]
This’d also be solved if settings were their own page - it’d be nicer on mobile and we wouldn’t have to be as careful about watching on settings values.

**Comment by SunburnedGoose** [comment]
That's probably the best fix, moving settings to their own page.

**Comment by bhollis** [comment]
#2544 fixes this that way
