### ISSUE TITLE
Tooltip does not display for Karnstein Armlets

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#2586]
When clicking on Karnstein Armlets, the tooltip does not display. In the JS console, I get this error:

```
TypeError: Cannot read property 'includes' of null
    at d2-perkRater.js:83
    at underscore.js:227
    at Function.w.each.w.forEach (underscore.js:153)
    at Function.w.filter.w.select (underscore.js:226)
    at e.value (d2-perkRater.js:82)
    at e.value (d2-perkRater.js:65)
    at d2-perkRater.js:29
    at Function.w.map.w.collect (underscore.js:172)
    at d2-perkRater.js:28
    at Function.w.each.w.forEach (underscore.js:153) undefined
```

I get this error on Beta, but not on Prod.

It doesnt matter whether the item is equipped or not, I get the same error.

**Comment by joshhunt** [comment]
Looks like it's failing on review `5a5cda74c3632f679ba6b9dd` on that item due to it not containing `selectedPerks`.

**Comment by duckmanBR** [comment]
@48klocs should be the right person to help us
What puzzles me more is the "no error on prod" since we didn't change those files this year.  Unless is one of @bhollis changes indirectly affecting these.

Anyway, can't help directly because I don't have this item on me and can't turn the ps4 on until late at night.

**Comment by 48klocs** [comment]
Huh. Good find - I'll get to it this evening.

**Comment by duckmanBR** [comment]
@joshhunt are you using the same setting for rating platforms on prod/beta?  That may explain prod not returning a error...
