### ISSUE TITLE
Black Spindle missing from DIM

### ISSUE THREAD

**Issue by Randactyl** [DestinyItemManager/DIM#261]
You guys have probably heard of it, this gun is today's hype train.

I'm not sure what information you need in order to add items to the manifest (i guess), but let me know if I can get you something. The weapon is not listed in the Bungie Armory or Destiny Tracker's database.

**Comment by kyleshay** [comment]
hey! thanks for the report. since it's not showing in the bungie armory/companion app/etc, there isn't any way for us to grab the item either. 

@SunburnedGoose Do we still get an item instance id for these types of "classified items"? We could just give items without a definitions map a generic icon and make the text "Classified"? If we have the item instance id, it would still be technically possible to move the item, correct?

**Comment by Randactyl** [comment]
That's what I thought with it not being available :/

That's what the destiny companion app does, but I was having problems trying to vault the Black Spindle just now.

**Comment by SunburnedGoose** [comment]
We get the item id with an item hash, but there is no definition.  I'm adding code to DIM when items are found without definitions, we get a message through google analytics, and we can patch it.

**Comment by SunburnedGoose** [comment]
I'm going to get Touch of Malice and Black Spindle today I expect and will be able to test.

**Comment by kyleshay** [comment]
resolved in #264
