### ISSUE TITLE
Not working after Warmind update

### ISSUE THREAD

**Issue by MelonSquid** [DestinyItemManager/DIM#2798]
DIM isn't loading after the warmind update for me

**Comment by G4te-Keep3r** [comment]
same here

**Comment by s4nholo77** [comment]
same.  using chrome on linux mint

**Comment by nivshah** [comment]
Screenshot of JS console errors:

https://www.dropbox.com/s/zvh2wxt11ao1bst/Screenshot%202018-05-08%2014.33.17.png?dl=0

**Comment by duckmanBR** [comment]
The API Server took longer to be online. It should be working now.

**Comment by MelonSquid** [comment]
Not for me. Using Firefox on Windows

**Comment by dexTdoug** [comment]
Not for me. Using Chrome on Windows 10

**Comment by G4te-Keep3r** [comment]
win 7 chrome same error

**Comment by bhollis** [comment]
Still a Bungie API problem, not DIM. Probably taking them a while to roll out all the updated servers. Give it a while.

**Comment by s4nholo77** [comment]
logging in to each character worked for me

**Comment by armando1793** [comment]
logging into each character got the app working for me

**Comment by G4te-Keep3r** [comment]
Going into each character did fix it. There was a bug in the game a while back where some people were having too do that for in game bugs too.

When I go to collections, the stuff grayed out I haven't gotten yet. But a few things are light without a green checkmark. Also every weapon is listed twice. All this is on pc login, my ps4 bungie account has not been checked since I was grinding on pc today.
https://drive.google.com/file/d/10hOnPH2VJzU7WwlzZ9zMKJmSG8SiUhpY/view?usp=sharing

**Comment by bhollis** [comment]
I haven’t gotten a chance to play yet, but I believe the duplicates are for masterwork versions. Lit up without a checkmark means you’ve unlocked but dont have it in your inventory.
