### ISSUE TITLE
[Gather Duplicates] button on item details

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#2834]
I often find myself searching for duplicates of items that I just got a drop for. More often than not, I need to transfer the item locally to either dismantle the lower power item or infuse the new item into it (in the case of masterworks, mods, etc. on the lower powered item)

It would be nice to have a button that simply gathered any duplicates to the character where the item is currently being held.

**Comment by bhollis** [comment]
If you're searching for duplicates (using is:dupe or is:dupelower), just click the character menu and select "Transfer search".

If you want to infuse, use the infusion tool to select the item you want to infuse, and click "Transfer Items" and it'll bring the infusion fuel over.

We could add a dedicated button but we're kind of running out of space for those...

**Comment by Wh1rledPeas** [comment]
Yes. I use is:dupe. It's just clunky since I'm on a phone. Swiping back and forth and scrolling to find the items. I suspect it's a lot simpler on a tablet or PC, but I'm in a power chair full time with a phone mounted on the end of the arm rest. Mounting a tablet there would be too obtuse unfortunately.

I'll tell you another option that would satisfy the same need... When clicking the little double-square icon to see other versions of the same item, make the other items tappable. So you can bring up that item by tapping on the picture. Then just transfer the item using the controls that already exist.

**Comment by bhollis** [comment]
Thanks, those are good suggestions! Hopefully soon we’ll be able to do the changes we’ve been thinking about for search and the item popup that can make them a lot easier to use.

**Comment by javalasers** [comment]
This points toward the biggest remaining unsanded corner in DIM for me, also. Specifically, I struggle when a new expansion comes out and dupes start dropping at higher power levels than my existing equipment.

If the new item is indeed "better" (depends on masterwork and powermod), then I basically want the new item to "take the place of" the old everywhere:

1. Apply the "favorite" or "keep" tag if the old item had that tag.
2. Apply the "trash" tag to the old item (usually).
3. And most crucially **find any loadouts where the old item appeared and update those loadouts** to now include the new item instead.

DIM does a reasonable job at 1 and 2 today, but when I hit number 3 DIM adds a lot of friction to things. In particular, I'm sort of punished for creating many loadouts, because that forces a longer manual linear search through them, to see if I'm referencing the now-obsolete lower dupe anywhere. :-/

I had some momentary joy in discovering is:inloadout which could at least give me a binary yes/no as to whether the obsolete item was in ANY loadout, but the behavior seemed inconsistent there, and sure enough issue #2410 seems to imply that I shouldn't rely on that functionality today.

At a product/design level, I'm actually not sure how to best solve this problem. It's a kind of subtle notion that involves a _pair_ of items rather than a single one. The infusion finder has some notion of a pair of items that I'm dealing with, but this feels like a use-case that's somewhat distinct from infusion.

Anyway, just hoping that me laying out the particular workflow is helpful in honing in on user needs, whether you're able to come up with something to do here or not. Thanks so much for DIM, and in the meantime I can certainly muddle through even if it means keeping my loadout-creation tendencies in check. ;-)

**Comment by kyleshay** [comment]
Unfortunately until we decide to redesign the item details popup (real estate is already very limited.) this is the expected userflow as Ben described:
> If you're searching for duplicates (using is:dupe or is:dupelower), just click the character menu and select "Transfer search".
We'll revisit this ticket when we make those changes.

@javalasers it sounds like your issue is more related with how the loadouts feature works. Would you mind opening a seperate issue for that?

**Comment by javalasers** [comment]
@kyleshay thanks for the thought re: this being more of a loadouts issue (and I can certainly see that). However, with random rolls now in the picture, I'm not sure what I would even want any more. :-) So I'll hold off on opening a new issue for now...

**Comment by Wh1rledPeas** [comment]
<img src="https://user-images.githubusercontent.com/3685437/49311493-49d5c280-f4af-11e8-9471-a013b841ecc1.png" align="right" width="200" alt="screenshot_20181130-074056" />When using a phone device, swiping left/right/up/down to find duplicates is very tedious, so I have been using the [INFUSE] button now that you've grouped duplicate items at the top of the items available for infusion. This works very well now! 😊 I tap [INFUSE], select the duplicate and move it local. Not for infusion, but to compare them.



This has been working GREAT until I started getting MAXPOWER drops. The MAXPOWER duplicates only show up if the drop I got is less than MAXPOWER. Would it be unreasonable to ask that ALL duplicates are grouped at the top of the list, regardless of POWERLEVEL? That would seal the deal on needing a "gather duplicates" operation.
