### ISSUE TITLE
Infusion v3

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#289]
Some suggestions:

- [x] Dialog won't close when you click outside of it. Right now, you must click the X button
- [ ] Calculate "best upgrade path" (take checkboxes into account, eg. if show locked items are checked, include the locked items in the best upgrade path) [code here](https://www.reddit.com/r/DestinyTheGame/comments/3n6pox/python_infusion_calculator/) will calculate:       
* Best light with least marks
* Least marks with best light

**Comment by geck0s** [comment]
I found some ways to confuse the infusion calculator.  Select a higher stat item, then toggle the checkboxes and select a lower stat item and for example, it lets me input that I want to infuse my 279 hunter helm with a 288 titan helm and then a 285 hunter helm, bringing the gear to 285 with 6 marks.  

Also, I Ieft the window open after infusing the helm from 279 to 285 and now when I toggle the checkboxes it puts the 285 version as a candidate to infuse with itself.  Apparently it has refreshed some of the data in the background even though I didn't click refresh yet.

Of course the game wouldn't let you do any of these crazy things and if you don't do silly things you won't get silly outputs, but I think it could be improved so we reduce confusion when people toggle inputs.  I like that it keeps your current choices open instead of discarding them when you toggle a checkbox.

I haven't looked at the code yet, but I'm guessing this could be fixed by passing the current expected result value into whatever filters out items that are too low to be infusion candidates.  It looks like it currently uses the starting item's value each time a checkbox toggles.

Finally, there is enough height on my screen to avoid having a scroll bar and hiding the text "This calculator uses the best known algorithm for infusing. If you find any discrepancies let us know."

Both issues are shown in this screenshot:
![demonstration of confused infusion calculator](http://i.imgur.com/3n2M6TR.png)

**Comment by geck0s** [comment]
Also, the title row stating "Infusion Calculator" includes the close button and can be scrolled out of view, perhaps with the mouse wheel.  This can lead to confusion on how to close the infusion dialog.  If there is a simple way to place that title and/or the close box above the scrolling portion, that would be preferable.

**Comment by geck0s** [comment]
Reddit user IMM91 reports that the infusion calculator suggests infusing year 1 items into his year 2 hothead rocket launcher because it was 150 attack and lower than them but the game won't allow that.  We may need to filter out all year 1 weapons in addition to the primary stat comparison.

https://www.reddit.com/r/DestinyTheGame/comments/3o48e2/infusion_data_collection_request/cvvx7p2


Reddit user jlmurph2 reports that a 305 exotic infused with a 310 exotic only came out as a 309.  
This matches another report on Apswny's sheet so we will have to wait until an improved formula is formulated.

https://www.reddit.com/r/DestinyTheGame/comments/3o48e2/infusion_data_collection_request/cvw00w6

**Comment by Mulchman** [comment]
I also had a 305 exotic, infused a 310 exotic into it, and was left with a
309 exotic. (The 310 also had every node unlocked but not upgraded.)

**Comment by cdacamar** [comment]
So I was just fiddling around with the idea of best infusion paths.

https://gist.github.com/cdacamar/5bd4fc10417e22d739e4

In this example I used a dynamic programming approach to do a simple depth first search on a list of weapons.  I feel like this could easily be adapted to the app.  Another thing is that this solution will be faster than just computing every permutation of the list since we won't have overlapping solutions using this approach.

**Comment by geck0s** [comment]
Can we also have the "Show infusable items across all characters and vault" checkbox check the postmaster on each character or maybe have another checkbox for that?

I'm sure most don't leave much armor at the postmaster, but it might be a nice addition for those of us who do.

**Comment by kyleshay** [comment]
Closing, as best upgrade path is being tracked by #305
