### ISSUE TITLE
iOS “Add to home screen” opens in Safari tab, not full screen

### ISSUE THREAD

**Issue by indirect** [DestinyItemManager/DIM#2917]
According to [this tweet](https://mobile.twitter.com/thisisdim/status/879153341145788416?lang=en), using “Add to home screen” will make DIM an “app like experience”.

However, adding both `app` and `beta` to my home screen produces an icon that simply opens a new tab in Safari. I just want to use DIM without a URL and tab bar. :sob:

![](http://files.arko.net/2u1O1C2Q0o1s/B524E455-D179-4380-8F1D-473028406841.jpeg)
![](http://files.arko.net/3Q1D3K3j3g2b/A0592305-91A9-4BF5-970D-D9394D578551.jpeg)

**Comment by bhollis** [comment]
Unfortunately iOS Safari can’t quite do that yet. While we could put you into a screen that has no URL and navigation bar, you’d never be able to log in because the login redirect won’t work. We have some ideas long term on how to fix this, or Apple can fix their experience (similar to how Android Chrome works)
