### ISSUE TITLE
''Gather Reputation Items" doesn't transfer all items to vault

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#2932]
''Gather Reputation Items" doesn't transfer all items to vault. Since about a week or so ago, it transfers some times, and displays the "your loadout of n items was successfully transferred", but i'll still have tokens or Gunsmith materials left on my character. I get the problem on both beta and prod.

Here's a video of it in action https://gfycat.com/SecondhandLoneLadybird  
Note how I transfer an item first to clear the B.net cache and ensure that the inventory showing in DIM is up to date and accurate.

@duckmanBR said on Discord:

> Yeah, the problem is when you have split stacks (even if one of the sides is at max).  

I'm not sure I entirely understand this, but I've had multiple stacks of Gunsmith Mats for a while now and this bug didn't happen back then.

**Comment by duckmanBR** [comment]
Looks like the root of the problem is when you have split stacks of items.
@bhollis recently changed how we handle items with amount, so it may be that (can't debug it right now). 

Example: You have 10 EDZ Tokens, split 5 on the "common bucket" and the other 5 on vault.  
"Gather Reputation Items" or a "Transfer `is:consumables EDZ`" on vault won't transfer them, but will transfer every item that that you only had on your common bucket.

But if you click on the item and do a tranfer/take it works, so it's probably something on how DIM handles the transfer search (the gather reputation is basically a transfer search).

**Comment by bhollis** [comment]
Thanks for digging in, I bet you’re right. I’ll take a look tonight, I’ve been away for a while.
