### ISSUE TITLE
item ratings don't appear after changing some settings?

### ISSUE THREAD

**Issue by oguzka301** [DestinyItemManager/DIM#2971]
i changed some settings, but turned some of them back again,
the item ratings shouldnt actually be affected by my changes, but somehow they are.
heres a picture of my weapons without any ratings. ( same to armor sets as well)
![image](https://user-images.githubusercontent.com/42637915/44514926-91370080-a6c1-11e8-8402-2206fc71a9e0.png)
heres a picture of my settings:
![Uploading image.png…]()

**Comment by bhollis** [comment]
Can you try uploading your settings screenshot again?

**Comment by oguzka301** [comment]
![image](https://user-images.githubusercontent.com/42637915/44531015-07eaf280-a6f0-11e8-9bcf-4f06b6cc9a1b.png)

**Comment by oguzka301** [comment]
thats exactly what i did, i event changes from show all to playstation only.
or from pve to pvp and stuff like that,
when i go to a single item, and check on show preview,
it says, that no one has given a ranking yet for this item, and i should be the first one to do tho.

**Comment by patchm00** [comment]
I'm seeing the exact same thing

**Comment by patchm00** [comment]
By the way, even though the item preview shows the green 96% etc, in DIM itself it just has the power level just like the weapons

**Comment by patchm00** [comment]
Also i see this on destinytracker: We are detecting issues w/ the D2 Bungie api. We could not update your stats. Please try again.

**Comment by 48klocs** [comment]
Would it be possible to get more detail on this? Testing locally (also on Chrome 64 bit), I'm seeing reviews be pulled.

The API we talk to has intermittent downtime; can you still reproduce this?

It was mentioned that an item has no reviews; we archived ratings+reviews recently, so I'd expect a number of items to not have any reviews. Do you have an example of one that you know that has reviews that's claiming otherwise?

**Comment by patchm00** [comment]
I think it was api being down because it started working again

Thanks

On Sep 1, 2018, at 9:54 AM, Dave <notifications@github.com<mailto:notifications@github.com>> wrote:


Would it be possible to get more detail on this? Testing locally (also on Chrome 64 bit), I'm seeing reviews be pulled.

The API we talk to has intermittent downtime; can you still reproduce this?

It was mentioned that an item has no reviews; we archived ratings+reviews recently, so I'd expect a number of items to not have any reviews. Do you have an example of one that you know that has reviews that's claiming otherwise?
