### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2996]
How should we display Collections data in DIM?

**Comment by philkernick** [comment]
So we aren't duplicating DestinySets, if would be good if it could somehow reflect the way it appears in game.

**Comment by philkernick** [comment]
I’ve had more of a thought about this, and it doesn’t seem necessary to duplicate destinysets. 

What if the DIM collections just showed you what you don’t have - the things still to chase.

**Comment by inexorableAce** [comment]
yeah since there is no way to pull from collections at the moment via API, this is cool opportunity to make something to review your collections while away from the game. Which is a cool interface in game, I second replicating in game UI to a point. I wouldn't paginate that sections once you get in, and obviously need to make some considerations for scaling and mobile and such. I'll see If I can mock something up this afternoon :)

**Comment by bhollis** [comment]
Awesome! I have got the collections rendering out the whole tree but I kinda lost steam on styling and interaction design. I did make sure search would be possible.

**Comment by inexorableAce** [comment]
https://codepen.io/inexorableAce/full/oPRVJg/ quick mockup of page layout without. media query to scale it down. bhollis had mentioned the companion app, so this takes the in game layout (allowing for larger screens) and then when it gets too small, it switches to icons like the companion app has. You can scale the window to see that change. clicking in could either display the items below the base categories Like the preloaded on or remove the categories and use the space for the items with a back to categories button.

So essentially you get the in game UI  but without all the pagination clicking in / out. I'm still working on the interaction part so added a pre-loaded section with items to show what might look like.

**Comment by ckhicks** [comment]
Love this.
