### ISSUE TITLE
Any interest in porting to ReactJS?

### ISSUE THREAD

**Issue by framerate** [DestinyItemManager/DIM#306]
I'm wondering if the slowdown we see as the app gets more mature is due to UI re-writes. We could rewrite it in ReactJS and take advantage of the shadow DOM to speed it up! 

Not sure if the authors have familiarity but if so, I'd love to help set up a project using reactJS and ECMA2015 in the future for this project if so inclined to go in that direction.

**Comment by jflayhart** [comment]
I have casually brought this up myself and the leader of this outfit seems pretty happy with Angular. I respectfully agree with continuing development in Angular, since we have come this far with it; although, I am using React + Flux at work, so I am always up for applying it somehwere :) So... as of now we are sticking with Angular unless @SunburnedGoose says otherwise

**Comment by framerate** [comment]
@jflayhart Do you know if the "business logic" is abstracted well from the UI layer? if so, I imagine we could make a prototype version using react pretty quickly. `Root` component, `Section` component and `Icon` component could be testable, I imagine?

**Comment by SunburnedGoose** [comment]
It is an Angular app inside/out. I don't have any issues with React but
there is no need for a rewrite. Feel free to try it out. Who knows... I'm
always live to see different perspectives.

This is just a quick post from my phone. I'm always happy to talk shop and
listen.

**Comment by lukefx** [comment]
@framerate the business logic is very tied to Angular right now. It would be nice to have some socre services that are extractable and reusable in other applications.
For sluggishness in general I'm trying out some sort of caching everywhere, like for images https://github.com/lukefx/DIM/commit/d2b42aec151b8744279489ed34514ddf6e48b62c I'd like to heavily collaborate on this because...it's super fun :smile:

**Comment by kyleshay** [comment]
out of scope for now, by all means feel free to experiment. though, do check out the `perf` branch. @SunburnedGoose has made some great enhancements.
