### ISSUE TITLE
Sliding to other characters not showing inventory after loading up - Galaxy S6 Edge

### ISSUE THREAD

**Issue by JonnyRekts** [DestinyItemManager/DIM#3135]
When viewing my first character then sliding across to the others the inventory doesnt load on either of the other two charcters. Can solve by exiting and loading back up. Looks like it could be an initial loading issue. 

![screenshot_20180926-083558](https://user-images.githubusercontent.com/43600453/46064712-0fc30a00-c168-11e8-81fb-a625abedd682.png)

**Comment by redtwotwo** [comment]
I have had this problem for a while. Now it seems that the mobile window is larger than the screen, the search is way off to the right and can not be seen.

Google Pixel (original) Android 9.0
![screenshot sep 26 2018 20_47_40](https://user-images.githubusercontent.com/33066550/46117129-8cd49a80-c1cd-11e8-9d49-259bb4ec3b13.png)

**Comment by KiCH75** [comment]
I have the same issue as Jonny but on a "random" noname phone. It worked until 1-2 days ago. Since then I can't slide between my characters, sliding animation stops between two characters, items don't appear under character switched to, I tried clean phone storage, reinstalling app, no change. Still works flawlessy on PC.

**Comment by bhollis** [comment]
Pushing a fix to beta, can you take a look?

**Comment by KiCH75** [comment]
Beta seems to work for me, shows the well-known behavior without glitches. Thank you for the fix!

**Comment by SunburnedGoose** [comment]
Fixed on S8.
