### ISSUE TITLE
Loadout Builder tier picker

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3162]
Picking items and perks is great, but being able to maximize your Mobility/Recovery/Resilience to your play style can be really useful.

- [ ] [tier picker](https://github.com/DestinyItemManager/DIM/issues/2292#issuecomment-336530451)
- [ ] compute more tiers by splitting out base and bonus for perks
- [ ] Include suggestions on what mods to buy and apply to hit desired tier
- [ ] Exclude/include custom applied mods/masterwork option

**Comment by inexorableAce** [comment]
lots of feedback from the discord on loadout builder recently. General consensus so far is that perk selection outweighs tiers. It's confusing to people when they lock perks but receive loadouts without those locked perks. As an example if I lock both shotgun targeting and shotgun reserves perks on my helmet I get results that do not include both shotgun targeting and shotgun reserves. I'd expect to see nothing if my gear can't make that happen, and even better if we can tell the user why we aren't showing anything because often times it's because they are selecting two perks within the same slot. 

we also had some confusion on the drag to lock, users where trying to drag items to the loadout below to lock them, perhaps some hover event that lights up the appropriate drag location when a drag starts.

**Comment by kain243** [comment]
To some players including me, locking perks is going to be more important than the tier picker. It seems right now the tier picker takes priority over the perks you have selected.  It might be a nice feature to let players ignore the tier picker and choose gear in their loadout only based on the perks they have locked. Someitmes currently even when i've locked a perk, the loadout builder will not choose a piece of gear with that perk if it doesn't have a stat that the tier picker wants.

**Comment by kyleshay** [comment]
closing in favor of #3260
