### ISSUE TITLE
CONTRIBUTING.md Missing Instructions for OpenSSL

### ISSUE THREAD

**Issue by cbcrouse** [DestinyItemManager/DIM#3172]
Hello!

I am not sure if I missed it somewhere, but I did not see any instructions explaining the requirements for OpenSSL. When I was going through the [Install Pre-requisites](https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md#pre-requisites) section on my **Windows 10 system**, all was well until I ran `yarn start`. I received the following error:

Error Message: `'openssl' is not recognized as an internal or external command`

You can see more detail in the screenshot below.

![yarn_start_error_openssl](https://user-images.githubusercontent.com/6248703/46517762-a6a55b80-c825-11e8-9d81-7cc507233c82.png)

Turns out that I did not have OpenSSL installed on this machine...

What I did to resolve my issue:
1. Downloaded the binaries from [here](https://slproweb.com/products/Win32OpenSSL.html) - **Win64 OpenSSL v1.1.1 EXE**
2. Installed Win64OpenSSL-1_1_1.exe to `C:\Program Files\OpenSSL-Win64`
3. Opened CMD as Administrator
4. Ran the command: `"C:\Program Files\OpenSSL-Win64\bin\openssl.exe"`
5. Ran the command that failed during **yarn start**: `req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem -subj '/CN=www.mydom.com/O=My Company Name LTD./C=US'` - (not sure if this command is different per user)
6. Ran `yarn start`

See successful example below:

![yarn_start_error_fix](https://user-images.githubusercontent.com/6248703/46518067-57602a80-c827-11e8-86e8-74b7e9cf9f49.png)

I hope this information was helpful and not redundant. I am new to open source and appreciate the documentation that is available to help me get started very much!

**Comment by glyphstalker** [comment]
Just wanted to let you know you are not alone.  I ran into this exact issue.

I 'solved' this a slightly different way:

1. I opened a powershell prompt in **C:\Program Files\Git\usr\bin** (since Git comes with OpenSSL.exe)
2. Ran the command: `openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem -subj '/CN=www.mydom.com/O=My Company Name LTD./C=US'` (literally copied and pasted from webpack.js into my powershell prompt)
3. Moved the generated **key.pem** and **cert.pem** files into the \DIM project folder
4. Ran `yarn start`

Just figured I would add this for anyone not wanting to 'install' OpenSSL for just one thing (especially since you either have to compile your own or trust a third party to get it).

**Comment by bhollis** [comment]
This is great info! We’ll get the readme updated.

**Comment by 48klocs** [comment]
My copy of Git for Windows came with OpenSSL and with it added to the environment path, which is why I didn't run into any of these pain points.

I peeked and there doesn't seem to be a node package we can globally install to add OpenSSL, unfortunately.

**Comment by cbcrouse** [comment]
@glyphstalker and @48klocs, thanks for your input! I didn't actually think to look there and none of the forums discussing 'how to install' it mentioned that either. After checking, it turns out that I did, in fact, have `openssl.exe` in that same git\usr location. From that, I think the issue then ultimately is that my windows Path didn't know about it.

Cheers!
Casey
