### ISSUE TITLE
First perk selected in Loadout Builder

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#3181]
https://twitter.com/efishkin/status/1048699426082967552?s=21

@ThisIsDIM I'm having trouble with the loadout builder (beta,I appreciate it :)), when I select two perks under gauntlet, the builder only looks for the first, is this as intended?

**Comment by kyleshay** [comment]
It is working correctly (pick two perks that are on the same item and it will come to the top.) 

It may appear that it is not working because we currently limit the number of results to 10. We could add a `v show more` button at the bottom to load additional sets, which would unveil the items that match more sets. 

The reason we block some is because showing all at once could hang the UI as thousands of sets may be generated.
