### ISSUE TITLE
Intermittently when loading PS4 account view the PC account character info is also displayed

### ISSUE THREAD

**Issue by suttungur** [DestinyItemManager/DIM#3211]
Two Destiny 2 accounts, one on PS4 (used for DIM Bungie.net authorization) and a PC account (linked to PS4 acct on Bungie.net). Both accounts have the same name (suttungur).
Occasionally, when the PS4 account details are initially loaded, refreshed or switched to, the PC character info is also displayed in the same view.
Does not happen with the PC view.
Please see the attached screenshot for the issue.
![dim_ps4_pc_bug](https://user-images.githubusercontent.com/44109217/46902168-4fcb0200-ce75-11e8-982f-2e76eb2355f6.JPG)

**Comment by bhollis** [comment]
We suspect this is a Bungie.net issue. Let me see if I can add enough debug logging so we can give Bungie the right info to debug this.

**Comment by bhollis** [comment]
Just an update, I haven't caught this happening on Beta yet (we only have debug logging on Beta). Any chance you can try to get it to happen on Beta?

**Comment by suttungur** [comment]
Using Beta now. Will update if issue reproduces.

**Comment by suttungur** [comment]
I haven't been able to reproduce the issue while using the Beta.

**Comment by kyleshay** [comment]
Thanks for the report. Please re-open if it occurs again!

**Comment by vthornheart-bng** [comment]
Turns out the source of this happening requires some specific repro steps.  You have to be using Fireteam features on bungie.net, and within the next 60 seconds or so access a feature on a 3rd party app (such as DIM).

This is entirely a bug on our side - an error in Fireteams that allowed your cached user data to be improperly overwritten with your other linked accounts' data - and it will be fixed more permanently as of 12/11!
