### ISSUE TITLE
Unable to Mass Lock/Tag via filtered results

### ISSUE THREAD

**Issue by K-Davis1** [DestinyItemManager/DIM#3241]
In the 4.74.0 release, the following feature was added:

> Lock and unlock items matching your current search from the same menu you use for tagging them

However, filtering items by, let's say, `tag:infuse` and then selecting `unlock` from the tag icon in the search bar will show the user the following message:

> Unlocked 0 Items

Even when there are locked items matching the search result.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/eNTCI.gif

As shown in the above, the search result of `tag:infuse is:locked` would no longer have matched the **is:locked** portion if the unlock update went through, but they remained locked.

**Comment by duckmanBR** [comment]
Trying to reproduce this I also discovered that tagging is also not working, so none of the "mass" options are working.  And tagging doesn't show the info popup...

I'm on mobile, so can't check console for error messages.

**Comment by duckmanBR** [comment]
So looking a little further, looks like the problem is that the combo selection is not properly triggering a refresh.
For the tag, I need to manually refresh (or jus be luck for DIM auto refresh) to see the changes.
For the lock, it's taking a little longer (maybe some delay on Bungie side since lock is trough API while tag is 100% DIM?), but 1-2 manual refreshes are needed for the items reflect the (un)lock action.

**Comment by bhollis** [comment]
Yeah lock state isn’t modeled separately in the Redux store yet so we need to force a store update after locking/unlocking.
