### ISSUE TITLE
Loadout Builder layout depends on whether mods are applied

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3287]
If a class item does not have a mod, the equip button is a single line.  This looks like how it was intended to be.

However if the class item has a mod, the equip button is now two lines.

![image](https://user-images.githubusercontent.com/25425159/48112702-9874b000-e2a7-11e8-90d1-607728c2a240.png)

**Comment by kyleshay** [comment]
Ah, I think it is happening because the button is slightly less wide so the button string wraps to a new line. I've had some trouble figuring out where to place the buttons. @inexorableAce now that the Loadout Builder is a little further a long, would you happen to have any thoughts? I've tried putting the buttons on the same line as the light level / stats info, but floated to the right. Maybe that works best.

**Comment by kyleshay** [comment]
#3288
