### ISSUE TITLE
More info for ranks

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3294]
Posted in discord
![drlgzqcu8aesk_z](https://user-images.githubusercontent.com/4798491/48295371-88e09d00-e448-11e8-8e4c-4559bf4e35aa.png)

My idea to achieve this without a wall of text would be to make another circle, around progress through current rank that shows progress towards reset.

//cc @bhollis @inexorableAce

**Comment by inexorableAce** [comment]
we should do that thing justrealmilk had a concept for a while back, or some variation. probably should add the current number your at. but otherwise its a great way to visualize where you are on the road to legend. 
![image](https://user-images.githubusercontent.com/29002828/48295978-6b6afd80-e45f-11e8-9d1c-5fcb90b00756.png)
