### ISSUE TITLE
Allow a user to create a set of items to be transferred from their current character to their vault on a regular basis

### ISSUE THREAD

**Issue by TheHandsomeCoder** [DestinyItemManager/DIM#330]
Things such as strange coins, spinmetal, passage coins etc. Could perhaps be tied into the auto-refresh or have it's own timer

**Comment by cdacamar** [comment]
I really like this idea.  It lets you treat your vault like a bank for those items, however, whenever you actually want to use those items and allowing DIM to automatically pull them away from you in its 'Gather' operation it could get frustrating.

A compromise might be to simply make it a button called 'Gather' which would pull the specified list of items from all your characters into the vault.  Even that has its problems because you could fill up your "General" section very fast.

The way I use my vault is I have a stack of 200 of each planetary material, a few stacks of heavy synth and a bunch of telemetries.  So if the 'Gather' operation could set an upper limit on each item, for example: `transfer spinmetal until 200 in vault` that would be awesome.

**Comment by TheHandsomeCoder** [comment]
Yeah it would need to be quick to turn off, but I think it would be a nice option for some players. I for one would use it exclusively for the instant glimmer consumables such as house banners, network keys  etc.

**Comment by geck0s** [comment]
This is something I would really like as well.  

How about a gather checkbox to make it easy to enable and temporarily disable?

Maybe we can set it up so that you specify a "preferred" amount of materials on each character.  If you set a preference for 150 spinmetal on each character, then the gather algorithm would distribute whatever spinmetal you have equally among the characters and if there is more than 450, it puts the excess in the vault.  If you specify zero house banners then it moves all house banners into the vault when it sees them.  Uncheck the checkbox when you want to cash some out  manually.  Even better, input the desired number you want to sell and have this feature move exactly that many onto your character so you can visit the cryptarch and mash the button to turn in exactly as many as you want very quickly.  

Maybe have a checkbox to have it equally distrbute among all characters for things like ether seed or armor materials which stack past 200.

**Comment by bhollis** [comment]
See also #129.

**Comment by kyleshay** [comment]
we now have a farming mode, as well as bulk talk/gather/split for stackable items.

what do we want to do with this feature?

**Comment by TheHandsomeCoder** [comment]
Does farming mode work for things like mats or consumables?

On 9 May 2016 at 21:06, kyle shay <notifications@github.com> wrote:

> we now have a farming mode, as well as bulk talk/gather/split for
> stackable items.
>
> what do we want to do with this feature?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DestinyItemManager/DIM/issues/330#issuecomment-217973660>
>



-- 
- Scott

**Comment by kyleshay** [comment]
right now it's only engrams

**Comment by bhollis** [comment]
I'm not sure I see the value of moving mats and consumables - they stack,
so it's much harder to run out of space. Easier to just make some room
before going out.

**Comment by kyleshay** [comment]
that's what i was thinking. between that and the new "take all"/"split" features, should we close this issue? unless someone has any other thoughts?

**Comment by bhollis** [comment]
I'd vote close.

**Comment by cdacamar** [comment]
Just as a quick thing that could be done (possibly unrelated to the actual issue) is ctrl+click to select multiple stacks or items to transfer into one place.

**Comment by kyleshay** [comment]
good call, @cdacamar. I'm going to close this for now. If we have an idea on how we could make this work, I'd be happy to re-open it.

also remember loadouts can move materials now. you could make a loadout with 500+ strange coins, 500+ blackwax, 500+ etc and apply that loadout to a character to quickly cleanup.
