### ISSUE TITLE
Loadout Builder 2.0 requires a bit too much work to select a build

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#3320]
<img width="907" alt="screen shot 2018-11-13 at 9 36 26 pm" src="https://user-images.githubusercontent.com/313208/48462230-3f67b900-e78c-11e8-8fa2-d00afb6293dc.png">

I think I get the idea behind this filter, but I really liked the simplicity of the old loadout builder's single dropdown with all the different stat spreads on it. Having to select a bunch of different ranges is much more of a burden.

**Comment by inexorableAce** [comment]
We had one complaint about this in the discord as well, we could go back to the drop down as long as it’s defaulted to an option for ignoring the options... 

It is helpful to see what’s possible I guess.

**Comment by bhollis** [comment]
Maybe even a switch that lets you select what your preferred mix is - for example, that you’d prefer to emphasize Recovery. Otherwise the big list is a bit unweildy.

**Comment by inexorableAce** [comment]
Yeah I like that idea, just setting your preference is nice, would then also have to sort the results by that preference.

**Comment by kyleshay** [comment]
I feel like we should let users have full control if possible. When setting up a crucible loadout for example-
Some users may want to have exactly #X resilience to have enough hitpoints for some various 1:1 encounter (withstand number of headshots/grenade/etc.) and then use the rest of their points on Mobility/Recovery. 

If we just have an option to say "maximize recovery" then you may get a loadout with 8 or 9 resilience, when you would want to instead use those points elsewhere.

The idea with these filters is that they're optional. When you do nothing, it automatically sorts by Tier and then Power level. If you update the minimum of any stat, it will re-sort to make sure you're always getting the best. 

I have a branch open with the dropdown. It feels kinda clunky because there are so many options and it does the same thing, but I feel like it requires more clicking because you may want to compare between different tiers (whereas with the current version loads all tiers at once, so you can just scroll down to compare.)

<img width="1065" alt="screen shot 2018-11-28 at 2 20 52 pm" src="https://user-images.githubusercontent.com/424158/49186673-22012600-f31a-11e8-9adb-77f3c71b7ebd.png">

**Comment by inexorableAce** [comment]
In this same line someone in the discord pointed out that the stat filters bottom out at 1 but it’s possible to have 0 in a stat so they should bottom out at 0.

**Comment by 13DavidG** [comment]
I think it's good for people to have full control over all the options like that. I prefer this option over the previous version. What would make it easier like others said, is the option to select your preference between the 3 stats. You could have a list and select which one should be on top/mid/bottom and sort the results by preferences. That way, you don't need to worry about those numbers.
