### ISSUE TITLE
Add compare feature to search

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3369]
When using the search filter:

If the type of item being searched for only matches a single item type, or if the compare screen is open then:

Show the compare icon button in the search box, which on click will add all matching items to the compare screen.

**Comment by kyleshay** [comment]
another approach is to just add a new button to the compare view that says something like "add all matching items from search" 

we could also automatically apply a search filter that shows only the items that can be added to compare.

**Comment by DHager** [comment]
I would absolutely use a "compare currently filtered items" feature, even if it sometimes complained with: "Not all items fit the same archetype, please narrow your search."

**Comment by kyleshay** [comment]
#3518

**Comment by DHager** [comment]
@kyleshay As a PC user, I usually think of the main UI with filtering as how I "push" to the comparison-pullout-zone. I don't think of it in terms of "pulling" because there's enough screen-space that the comparison-lineup isn't blocking me from using my regular search-and-result workflow.

**Comment by DHager** [comment]
Any updates on this? 

Right now the annoying workflow involves:

1. Find item of correct archetype
2. Click comparison view
3. Manually remove every single item except one (since removing them all closes the view) by clicking repeatedly to "X" out the second-from-the-left slot.
4. Find the items I *actually* wanted to compare
5. Remove the original temporary item, assuming it isn't coincidentally one of the ones I want.
