### ISSUE TITLE
Don't error when picking an unequippable item from item picker

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#3592]
Just move it instead.

**Comment by Wh1rledPeas** [comment]
> Just move it instead.

I'm not sure if you have the ability to track metrics and have DIM report them back to you, but if so, you might want to track some metrics here and see if you're erroring more than not. The idea being, DIM should perform the action that causes less error+retry events. You could also track how many people use the equip vs. move option, to get an idea of which is more common.

For me personally, I have to move 95% of the time, so it's always a two-tap process.

**Comment by bhollis** [comment]
> I'm not sure if you have the ability to track metrics and have DIM report them back to you

I don't know of a good free platform for this. We use Google Analytics but are always very close to bumping over the free limit on events just for basic pageviews.

> The idea being, DIM should perform the action that causes less error+retry events.

Yes, obviously. That's what this issue is about.

**Comment by Wh1rledPeas** [comment]
> I don't know of a good free platform for this. We use Google Analytics but are always very close to bumping over the free limit on events just for basic pageviews.

I'm not sure what your server-side platform looks like, but if you're truly interested in collecting metrics/insights, perhaps the DIM client could store some summary/trend data (FIFO) internally and occasionally report that information back to your servers for storage in a database.

You could use a quick HEAD request as a server-side switch to only collect data from clients during a specific period where you want to look at metrics. That way, there wouldn't be a constant overhead caused by clients reporting their metrics. Sadly, you'd probably have to build in some sort of protection against malicious posts to the server though...

**Comment by bhollis** [comment]
DIM has no active server component. We just serve Javascript.
