### ISSUE TITLE
Loadout Optimizer: Select multiple perks from the perk sheet

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#3822]

**Comment by bhollis** [comment]
While I'm in there I'd like to either add tabs for categories or a nav-strip

**Comment by DHager** [comment]
Just saw the new UI and came here to give similar feedback: From a power-user perspective (i.e. I already know what all the perks do) -- this has been something of a downgrade. 

My prior workflow was often something like:

1. Lock all equipment 
2. Unlock the piece I know I want to switch
3. Pick two perks 
4. (Optional) Loop back to step-2 for another equipment-part
5. Review results, possibly tuning them by excluding gear that pops up but has an infuse/junk tag

Right now the main issue is step-3 takes a *lot* longer, because instead of jumping to a particular slot, I must *scroll* from the top, every single time. It also forgets the search-term I was using, so if I wanted to optimize multiple items for a purpose (e.g. "hand cannon") I need to re-enter that for every piece of equipment.

Suggestions:

1. **Preferred solution:** Do *not* hide or reset the state of the "Choose A Perk" menu after I have selected (or deselected) a perk. I almost *always* want to make more than one selection at a time, often two selections for every item I plan to switch around.
2. Lesser-workaround: Do *not* automatically erase the last-entered text in the "Choose A Perk" box.

**Comment by DHager** [comment]
Another pain-point I'm finding: The UI shows you when you're looking at an un-satisfiable perk combination by greying it out (good!) but unfortunately it also actively prevents you from picking the combination anyway. This is an annoyance because it forces the user to "backtrack" their selection even if they would rather just discard one of the earlier-picked perks.

In other words, you can't do this:

1. Look for and Pick Perk A1
2. Look for and pick Perk B1
3. Notice nothing has them *both*, and realize that B1 is actually more important
4. Unpick A1 and Pick A2 instead

**Comment by bhollis** [comment]
Thanks for the feedback. That’s what this task is suggesting, I just didn’t manage to get it done before the release.

**Comment by DHager** [comment]
Found another issue related to being unable to toggle "unsatisfiable" perks:

1. Pick perks for most of your equipment, unknowingly creating a set of possibilities that requires an exotic.
2. Try to pick the last set of perks for the exotic you *do* want -- and get prevented! Go back, puzzled.
3. See the earlier exotic among the list, and shift-click to blacklist it
4. Try to **un-**select the perks that mandated the blacklisted exotic -- and it prevents you from deselecting them.

**Comment by bhollis** [comment]
@DHager take a look at #3841.
