### ISSUE TITLE
Non-instanced objectives not included on items

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3910]
Legendary quests that have only one objective display correctly.

![image](https://user-images.githubusercontent.com/25425159/59548754-e9adf600-8f92-11e9-9740-ba0b72cd9fb1.png)

Legendary quests that have multiple objectives don't display any of them.

![image](https://user-images.githubusercontent.com/25425159/59548759-fcc0c600-8f92-11e9-82a0-d809a53bc8d5.png)

**Comment by sundevour** [comment]
this is not about the number of objectives, but the account-wideness of the new pinnacles

season 7 pinnacle quests live in
`characterInventories.data[character_id].items`
just like previous quests

but instead of being instanced,
their progress (identically formatted) can be found in either
`characterProgressions.data[character_id].uninstancedItemObjectives[quest_hash]`
or
`characterUninstancedItemComponents[character_id].objectives.data.[quest_hash].objectives`

**Comment by bhollis** [comment]
I had this right in the old progress page, but lost the logic when I switched back to DimItems. Should be pretty easy to re-incorporate that data.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/pull/3896/files#diff-ca1868a1c90550c10a94609efc95647bL560

**Comment by twistof8** [comment]
Same issue.  Looks great but would rather have the steps progress than the pretty. Glad to see your already working on it. Wish they would have waited to fix before updating the non-beta though.

**Comment by bhollis** [comment]
Just to be clear, I’m on vacation for a few weeks. So if somebody other than me wants to take a stab at it that’d be awesome. Otherwise I’ll fix it when I get back. 

DIM automatically releases from Beta every week.

**Comment by delphiactual** [comment]
Closed by #3927
