### ISSUE TITLE
Curated filter is a NOP

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3939]
Just noticed that there is an `is:curated` filter, but it doesn't return curated weapons.

Strangely there is also a `curated:` filter prefix, but this also doesn't do anything.

Neither are in the filter help.

![image](https://user-images.githubusercontent.com/25425159/60154383-51cbca00-9826-11e9-9ae4-b633ddbca0ba.png)

**Comment by bhollis** [comment]
Hmm, what version are you on? It is on the filter help, and it worked the last time I checked (I don’t have a wishlist loaded on my phone to check though)

**Comment by philkernick** [comment]
Current beta on Chrome on Windows 10.

**Comment by philkernick** [comment]
is:curated is on the filter help.  curated: as a filter prefix is not.

**Comment by duckmanBR** [comment]
is:curated is for the wishlist, not for Bungie _Curated Rolls_, as stated in the filter help: _Shows items that match your **wish list**_.

And the curated keyword makes no sense, but we indeed added that on #3348, maybe @48klocs had the intention of partial matches?

**Comment by 48klocs** [comment]
No, I didn't have any intention of checking for Bungie curated rolls with wish lists (although that would be a nice feature, if we can detect them).

The little backstory there is that I originally called the wish list feature "community curated rolls", and it took longer than I'd like to admit to realize that the original name was bad and confusing. Long enough that I had an `is:curated` search feature plumbed in.

I'll remove that soon, since it's not the first time someone's been (rightfully) confused by it.

**Comment by bhollis** [comment]
@48klocs looks like the actual question is about the curated range search, not the is:curated search. Not sure why that’s there.

**Comment by 48klocs** [comment]
Understood - I'll make a separate issue around yoinking the other one (which may or may not clear this one up).
