### ISSUE TITLE
add is:bungie for bungie curated rolls

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3948]
Continuation of #3941 

`is:bungie` might be able to be sourced from the API with a slight massage of data

curated rolls exists for a select few weapons, ~we can maintain this list by hand.~ 

[list](https://docs.google.com/spreadsheets/d/1_yqFd9lSUtH6k3MzuXodCDZKkwm7oj5Io0Craz08Q7k/edit#gid=619155124)

The curated roll is what is shown in `sockets.socketEntries[#].singleInitialItemHash`

We will need to ignore some of the other sockets such as shader, etc.
We do need to ensure masterworks are respected and short circuit if masterwork is not present (for rolls that have a masterwork specified)

Or even just a wishlist that is maintained separately specifically for these curated rolls.

https://gist.github.com/delphiactual/9a1fb840a116ff632c59a5a73962ecc3

**Comment by philkernick** [comment]
This is what is;curated should be, and since the old usage has gone away, there isn't any good reason not to use that name.

We can heuristically determine what a curated roll is, as they are exactly this definition:
1. Is a weapon
2. Is legendary
3. Masterwork level 10.
4. Every perk has exactly and only one option (ignore kill tracker).
