### ISSUE TITLE
Changing colorblind setting removes all UI

### ISSUE THREAD

**Issue by AwokenHive** [DestinyItemManager/DIM#4129]
I enabled protanopia mode, and everything disappeared. I can't get to settings to change it back. The menu bar briefly appears on refresh, but disappears after around a second so I can't do anything.

**Comment by sundevour** [comment]
hi, a couple things here:

#### i'd like to get you back up and running DIM
- if you're on APP.destinyitemmanager.com can you try BETA.destinyitemmanager.com or vice versa?
- if you were using google drive, it will carry over your settings/notes/tags/loadouts if you _immediately_ go to settings and set up google drive
- if you weren't using google drive and you made a backup, you can upload it
- if neither, you will not have your old info for now

#### i'd love your help making sure this doesn't happen again
- what browser are you using?
- it would be helpful to see more of what is causing your error, can you open your **console** and see what errors you can screenshot? try Ctrl+Shift+J (or Cmd+Shift+J on a Mac) or the F12 key

**Comment by AwokenHive** [comment]
Hi. 

The setting was changed on the app version, and synced to the beta version when I tried to use DIM there to fix it. 
I managed to get DIM working again by using a different PC that worked in the same browser (Firefox), and that setting change synced to my Google Drive, allowing me to use DIM on my main PC. 
Unfortunately, I didn't get a screenshot of my console before fixing this issue, since I wasnt expecting to be able to fix it myself. I believe I had my ad blocker off on the PC where the issue happened, and on where I could fix it, just in case that might help.

**Comment by sundevour** [comment]
cool, glad it's working for you!

**Comment by blakmarkit** [comment]
Same exact issue for me on both app and beta subdomains. Changing to any colorblindness mode in Firefox (69.0b9 (64-bit)), will blank out the page. Does not happen in Chrome. What is very strange is that the contents of the page are still there and interactable, but it's as if there is a solid layer sitting over the top of everything, obscuring it. If I mouse over something interactable, I can blind click on it to get the flyout info modal for gear items, and those appear correctly. There is clearly something going on with the filter/overlay specifically in Firefox. 

only things in console:
```
Content Security Policy: Interpreting https://none as a hostname, not a keyword. If you intended this to be a keyword, use ‘none’ (wrapped in single quotes).
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
```

The only thing that resolves the issue is to clear all cookies and site data, refresh, and reauthorize the app. That's less than ideal, as I am losing all of my settings and tags each time.
