### ISSUE TITLE
Feature Request: Add a tag like "Try"

### ISSUE THREAD

**Issue by LZRDLEG** [DestinyItemManager/DIM#4133]
I use the tagging constantly.  What about adding a tag or two.  I'll be running and gunning, get a drop and throw it in the vault.  Promptly forget about it.  Tag it tag:try and I know these weapons need to be tried before sharding/keeping.

**Comment by inexorableAce** [comment]
That’s what notes are for. Add a note, they are searchable without prefix as well.

**Comment by LZRDLEG** [comment]
True, and I do utilize those, but the shift + 1,2,3, or 4 is so much faster.  Just a thought.  I love it anyway, and if DIM is down, I normally just don’t play.

**Comment by Baglog** [comment]
Tags look like they are defined here(?):

src/app/inventory/dim-item-info.ts

Is that it? This seems like a trivial change to implement.

**Comment by inexorableAce** [comment]
You’re welcome to PR. It’s been discussed many times before. You’re welcome to search around and see the reasons it’s not been done in the past. Maybe this time will be different. Just be prepared to add more, and figure out some other design challenges that come with expanding tags instead of using notes.

**Comment by Baglog** [comment]
Sure I will look around. Sorry I should have RTFM first.
