### ISSUE TITLE
On some weapons, the perk popup does not contain the element type

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#426]
With certain weapons, the element type does not show up on the perk popup:
![example](http://i.imgur.com/PRJa4Ci.png)

Here's a weapon that does show the element type correctly in the popup:
![example](http://i.imgur.com/6WPIZcI.png)

**Comment by Mulchman** [comment]
And for completeness- here's a weapon that does show the element type correctly in the popup: ![example]([http://i.imgur.com/6WPIZcI.png)

**Comment by bhollis** [comment]
Interesting. Turns out that Qullim's Terminus simply doesn't have a visible damage perk. Doesn't show up on Bungie's site either! Looks like this is an issue with all the Oryx raid weapons - the "Will of Light" perk seems to have replaced the damage type perk. Basically a data issue on Bungie's side.

I don't want to get in the habit of patching up this sort of thing. We'll talk about the colorblind stuff, but I'm going to close this as a data issue.
