### ISSUE TITLE
Shadowkeep: Breakers

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4282]
https://github.com/Bungie-net/api/wiki/2.4.0-(Shadowkeep)-API-Changes#breaker-types

Show breaker type on weapon popup

**Comment by sundevour** [comment]
fyi this is fairly minor in importance because mods are completely transitory and aside from 1 exotic handcannon, breaker types are actually earned per-character.

so in most ways this marker just tells you whether the item has a breaker mod attached (a whopping 500 glimmer to switch on or remove). but it's not extremely meaningful because if you move it onto a character you haven't spec'd into that breaker variation and weapon type, it means nothing that the mod is attached.
