### ISSUE TITLE
Reforge/Twist of Fate Perk on Year 2 Armor Items in Vault

### ISSUE THREAD

**Issue by wein3967** [DestinyItemManager/DIM#431]
I've noticed that the Reforge/Twist of Fate perk has been showing up on all Year 2 armor pieces (e.g. artifact, ghost, chest) if they are in the Vault when you launch the DIM tab. The Reforge perk only goes away if you move the item to a character and hard refresh/reopen DIM.
![artifact reforge](https://cloud.githubusercontent.com/assets/11590326/13506105/fdf9d9ba-e141-11e5-9ead-080c296fd334.png)

**Comment by bhollis** [comment]
That's interesting. I wonder if that's an artifact of how Bungie represents the perk.

**Comment by bhollis** [comment]
Yup, this is a bug with the data Bungie sends back. Twist Fate is `hidden: true` when it's on a character, but `hidden: false` when it's in the the vault. It requires a refresh after move because that's when we rebuild our data from Bungie's response. I don't think we're going to be able to fix this in any nice way, so I'm going to leave it as a minor annoyance.
