### ISSUE TITLE
Only Valor Rank breadcrumbs are showing

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4311]
In the Ranks section of the Progress page, the 5 dots showing progression for Valor/Glory/Infamy only work for Valor.  The other two are always blank.

![image](https://user-images.githubusercontent.com/25425159/65828250-e76c6f00-e2d7-11e9-8a48-6a138b5e73b6.png)

**Comment by sundevour** [comment]
app or beta? does it look different on the other?

![image](https://user-images.githubusercontent.com/31990469/65828774-64093a00-e253-11e9-9fbd-fd160e3881c1.png)
i've got an infamy rank that is showing up, so it's not completely always missing, but it's not loading in app right now so that's a little weird. i will poke at it more.

**Comment by sundevour** [comment]
actually now they are both showing fine

there's some kind of extremely strong throttling going on lately, is it possible at all that your numbers are just lagging behind? i've had such a problem breaking the cached responses in the last week or two

**Comment by philkernick** [comment]
Beta

**Comment by inexorableAce** [comment]
Just to make sure we don't have wires crossed, the 5 boxes aren't showing progression, they are showing win streak if you have one. Just want to make sure we are on the same page as your original message seems like we may not be.

**Comment by philkernick** [comment]
This is my embarrassed face.  I had no idea that was a win streak indicator.
