### ISSUE TITLE
Update is:arc/solar/void search for Armor 2.0

### ISSUE THREAD

**Issue by phillipspc** [DestinyItemManager/DIM#4459]
Currently this search only works with non 2.0 armor
I can take a stab at it, but mostly wanted to open the issue to make sure it wasn't already being addressed.

**Comment by sundevour** [comment]
these are purposely excluded from being assigned as arc/solar/void because the armor energy is
• mostly an arbitrary value not directly related to the elements' arcishness solarness and voidness, except in the case of 2 mods per element. for the most part they could be named Energy Dog, Energy Cat, Energy Bird, and the attunements would make about as much sense
• api docs note these may not always be the categories of armor energy
• type "arc" and you'll see the filter for this

i'm open to being told i'm wrong

**Comment by phillipspc** [comment]
Ah, was unaware of the `energycapacity:arc` search option. 
I dont know... my personal opinion, despite the elements really having no tie to that element anymore gameplay wise, I think most people would expect `is:arc` to work. In every other usage, that search corresponds with the elemental icon on an item, so its a bit odd it doesn't here. Thats my 2 cents, but I'll leave it up to the core team to decide whats best.

**Comment by jerrycarlson** [comment]
I have found that to search for any particular armor 2.0 element, you have to enter a *negative* element filter in addition to the is:armor2.0 filter: "-solar" will show only solar 2.0 armor, "-arc" will show only arc 2.0 armor, and "-void" will show only void 2.0 armor.

I'm using the latest DIM and 64-bit Google Chrome browser.

**Comment by johyphenel** [comment]
+1 that I expected `is:arc` to find arc armor2.0 gear.

**Comment by sundevour** [comment]
fixed
