### ISSUE TITLE
Beta sometimes prompts for updates continuously

### ISSUE THREAD

**Issue by lorddax** [DestinyItemManager/DIM#4540]
Thought was cache issue, cleared and was able to reauth with Bungie and get newest version. Turning Google Drive integration back on keeps triggering update request as app reverts or something based on saved data 
Loading my Drive data caused about page to revert - 
DIM (Destiny Item Manager)
Version 5.50.1.5356 (beta), built on 10/20/2019, 11:53:18 PM

**Comment by bhollis** [comment]
Sorry, could you provide more info? What do you mean by "keeps triggering update request"?

**Comment by sundevour** [comment]
common behavior for me with no google drive integration. extremely stubborn caching i assume.

**Comment by bhollis** [comment]
You mean like the "Update DIM" indicator? On beta? On what browser?

This definitely doesn't have anything to do with GDrive. My hypothesis is that some mobile browsers refuse to update a service worker more often than every X hours for some reason.

**Comment by duckmanBR** [comment]
I'm getting this on Chrome Windows and Chrome Android, so it's not restricted to mobile, maybe to Chrome?

**Comment by lorddax** [comment]
I was getting it with Safari on iPad as well. I would be fine with a full
cache clear, but each time I resynced with drive I would get the Update DIM
notices. I can attach screenshots in a bit

**Comment by delphiactual** [comment]
When I have noticed this happening, when you press `Update DIM` instead of loading the actual update it loads an older version that is hard cached by the browser and SW

**Comment by bhollis** [comment]
This ended up being a caching problem caused by going to the new hash-less URLs. Those were getting cached by CloudFlare, and the cache key wasn’t `index.html`, it was `/4611686018433092312/d2/inventory`. The service worker just has `index.html`. So the service worker had the right version but CloudFlare was returning a day-old version. I’d set things up so deployments purged index.html from the cache… but not all the rest.

Now the service worker will serve `index.html` for all navigation requests, and I've set HTML to not be cached as aggressively.
