### ISSUE TITLE
Masquerader's Hood appears as a result for all maxbasestatvalue queries

### ISSUE THREAD

**Issue by irons** [DestinyItemManager/DIM#4657]
`maxbasestatvalue:discipline` highlights this item for me, despite a discipline of 2. It appears as a result in maxbasestatvalue queries for me for all six stats.

Masquerader's Hood does have a base strength stat of 22, which is higher than any of my other hats, but `maxbasestatvalue:strength` highlights both it and a Notorious Collector Hood, whose strength stat is 18. So the glitch goes both ways.

**Comment by delphiactual** [comment]
this is because of https://github.com/Bungie-net/api/issues/1126

**Comment by sundevour** [comment]
this is because the max formula checks per armor item (helmet, arms, legs, etc)
and, well,
![image](https://user-images.githubusercontent.com/31990469/68097959-cebf1e00-fe6e-11e9-8f22-ed2cf5082730.png)
![image](https://user-images.githubusercontent.com/31990469/68097971-dbdc0d00-fe6e-11e9-8415-188d65bec570.png)

i will see if these can be further distinguished, but not a huge priority

**Comment by bhollis** [comment]
@sundevour if you use `type` instead of `typeName` it might work.
