### ISSUE TITLE
Loadout Optimizer ignore stat not working as expected

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4725]
There was a ton of discussion on the PR for ignoring stats on LO, so apologies if I missed something, however I cannot get it to work as I had expected it to:

![image](https://user-images.githubusercontent.com/313208/69016132-2de16000-0950-11ea-929a-9540e3d881df.png)

In this case I've ignored all stats except for Strength. I'd expect my builds to then be ordered by maximum Strength, but it's still ordered by Total Tier. When we'd talked about this originally, the idea was that ignored stats would not be counted as part of the total that is used as the primary sorting mechanism.

**Comment by ryan-rushton** [comment]
Yeah the functionality to ignore total tier was removed for a couple of reasons from memory. First using the heading to disable that stat sorting was not obvious which I agree with totally. Second we came to the agreement that being able to disable certain stats was the sufficient functionality to get the idea the user wanted, @inexorableAce might be able to elaborate that a little more on that as I believe they made the connection originally.

Since using the functionality the way it is I agree though that ignoring the total tier in sorting is desirable. I tend to find I am scrolling though 20ish builds until I get to something that I end up using. For example, on my hunter I have 15-20 tier 24 builds, all which have a rubbish combination or recovery and intellect (which are the stats I mainly care about). I end up scrolling through all of my tier 24 builds to get to the tier 23 ones and pick the 6th one down.

**Comment by ryan-rushton** [comment]
I am of the mind that we should add in a button or checkbox to disable it. I personally still like my original idea of adding a total tier to the dragable options as I enjoyed using it but I get why it would be confusing to people.

**Comment by ryan-rushton** [comment]
I didn't read that last sentence properly with my original comments. I think that just got lost with all the changes (not sure if intentionally or not). I'll put a fix up this afternoon that does that and displays the total for enabled stats, used for sorting, and with the actual total which I will put next to it in brackets).  Something like `T5 (T22)` with the bracketed part being opaque like the ignored stats.
