### ISSUE TITLE
Seals is missing from left navigation on Progress page

### ISSUE THREAD

**Issue by kramrm** [DestinyItemManager/DIM#4739]
Version observed: 5.57.0.5832

![image](https://user-images.githubusercontent.com/48371021/69385948-e3285680-0c75-11ea-9499-6592ea9e3363.png)

**Comment by kramrm** [comment]
Digging into https://github.com/DestinyItemManager/DIM/blob/master/src/app/progress/Progress.tsx#L279, it looks like Seals may be grouped in with the Triumphs section, but given it appears as a distinct section in the content section, it appears that it is missing from the menu on the left.

**Comment by bhollis** [comment]
Yeah, it's just part of Triumphs.

**Comment by sundevour** [comment]
i see no harm in making this consistent for now, so there's no exception that needs explaining.
they are separate, non-linked trees which don't accordion each other closed.

it's not a huge space concern because the links menu isn't on mobile,
and shouldn't matter long term if we re-organize progress/collections
