### ISSUE TITLE
Comparing archetypes is broken?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4812]
https://www.reddit.com/r/DestinyItemManager/comments/ec24fa/comparing_weapon_archetype_is_still_broken/

**Comment by imeredith** [comment]
This issue seems to be divided into at least 2 issues.

1. DIM is always using RPM to lookup stats that are not always RPM in lookup table

The intrinsic perk lookup data is being generated with draw times for bows, charge times for fusions etc https://github.com/DestinyItemManager/d2-additional-info/blob/master/generate-intrinsic-perk-compat-table.js#L26 but DIM is only indexing that table using RPMs https://github.com/DestinyItemManager/DIM/blob/master/src/app/compare/Compare.tsx#L468

I imagine the best fix would probably to have the lookup table include what statehash was used to generate the entry in the table.

2. Some Archetypes have the same RPMs

This issue seems harder to deal with. I assume that the reason that DIM needs to group intrinsic perks together is because of exotics having different intrinsic perks for the same RPM?

The obvious solution would be to create the lookup table not based on rpm, but instead just create a list of groupings for non-exotic intrinsic perks, and have each exotic that matches that RPM/drawtime/charge time go into each intrinsic category.

I will take a look at the first issue for now

**Comment by bhollis** [comment]
I'm actually a bit confused - I lost track of how we were grouping archetypes, since I thought we were using the intrinsic perk to group them. @delphiactual, @sundevour, can you weigh in on the latest strategy?

**Comment by delphiactual** [comment]
There is multiple problems with just using the intrinsic perk or rpm... I have a WIP PR that just needs one more thing that I cannot figure out how to map correctly...

https://github.com/DestinyItemManager/d2-additional-info/pull/76

**Comment by delphiactual** [comment]
It is based off of impact and rof to group intrinsic perks that are compatible with each other (see [shotguns](https://github.com/DestinyItemManager/d2-additional-info/pull/76/files#diff-66ebc5b47c85b6fd8f0f7a57683bfa07R44-R51)) as precision frame shotgun intrinsic perk has multiple hashes and they.

**Comment by delphiactual** [comment]
Just switch back to intrinsic only, I cannot figure out what the correct grouping is...

**Comment by radar3301** [comment]
same as https://github.com/DestinyItemManager/DIM/issues/4056

**Comment by bhollis** [comment]
Yeah we should use the intrinsic. I understand exotics are hard, but IMO comparing exotics with other stuff isn’t that interesting.

**Comment by sundevour** [comment]
okie doke i will swap in some of the older code
