### ISSUE TITLE
Export all of the users weapons/armor to csv

### ISSUE THREAD

**Issue by thesamprice** [DestinyItemManager/DIM#487]

**Comment by wein3967** [comment]
At the moment, you can use the Gist [here] (https://gist.github.com/wein3967/73430a38fdd4007577e1) to export all your Year 2 legendary and exotic armor. If you want Year 1 legendary and exotic armor as well, you can use this [one] (https://gist.github.com/wein3967/493d98184e5a13813494f696ba917c7e). You need have a DIM tab open, press F12 (on Windows), past the Gist code into the Console tab, and press enter. You can then copy and paste the resulting CSV string into your program of choice.

I'm planning on updating this in the next couple days to get all armor regardless of quality and vintage, and to include color (Chroma). Another user has modified my script for weapons, but I may make one as well based on interest. If you are familiar with coding, all you really need to do is update the filter to get weapons instead of armor.

**Comment by wein3967** [comment]
I just made an updated one going forward (handles all armor types). I'll be putting together a weapons one in the near future. You can find it [here](https://gist.github.com/wein3967/73430a38fdd4007577e1).

**Comment by bhollis** [comment]
If we were to add this to DIM proper, what would be a good place in the UI to put it. I was thinking maybe "Settings"?

**Comment by wein3967** [comment]
It is certainly more of a specific or power user type feature. I'd guess most users wouldn't be interested in it at all. So somewhere not on the main screen would be best; Settings could work. The features I'd like to see, but haven't added yet is returning the unboosted and boosted stat values and the armor quality (% like kyleshay's minmax branch and Tower Ghost).

**Comment by kyleshay** [comment]
from @knuxem95 

> I made a Excel Workbook that tracks a players gear and it has support for a comma delimited text file that is generated using DIM. Link here: https://www.reddit.com/r/DestinyTheGame/comments/4f95gt/destiny_master_checklist_v21/

> Thanks to wein3967 who created the original code to be used in Chrome's developer console, I was able to modify it to fit my needs. I'm wondering if it would be possible for you developers to expedite the process and make it an option to export this data in DIM itself. Thanks!

> EDIT: Secondary to this, I'm wondering if DIM (through Bungie's API) has access to what shaders, ships, emblems, and sparrows a player has acquired as noted by the kiosks in the game. I'm guessing no, though, as it probably only has the functionality to see a players inventory.

**Comment by Mulchman** [comment]
> Secondary to this, I'm wondering if DIM (through Bungie's API) has access to what shaders, ships, emblems, and sparrows a player has acquired as noted by the kiosks in the game. I'm guessing no, though, as it probably only has the functionality to see a players inventory.

This information is obtainable.  I use Tower+ on Android to notify me when a shader/ship/emblem comes up for sale that I don't already have.  

(As far as I'm aware, Tower+ is only available for Android at the moment: https://play.google.com/store/apps/details?id=scave.dvend&hl=en but of course any app could use the endpoints it uses.)

**Comment by kyleshay** [comment]
Thanks @Mulchman would be happy to start a discussion on something like that if we knew the endpoints, what it could look like in dim, and if was a separate issue to track it. Would like to bring back that collection page DIM used to have one day.

**Comment by Mulchman** [comment]
https://www.reddit.com/user/ingulit is the author's [of Tower+] reddit account

**Comment by kyleshay** [comment]
fixed in #587
