### ISSUE TITLE
Create a loudout to maximize stats

### ISSUE THREAD

**Issue by cdorner** [DestinyItemManager/DIM#488]
So, I'm playing crucible a lot these days and I'm missing something that helps me to maximize my stats like Intelect, Discipline, or Strengh.
When I'm playing with hunter/gunslinger I like to maximize my Discipline so I can throw triplemines at every 25secs, But when using hunter/nightstalker the strengh is better because of the smoke bomb, same thing while playing with Warlock, is better always have melees.

He can also compare stats of my armor and inform that I need change something in the configuration, add more Intelec instead of Discipline for example.

I know, I know I can do the work myself to find the best loudout possible for the situation and then save as a loudout, but would be a nice feature to have if possible.

**Comment by Mulchman** [comment]
With T11/12 loadouts being the norm, this would be a great feature. I've
been using the minmax branch to see what's good %-wise, but it's still a
manual process to do the addition theory and see if you can make
300+/300+/60+.
On Apr 22, 2016 14:18, "Christian Dorner" <notifications@github.com> wrote:

So, I'm playing crucible a lot these days and I'm missing something that
helps me to maximize my stats like Intelect, Discipline, or Strengh.
When I'm playing with hunter/gunslinger I like to maximize my Discipline so
I can throw triplemines at every 25secs, But when using hunter/nightstalker
the strengh is better because of the smoke bomb, same thing while playing
with Warlock, is better always have melees.

He can also compare stats of my armor and inform that I need change
something in the configuration, add more Intelec instead of Discipline for
example.

I know, I know I can do the work myself to find the best loudout possible
for the situation and then save as a loudout, but would be a nice feature
to have if possible.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/DestinyItemManager/DIM/issues/488>

**Comment by kyleshay** [comment]
we'd love to see something like what destinytailor.com does. it's a neat tool.

**Comment by kyleshay** [comment]
fixed in #538
