### ISSUE TITLE
Again not all combinations are calculated and presented

### ISSUE THREAD

**Issue by humandxp** [DestinyItemManager/DIM#5184]
well my previous issue was simply trashed, like all devs recently, removed means fixed.
ok this one is easy, everybody can masterwork previous season and current titan armor.
so lets see
T30 3,9,3,6,4,5 dawning,seraph,dawning, dawning
![aa](https://user-images.githubusercontent.com/24486599/81513223-aa149900-931e-11ea-95e8-7d8b4a6b0bb6.png)
now we will force seraph on legs
T30 3,9,3,6,4,5 dawning,seraph,dawning, seraph
![bb](https://user-images.githubusercontent.com/24486599/81513248-e0521880-931e-11ea-8d3d-62f25fca235a.png)
so question again is also simple, why this configuration is missing from 1st picture when we dont force seraph on legs? and how many more like that are not here

**Comment by ryan-rushton** [comment]
Each row represents a unique combination in the 6 different stats that are listed. The armour visible is a set that combined, will give you those stats. Thus you will only get one set visible for those possible stats. 

By locking the legs you are just seeing a different set that will also give those stats. Furthermore, I would wager that if you click on the little arrow under the legs in the first picture you will see the leg piece you locked in the second picture.

One final point, you mention locking an item like you have restricts it to seraph. It doesn't, it locks it to that exact armour piece. Thus in this example, if you have other seraph boots they would be ignored as they are not the exact item you have locked.

There is a really good video on how this page works at the top of the page, you should check that out.

Finally I need to call you out on this
> well my previous issue was simply trashed, like all devs recently, removed means fixed

Quite simply, we put in our spare time to build something for the Destiny community that we would normally get paid very well to do. We don't owe you this product. 

It took me a number of attempts to figure out what you on about here and your previous issue I couldn't understand it either. If you want us to take you matters seriously give us a really good description of what the issue is with steps on how to reproduce it. This is decent size codebase with a number of people contributing, understanding if behaviour is expected or a bug can be difficult at times.
