### ISSUE TITLE
Mods in Loadout Optimizer mod picker have close buttons

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5341]
Mods in the mod picker have a "close" button that doesn't do anything:
![image](https://user-images.githubusercontent.com/313208/84867548-3017b400-b030-11ea-8303-6752f766131f.png)

**Comment by ryan-rushton** [comment]
Those are there so you can remove mods. I was a little unsure of it but because you can choose say 5 mobility mods, the close icons allows you to remove them without having to remove them directly from the footer. I was even thinking of having a slight variation where its a - instead of the cross, thoughts?

**Comment by bhollis** [comment]
I think the part that tripped me up is they have the close boxes even when they haven't been selected at all.

**Comment by ryan-rushton** [comment]
I am pretty sure I did this with the Closeable component wrapping each mod. I could potentially modify that to have an enabled prop, so it only shows up when we have selected that actual mod?

**Comment by bhollis** [comment]
That'd be nice

**Comment by ryan-rushton** [comment]
Cool, it's now on my todo list.
