### ISSUE TITLE
Show breaker type in item popup, include in search

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5393]
Just realized we don't have anything around breaker types in DIM.

**Comment by sundevour** [comment]
we abandoned the idea when shadowkeep was released because, to repeat a comment from #4282
> fyi this is fairly minor in importance because mods are completely transitory and aside from 1 exotic handcannon, breaker types are actually earned per-character.
> so in most ways this marker just tells you whether the item has a breaker mod attached (a whopping 500 glimmer to switch on or remove). but it's not extremely meaningful because if you move it onto a character you haven't spec'd into that breaker variation and weapon type, it means nothing that the mod is attached.

i guess my modern addition to that would be, they also keep changing *which* types of weapons can be which breaker types, so a filter like "canapplybreaker:barrier" is possible but would need updating every season
