### ISSUE TITLE
Loadout Optimizer Not Working Properly

### ISSUE THREAD

**Issue by Darraess** [DestinyItemManager/DIM#5431]
Hello,
after the latest patch loadout optimizer stat search criteria defaults to a set of minimum values on its own and i can not sett hem to 0. This happens without any other search filter being active.

Thank you

![DIMLOIssue](https://user-images.githubusercontent.com/67900500/86580661-b0726a80-bf87-11ea-91cf-3b492099511d.png)

**Comment by ryan-rushton** [comment]
That is happening because those are the stat ranges being returned after your gear is processed. So in what you have access to, T3 for strength is the lowest you have. By locking gear or changing the minimum stat filter, they will change depend on what is being returned.

The gear you are getting back is the prioritised by highest total tier, then highest tier in the order of the stat filter on the left (you can change it to make something other than mobility of higher importance).

We have some work in the pipeline to make those stat filter have more of an impact but that's not quite done yet.

**Comment by Darraess** [comment]
Maybe i was not clear, the minimum values you see on all stats have been assigned by DIM my problem is not only with STR which i used as an example.

I have no locked gear or perks, and i can not change the minimum values to all being 0.

Have in mind that i am using DIM for almost a year now, i am very well accustomed into how it is used and how to read it.

As it is now i can not, for example, search for sets using Mob 0, Res 0, Rec 0, Dis 0, Int 9, Str 0, which is the way i use to find all the items that can boost Intelligence as high as possible.

The minimum values have defaulted to the ones seen on the screenshot and no value can be lowered to 0, and yes i have alot of items that have Mob 2 for example so creating a set with Mob 0 (or any other stat) is absolutely possible but i can not do it.

Never before have i experienced such a behavior in the loadout optimizer.

**Comment by ryan-rushton** [comment]
Ah I see what you mean. #5423 should fix that issue. Once it gets merged check the beta app to see if it works. 

The optimizer is going through some changes atm as we are preparing it to be able to handle mods in a more thorough way. In its old form that wasn’t possible.

**Comment by Darraess** [comment]
Ok, i will do that, and ill post here if the issue has been fixed.

Thank you.

**Comment by ryan-rushton** [comment]
@Darraess can you please check the latest version of https://beta.destinyitemmanager.com/ (if it wants to update make sure to do it) and see if that is fixed for me.

**Comment by delphiactual** [comment]
Ensure you are on `6.19.0.7490`

**Comment by Darraess** [comment]
Hello,
using Version 6.19.0.7490 (Beta)

The problem is fixed, i can use the stat filters normally.

The amount of sets shown is still very limited this especially obvious when all the lowest values are chosen.
There is also a discrepancy in the amount of sets that DIM reads between not assuming masterwork and assuming masterwork.

With all the stat filters set to their minimum values:

Not assuming masterwork reports that i have 3.543.120 possible combinations of which 1.968.128 are shown, but i am only shown T27 and some T26 sets, something like about 90 sets altogether.

With all the stat filters set to its minimum value, assuming masterwork i am shown only TS31 and TS30 results about again about 90 sets in total, but the statement about the total amount of possible sets is not shown, it is as if i don't go over the minimum limit of 1.968.128 combinations.

Using different filters that generally limit results in a big way but still should return a lot of results, like for example (not assuming masterwork all stats at 0 and mobility at 7) the limit of showing max the top 90 combinations is consistent with all tries i made.

If there is anything specific i can try i would be glad to help.

**Comment by ryan-rushton** [comment]
To clarify first, the number you see up the top is the number of stat mixes, across those stat mixes you will have 200 sets. 

Those sets have been calculated to have the highest total tier, and then they follow the order of the stats you have on the left (I noticed you have the default order, you can change that  by dragging the stat up or down). Other sets can be accessed by clicking the arrow icons under the armour pieces. 

We needed to make this restriction as we are now sending sets from a web worker back to the UI. With a large number of sets this could take up to 40 seconds and cause memory crashes.

At some point I want to unwind the sets a little that sit under the arrow icons but that was how it worked before, you just don't see thousands of results as before.

>There is also a discrepancy in the amount of sets that DIM reads between not assuming masterwork and assuming masterwork.
Thats because setting assume masterwork recalculates everything and a different set of stat mixes is returned.

>If there is anything specific i can try i would be glad to help.
It sounds like it is working as intended, there will be more coming as we are positioning it to be able to handle more robust mod calculations. I will try and look at unwinding those sets from the arrow icons in the next week or so.

What we are aiming for is a smaller set of results that is more dependant on the filters you use. Those filters should determine what you are looking for. Personally I had a stat order that I care about so I have it set to that, then I try to maximise the stats I care about most.
