### ISSUE TITLE
Add a favorite box to DIM to allow players to quickly equip their most frequently used items

### ISSUE THREAD

**Issue by KiaArmani** [DestinyItemManager/DIM#5462]
**Proposed change**
I'd like to see a box with user-selected weapons / armor that I can quick-equip by clicking on it.
Something like this:
![fav2](https://user-images.githubusercontent.com/3679543/87665790-c4785200-c767-11ea-922b-a5200de8f563.png)

**How does this fit into your workflow?**
Instead of abusing the Loadout system for this, I can quickly access my favorite weapons without having them take up inventory space.

**Comment by caquino** [comment]
Actually expanding on the suggestion it would be interesting to have that side element being configurable with options like:
 - Favorites
 - Top used weapons
 - Highest level equipment

**Comment by DHager** [comment]
IMO that goes into custom multi-tags territory. For example, being able to go: `is:weapon tag:favorite tag:pvp` ... 

You can get a poor man's version by abusing `memo:`, but setting or changing those not-actually-tags is a real pain.

**Comment by bhollis** [comment]
> setting or changing those not-actually-tags is a real pain

How so?

**Comment by DHager** [comment]
> How so?

The biggest issue is that actually adding/renaming/removing tags requires clicking every item individually in the main interface, and editing its memo-field text by hand. This has led to cases where I'm going around copy-pasting the text like `[PVP]` over and over. (I use the brackets to prevent false-positives since `memo:` is a substring search.)

Another issue is that there's no way to know what tags have already been defined, or to detect when you've made a typo and created an accidental new tag. For example, I may use `[PVP][Momentum]` for weapons that shine in the Momentum Control game-mode, but a typo of `[PVP][Momnetum]` is not easy to discover unless you're already staring at the icon wondering why it isn't highlighted.

In contrast, the current (exclusive) tags are all enumerated for the user, and can be easily set/removed on any search-result.

**Comment by bhollis** [comment]
Give the Organizer a try?

**Comment by kyleshay** [comment]
I like the idea of being able to quickly access your favorites. Ideally this could tie in with the activity monitor concept. #2959 I'll link this idea from there and close this in favor of that. Thanks!

**Comment by kyleshay** [comment]
https://www.youtube.com/watch?v=xYmFZPTucqE

Still needs to be flushed out, but was imagining something like:
1st column are favorited items
2nd column active character
3rd column rest of your items. armor that is not of your current subclass is hidden.
