### ISSUE TITLE
You can get DIM in a state where you items won't show

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#566]
* Click MinMax
* Click 'Back to DIM'
* wait a bit to see if your items load or not

Repeat this process. At some point after clicking 'Back to DIM' you'll be left with an empty view. This exists in the current release and wasn't introduced with the T12 stuff.

**Comment by ericnelson0** [comment]
Finally was able to track this down.

When the state is switched back to <code>'inventory'</code> for the first time the stores are reloaded in <code>dimStores.directive.js</code> because <code>$scope.$root.activePlatformUpdated</code> is true. The next time we go to the <code>'inventory'</code> state  <code>$scope.$root.activePlatformUpdated</code> is no longer true and therefore the stores are not reloaded.

A simple fix is to change the lines starting from <code>line 66</code> of <code>dimStores.directive.js</code> to:

```
    if ($scope.$root.activePlatformUpdated) {
      loadingTracker.addPromise(dimStoreService.reloadStores());
      $scope.$root.activePlatformUpdated = false;
    } else if(!_.isNull(dimPlatformService.getActive())) {
        loadingTracker.addPromise(dimStoreService.reloadStores());
    }
```

but there might be a better solution, I'm not sure.
