### ISSUE TITLE
Bottom bar instead of collapsible headers on mobile

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5731]
We've landed a first pass for this on the dev branch, but have some additional thoughts before we consider pushing to beta. May also scrap the idea if we end up not liking it in dev

- [ ] Color of bottom bar? [Black] / [Purple (like fixed header)]. Black bleeds better into the nav bar on mobile, but we could change the nav bar color to match.
- [ ] Style text like the collapsible headers or something else?
- [ ] What to do w/ postmaster (right now it shows up on the inventory page for each character.)
- [ ] Verify it on iPhone
- [ ] Only show stats armor on stats on the armor tab? [ Y ] [ N ] 
- [ ] Move 'inventory' contents to the vault, as it's just duplicated between the characters? Vault could have collapsable headers to make getting between easier. Or move inventory contents to general (general is pretty empty.)
- [ ] Tab at bottom to jump to tag:favorite weapon/gear/loadouts?
- [ ] Use icons from the Organizer instead of text?
- [ ] It would be neat to have a opt-in/out setting for these dev-only options. Could push to beta and have beta-only settings to toggle.
- [ ] Should swiping go between categories instead of characters, and then the only way to swap characters is the header?
- [ ] Show bucket labels ("Kinetic" / "Energy" / "Power") to help split up page? only in vault?

![Screenshot_20200903-120724](https://user-images.githubusercontent.com/424158/92158940-7a176700-ede1-11ea-9289-64059afc1a1b.png)

**Comment by bhollis** [comment]
We may need to release this to beta to really get a sense of it - I run beta on my phone but can't easily use dev.

1. I like the black bar! If we make the header transparent I might change my mind.
2. On iPhone, remember that the bottom 44px (not counting the iPhone X "chin"!) won't respond to the first tap unless you're in standalone mode, so you may want to add padding in that case.
2. I like the all-caps labels! I'd maybe give it an orange underline like we do for selected tab on desktop.
3. Postmaster is super important. We could give it its own tab (with a badge?)
4. I kinda like the idea of pinning armor stats to the armor tab.
5. Inventory in Vault is weird, because you can put stuff from inventory *into* vault.
6. Use icons from the Organizer instead of text? - I'd like to see what this looks like
7. It would be neat to have a opt-in/out setting for these dev-only options - I love it. You can write anything you want into settings in DIM Sync (it just stores it as JSON).
8. I think swiping should still go between characters, though I really really intend to make that smoother when I replace the pager.
9. Show bucket labels ("Kinetic" / "Energy" / "Power") to help split up page? - maybe? If we switched to icons we could have sub-icons fly out when you select a tab.

It'd also be neat to try out something that's not a bar on the bottom, but a fly-out dot in the corner that buttons to switch view - harder to discover, but takes less screen space.

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/pull/5822
