### ISSUE TITLE
Updated Triumphs/Collections & Tracked Triumphs Feedback

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5741]
This is to collect feedback on the new Triumphs/Collections search and Tracked Triumphs

**Comment by bhollis** [comment]
> search interacts very poorly with Hide Completed

> also search results look like they're tracked because the Tracked header remains but the Triumphs header disappears

> .triumph-record should be overflow hidden

> the .7 opacity tracking marker interacts poorly with the box border

> tracking a triumph styles it like it's completed

**Comment by bhollis** [comment]
#5742 includes a fix for 1 and 2. #5743 has fixes for 5.

I'm not sure what 3 is getting at (what overflows?) or what about the border is interacting poorly.

**Comment by nev-r** [comment]
re 3:
i don't like how the 1px border looks, showing through the dimmed (inactive) tracking icon
![image](https://user-images.githubusercontent.com/68782081/92331430-67906e00-f02b-11ea-9c2a-69abc75428ba.png)

it looks like it's part of the icon, is a little strange at some zoom levels, especially during the zoom transition, but moving it down 1px causes a lot of problems so i thought overflow would nicely hide it but i was not at the time counting on how thick the border gets once something is tracked, which starts to cover the dim logo. i would prefer a form of dimming that wasn't opacity, maybe a darkening filter() since opacity is starting a new stacking context regardless

**Comment by errera** [comment]
Not sure if it's a bug, but the latest Beta (or at least the one I'm running, 6.27.0.8148) is no longer showing Catalysts that are available but not started. If that's a toggle, I don't know where to turn it back on. (The current non-beta still shows all available Catalysts, whether I've begun them or not.)

**Comment by nev-r** [comment]
beta is the intended behavior. the catalysts section should only show catalysts you *have* (like, found. saw in your loot feed), not every catalyst the game knows about (looking in Triumphs would be the appropriate place to see what else is in the game)

just like we show the bounties you're *holding*, the Catalyst section is meant to be a To-do list for catalysts that you have, but haven't finished

**Comment by nev-r** [comment]
in search results, multiple headings with the exact same requirements, should be collapsed (looking at you, collections badges)

**Comment by errera** [comment]
Okay, I suppose that's reasonable. The Triumph section shows the ones I don't have as 'Secret' (though the graphics let me know what they are, even though I no longer have access to the requirements to finish them)... but I guess I understand the split. I guess it would be nice if DIM had a toggle that let me decide whether to see 'Secret' data or not (when available, of course, as it clearly is in this case).

**Comment by errera** [comment]
(To be clear: I'm always going to lament the loss of information - the current build contains information that is no longer available in the Beta, and you've just confirmed that the Beta is the intended behavior. This makes me sad.)

**Comment by nev-r** [comment]
![image](https://user-images.githubusercontent.com/68782081/92333732-a549c280-f03c-11ea-9669-679c9791af68.png)

**Comment by errera** [comment]
DOH! Thanks. Didn't even see that.
