### ISSUE TITLE
Wishlists marking items inconsistently 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#5917]
**What version of DIM are you using?**
various environments 

**What Browser and OS are you using?**
chrome 

**Describe the bug and how to make it happen**
It's been reported that some wishlist items are not always marked and sometimes what gets marks varies between beta and prod. I cannot reproduce this right now but below is a screen cap I took 2 days ago that demonstrates beta and prod had different items marked.

![image](https://user-images.githubusercontent.com/29002828/94489339-44805680-01b2-11eb-8d05-55faf4345c14.png)

**Comment by Bravokado** [comment]
**What version of DIM are you using?**
Version 6.32.0 (release), built on 9/27/2020, 5:06:17 PM

**What Browser and OS are you using?**
Chrome (PC), Chrome (Android)

**Describe the bug and how to make it happen:**
- If I refresh the Chrome tab DIM is on, some non-wishlist items become wishlisted; and some wishlist items become non-wishlisted. The former items would receive a :thumbsup: because of just one or two curator-suggested perks (not a full string of perks), without wishlist notes. 
- Going into settings and updating the wishlist will return the items to normal, but it bugs out again if you refresh the tab (not refresh inside of DIM).

Before / After Chrome Tab Refresh photos added below: 
![wishlist before](https://user-images.githubusercontent.com/72051197/94495059-9d95bd80-01a5-11eb-84c3-aac88df430d9.png)
![wishlist after](https://user-images.githubusercontent.com/72051197/94495064-a090ae00-01a5-11eb-9d64-05d2856c275b.png)

**Comment by bhollis** [comment]
This has to be some interaction with the double-initial-load stuff @kyleshay was messing with.

**Comment by acelerador25** [comment]
**What version of DIM are you using?**
Version 6.32.0 (release), built on 9/27/2020

**What Browser and OS are you using?**
Chrome (PC)

**Describe the bug and how to make it happen:**
1. I enter to the Wishlist section and delete that wish because I imagined that was a new update on the wishlist I use in that moment.
2. Im goin to this [Wishlist Page](https://github.com/48klocs/dim-wish-list-sources) and select the [Voltron with "trash rolls"](choosy_voltron.txt is voltron with some opinionated trash rolls added in.) and pasted on the **Wishlist section** on **DIM** and see this roll on my handcannon:

![Wishlist 1](https://user-images.githubusercontent.com/22378686/94595773-dd65af00-0250-11eb-8b5f-375377be031e.png)

3. After that action on the **inventory section** (pass very few minutes), the web is refreshed automatically (similar to me doing it manually when I press F5) and then I see the same weapon with this **wishlist roll** (I have changed the perk ingame that you saw in the previous image):

![Wishlist 2](https://user-images.githubusercontent.com/22378686/94596070-41887300-0251-11eb-8cc9-64aa65ac35e5.png)

I've seen that inconsistent because I see first that say the Wishlist that is a **PVP** weapon, and in this case, I see that say **PVE** weapon and only say me in the wish that is good 1 perk.
4. Something similar happens in other weapons that I have because I have weapons that not have the the good hand in his box and then, after the refresh, they have good roll on that weapons that before not have, and in others have the good hand before and have too now but with 1 or 2 good perks in his image, similar to the handcannon, but in this case **not change the PVP or PVE Wishlist Recomendation**
