### ISSUE TITLE
Option to append to notes

### ISSUE THREAD

**Issue by Kellen-Hartnett** [DestinyItemManager/DIM#6093]
I've just started using the notes system and I'm finding it very useful, but it is a little tedious assigning notes to a large group of items. The existing add notes option from the search bar and the organizer are handy, but they overwrite existing notes on items. This is good to have, it lets me overwrite notes I don't want anymore, but it would also be nice to be able to append to existing notes on sets of items. 

For example, the way I use notes is to create more tag groups of my own, like 'PVE' and 'PVP'. The problem comes up when I have a weapon I want to put in both categories. If I assigned all items in a search as 'PVE', and then did another set notes of a different search as 'PVP', it will overwrite the 'PVE' note on any that had one previously. It would be nice to make the notes on those items that are in both categories something like 'PVE PVP', so they will show up in a search for either note. While I can accomplish this with a third pass, explicitly assigning items the note 'PVE PVP', it would be more intuitive to be able to add multiple "tags" to my items.

**Comment by bhollis** [comment]
That'd be a cool thing to have when we build our own Confirm widget

**Comment by DHager** [comment]
> it would also be nice to be able to append to existing notes on sets of items.

I would use this.  Right now I "note tag" using special braces like `[PVP]` or `[Boss]`, so that I can avoid false-positive results, like "[PVP] but in PVE the perk X backfires because Y`. 

That said, I think it's worth stepping back and examining the *real* problem, which is that the existing ~~tag~~ fixed category system is not working out, which is why people like you and me are hacking up workarounds using the notes-field.
