### ISSUE TITLE
docker-compose up fails with engine node incompatible with this module

### ISSUE THREAD

**Issue by broady** [DestinyItemManager/DIM#6226]
**What version of DIM are you using?**
```
$ git rev-parse HEAD
c2bb7035a11a4aae5318fa5768995733af9bd881
```

**Describe the bug and how to make it happen**

```
$ docker-compose up
...
Creating dim-webpack ... done
Attaching to dim-webpack
dim-webpack | yarn install v1.22.5
dim-webpack | [1/4] Resolving packages...
dim-webpack | [2/4] Fetching packages...
dim-webpack | error bungie-api-ts@4.5.0: The engine "node" is incompatible with this module. Expected version ">=13.2.0". Got "10.23.0"
dim-webpack | error Found incompatible module.
dim-webpack | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
dim-webpack exited with code 1
```

**Comment by GrimmiMeloni** [comment]
I ran into this myself trying to get my feet wet with the DIM code.
For me it works locally at first sight, i.e. I can log into my account and see my guardians data with my local build based on this. However due to my inexperience I am not confident that _everything_ will work.
Maybe there are tests I could have run? Please excuse my ignorance, as said, I am just starting to set things up.
