### ISSUE TITLE
Active mode issues in beta

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#6245]
The active mode pane doesn't replace character columns in beta (I'm on Chrome 87/Win 10, if it helps).

As a minor secondary issue, the toggle button's placement seems a bit more finicky than it was previously? When I loaded in active mode, I had 3 active scrollbars (vertical for the active pane, horizontal, another vertical for the characters).

![active mode go boom](https://user-images.githubusercontent.com/606888/100516392-96f9d700-3151-11eb-98d1-ed5a145586da.png)

**Comment by bhollis** [comment]
It doesn't replace the character columns anymore, that's a separate button (the chevrons)

**Comment by kyleshay** [comment]
yeah the active mode can be triggered if you're in the single or multiple character view now. ill clean up the scroll bars. 

i agree the button style/placement doesn't feel 100% final, i had tried putting it fixed on the left side but it would take up a lot of space then. 

![](https://user-images.githubusercontent.com/424158/100189463-36dd0980-2ea1-11eb-8739-ead463bc0dff.png)

**Comment by 48klocs** [comment]
This sounds like a dupe of known design issues.

**Comment by jgierer12** [comment]
Sorry to comment on a closed issue, please let me know if I should open a new issue for these concerns instead.

I much preferred the original Active Mode where you could manually select the active character. I often switch characters quickly when power leveling or doing raids, and DIM is quite slow to update when I switch characters. Having no way to manually select the currently active character, makes Active Mode almost useless to me as I often use it directly before or after switching characters.

I also noticed that the loadout section is gone from the Active Mode sidebar, I'm not sure if that's a bug or intended but either way I'm really missing it.

Honestly these changes made Active Mode nearly useless to me, which is unfortunately since I really fell in love with the original Active Mode for the short time I've been able to use it.

**Comment by kyleshay** [comment]
Thanks for your feedback and beta testing the new mode. The project is still a work in progress and there might be some bumps. I welcome you to check out the latest PR: https://github.com/DestinyItemManager/DIM/pull/6249

We've added an automatic refresh so that active mode so DIM swaps to your active character much faster. Hoping to land it this week and hope you give it a try. 

The ability to apply a loadout still exists in the character dropdown, It felt unnecessary to having it in both places so I removed it when we added the character tiles back in.

**Comment by jgierer12** [comment]
Thanks! Hopefully the auto refresh should resolve most of my issues. Personally I would like the loadout selection to be added back to the Active Mode panel simply because it requires one less click, which would save me quite a bit of time as I use the loadout feature a ton. But I understand if you don't like the idea of having it in both places.
