### ISSUE TITLE
Junk item power level warning

### ISSUE THREAD

**Issue by zzm634** [DestinyItemManager/DIM#6262]
Feels bad to accidentally dismantle a high-power drop without realizing that you needed it for the power climb. It would be nice to have a warning pop up if you tag an item as "junk" when that item is currently contributing to your maximum power level. 

It could be something like, when an item (or items) is tagged as "junk", DIM recalculates the maximum power with and without "junk" items, and pops up a warning notification if there's a difference. "Warning: some items currently tagged as 'junk' are contributing to your maximum power level." Doesn't need to be specific as to which item.

**Comment by bhollis** [comment]
What I do is search `is:junk is:maxpower` and untag those items before going on a deleting spree.

**Comment by zzm634** [comment]
I mean, yeah... but if one were cognizant enough to do that every time, this enhancement would be unnecessary. The point is to act as a safety net for forgetful people.

**Comment by bhollis** [comment]
No doubt! I think this would be a good feature, just gotta think of the right way to indicate it.

**Comment by DHager** [comment]
IMO it isn't really a tagging issue, since the actual "oops" moment often occurs in-game, and the player either didn't see the tagging or didn't realize they were operating on the wrong item. In many cases I didn't even visit DIM before making the mistake, falling into the habitual movements of dismantling junk-blues.

In other words, the player can still easily dismantle something unlocked even if the tag is still "favorite". 

Personally I'd like to see two automatic locking options:

1. When a new item appears for the first time which is max-power in its category (e.g. "Energy weapons" or "Titan Helmets")  lock it automatically.
2. When any item is not locked but is tagged keep/favorite/archive, lock it because the user *probably* doesn't want to accidentally delete it in-game.

**Comment by BrightReach** [comment]
Any chance I can have a go at cracking on this?

**Comment by inexorableAce** [comment]
You’d just end up with a fully locked inventory if we did this. And combing through the entire inventory every time you drop something swapping lock states would take a millennium. Locking is not a speedy api action. Also locking in general is kinda moot since there is bungie bug that tampers with lock state.

**Comment by BrightReach** [comment]
> You’d just end up with a fully locked inventory if we did this. And combing through the entire inventory every time you drop something swapping lock states would take a millennium. Locking is not a speedy api action. Also locking in general is kinda moot since there is bungie bug that tampers with lock state.

Though what if a new tag was made to indicate that it's a new item or use the existing mechanic within the app. Then after 24 hours and it's not the maximum power and/or not tagged with keep/archive/favourite, then it gets unlocked.

**Comment by inexorableAce** [comment]
We have a mew item indicator but creating timers for ever new item to say that it’s “not new” after 24 hours is a waste of data IMO. There is nothing that’s happens in 24 hours that ensures and item is “not new” to a person either. Again moot, because locking is not reliable with the bungie bug. 

Also you’re putting a lot of faith in DIM knowing you dropped a new item at all before one decides to try an delete it. 

Truly, DIM can’t save you from deleting something... it can have a message that says you’re about to transfer a max power item and to be careful. That seems fine, it also won’t save someone more than just taking an extra 2 seconds to ensure your. It doing something you’ll regret.

**Comment by shallowbit** [comment]
What If you just add another indicator like the dot used for is:new which alerts the user the item is contributing to their light level Maybe it's the same dot, just a different color for new, powerful, and both. You could also change the frame color like a MW item. Then the user has at least initially seen the item and has at one point been aware of it's level.

**Comment by bhollis** [comment]
Closing this in favor of the tracking issue https://github.com/DestinyItemManager/DIM/issues/10452, which has additional info.
