### ISSUE TITLE
FR is there a way to have multiple users on DIM?

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#627]
In the past, every time i tried to show someone how to use DIM, and logged into their account, then  switched back to my account all my saved  loadouts were gone.

**Comment by Mulchman** [comment]
I use a different chrome profile for each b.net account I play on.  Google
search 'Chrome profiles' if you're not familiar with it.
On Jun 21, 2016 19:02, "nki2bpz" <notifications@github.com> wrote:

In the past, every time i tried to show someone how to use DIM, and logged
into their account, then switched back to my account all my saved loadouts
were gone.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DestinyItemManager/DIM/issues/627>, or mute the thread
<https://github.com/notifications/unsubscribe/ALNpqcxsvhr3ajd7y7BGlpnQXW-Lka8fks5qOJedgaJpZM4I7Vra>
.

**Comment by kyleshay** [comment]
Create chrome profile, your accounts (loadouts) will sync to that. Let me know if you have issues with that and we can revisit this.
