### ISSUE TITLE
PR workflow build doesn't work for PRs from forks

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6421]
Looks like if a PR comes from a fork, instead of a branch in the main repo, the PR build doesn't run.

**Comment by ryan-rushton** [comment]
Yes that is correct. I can't fix this without splitting pack tracker from the main build. I know it means the build will get run twice but it's the only way. Pack tracker needs to run on push and the pull request needs to use the event "pull_request". Then from my understanding the pull_request event will get run on the main repo. Another option is to use pull_request_target but the docs aren't super clear on how that works so I would need to investigate

**Comment by bhollis** [comment]
It's weird because our previous Travis builds were triggered from the pull request event and were definitely able to figure it out.

**Comment by ryan-rushton** [comment]
We could give it a go but what the pack tracker docs state it needs to be run on push.

**Comment by ryan-rushton** [comment]
Just some house keeping here. Builds are working now but we aren't seeing packtracker results from forked repo's. I have a PR (#6445) that definitely sets the values correctly but we still don't see results. I have reached out to packtracker to look into it. I will follow it up in the next few weeks since its been a while.
