### ISSUE TITLE
I'd love to disable the Collect Postmaster button

### ISSUE THREAD

**Issue by irons** [DestinyItemManager/DIM#6426]
**Proposed change**
I only ever press the Collect Postmaster button accidentally, and doing so always makes me sad. I'd really appreciate a mechanism to remove it from the UI, or render it inert. 

If there was a way to cancel the just-invoked transfer of all items from the postmaster, I would use it. If there was a confirmation step before taking action, I would bail out every time I had the chance. 

**How does this fit into your workflow?**
Using DIM mostly on an iPad, I brush against this button by accident about twice a month, usually while trying to tap on an item in the bottom row of the postmaster, or intending to show/hide the Weapons section. My character slots and vault run close to full, and the postmaster is rarely empty, so whenever I do hit this button, it amounts to a randomization of on-character gear, and threatens to fill up the vault. Identifying the gear that I currently want equipped and forcing the keep-or-shard decisions that I'd deferred for things still in the postmaster are both time-consuming and undesirable, and I'm obliged to deal with both before I can return to the game.

Thanks for your time.

**Comment by FlaminSarge** [comment]
For the time being I've been using this in the Stylus extension:
`.dim-button.bucket-button {
    visibility: hidden;
}`

**Comment by bhollis** [comment]
We won't disable the button, but we do intend to add a cancel button to the notification (I think there's an issue in here somewhere for that). In general while we recognize that people use the Postmaster for extra storage, we do not optimize for that because it's a fundamentally dangerous place to store your items. Likewise, DIM is geared around treating all your items as a large pool rather than worrying too much about what's currently on your character - use loadouts and tags to keep track of what you like to have on your character. Note also that pull from postmaster will never de-equip any equipped items - it only moves unequipped items if there is not enough room to pull into that category.

**Comment by irons** [comment]
Looks like the case that mentions adding a cancellable notification is #3555. 

I should be clear that I don't consider this use of the postmaster to be extra storage. It's stuff that needs triage, because it's new and I wasn't able to instantly decide to delete it. That's why shifting it all onto characters and into the vault is the last thing I want. If not quite data loss, it's certainly state loss, and the upshot is that there's a region on the screen that must never be touched.

Thanks again.

**Comment by bhollis** [comment]
Consider using the "new item" indicators to handle that.

**Comment by mrgv** [comment]
I have yet to click that button on purpose.. I feel terror when moving the mouse over it with my touchpad and I carefully snake the pointer around that button every time I need to cross past it. Only a "Delete all my items and remove my account at Bungie" would cause me more fear hehe. 

I too would love a confirmation or an option to remove this button altogether. Besides, do people use it that often? Might be good for the UI in general.

**Comment by bhollis** [comment]
Yes, people use it very often, keeping your postmaster free is an important part of not losing your items.

**Comment by bhollis** [comment]
Confirmation before pulling from postmaster is now in beta.

**Comment by bhollis** [comment]
Reopening as I'm removing the confirmation. It's too annoying.

**Comment by bhollis** [comment]
In beta, the notification that we're pulling from postmaster now has a "Cancel" button that'll stop pulling. I think that's a good tradeoff between keeping low friction and allowing people to stop a mistaken click. Thoughts?

**Comment by Scuzzlebuttt** [comment]
I was just on Discord bitching about accidental clicks on this cursed button...  I would happily take a "Cancel" button so I can stop the process before too much damage is done.  THANK YOU!

> In beta, the notification that we're pulling from postmaster now has a "Cancel" button that'll stop pulling. I think that's a good tradeoff between keeping low friction and allowing people to stop a mistaken click. Thoughts?

**Comment by FlaminSarge** [comment]
@bhollis is it viable to add a (potentially configurable) delay before it starts making inventory changes so that we can hit that Cancel button before anything major happens? It looks like right now, as soon as you hit the button, things start moving, so if you fat-finger it you still potentially end up with the mistaken click having some kind of effect.

**Comment by bhollis** [comment]
I'd rather not add a delay. It's slow enough already.

**Comment by bhollis** [comment]
Closing as we now have a way to quickly cancel pulling.
