### ISSUE TITLE
Range masterwork values not showing in tooltips

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#6449]
Current beta, Chrome, Windows 10.

Stability masterwork.  Shows masterwork value.

![image](https://user-images.githubusercontent.com/25425159/104799556-ce1a6980-581f-11eb-8529-52dfede59522.png)

Range masterwork.  Does not show.

![image](https://user-images.githubusercontent.com/25425159/104799866-e8544780-581f-11eb-8034-8e61afb953a2.png)

**Comment by bhollis** [comment]
Which item is this happening on? Is it happening on all items? I see range masterwork bonuses on mine.

My guess is that due to how stats work in the game, a tier 2 masterwork on this weapon actually doesn't increase range. See https://github.com/DestinyItemManager/DIM/wiki/DIM's-New-Stat-Calculations for how this can be possible.

**Comment by philkernick** [comment]
It's on Succession (raid sniper).

Identical behaviour in both beta and prod.

I've subsequently deleted the range masterwork one shown above, but I have two more, both with range masterworks which show the same behaviour.  The one with +1 masterwork shows no bonus in the tooltip.  The one with +2 masterwork shows +2 in the tooltip.

![image](https://user-images.githubusercontent.com/25425159/104833184-b6f27f00-58e6-11eb-9617-b4baabdb0466.png)

![image](https://user-images.githubusercontent.com/25425159/104833192-c07be700-58e6-11eb-9f3e-9f48ee549139.png)

I don't think it's just scaling as the display interpolation for the reload stat for that sniper is is [0, 10] -> [100, 100].

https://data.destinysets.com/i/InventoryItem:2990047042/StatGroup:1069606838

That would make +1 masterwork -> 0.9 scaled -> 0 shown, but +2 masterwork -> 1.8 scaled -> 1 shown, but that +2 shows as +2.

I also note that the scaling only applies to the sockets, and not to the base weapon stat.  Not sure if this is how it is supposed to be based on your wiki article.  If the weapon has a base stat of 42, and no sockets that modify that stat, shouldn't that display as as 47 in DIM?  10 + 0.42 * 90 = 47

**Comment by bhollis** [comment]
Stat interpolation works on "investmentStat" which is not typically displayed (because it's worthless without interpolation). What's important to keep in mind is that the value we show on mods is how much it adds to that specific gun. That takes into account all of its existing stats and any other perks/mods on it, and calculates the value without the given mod and with it, and shows the difference.

Base investment reload on Succcession is 35. Reload scales from [0, 10] -> [100, 100], which means an investment stat of 0 would be reload 10, and investment stat 100 would be reload 100. Tactical Mag adds +10 to the investment stat, so we have 45. So without any masterwork, the interpolated (real) reload would be 45/100 * 90 + 10 = 50.5, which we then use banker's rounding to get to 50. With a +2 masterwork, the stat would be 47, which gives us 47/100 * 90 + 10 = 52.3 which is 52, thus it gives +2 to reload. Likewise, a +1 masterwork would be 46 which gives 51.4 which is 51, thus +1 reload.

Taking a look at your +1 masterwork, you have no perks that modify reload, so you have 35/100 * 90 + 10 = 41.5 = 42 (banker's rounding!) base, and (36/100 * 90 + 10) = 42.4 = 42 with a +1 masterwork, so the real effect of a +1 masterwork on range is +0.

I can't tell you exactly why range netted out as +0 for you, because I don't know what perks you had. But I'm pretty confident our math is correct.

**Comment by philkernick** [comment]
Like all things, it's more complicated than it looks!

Can I suggest that we actually report masterwork stats that don't have an effect as +0, rather than omitting the value.

**Comment by bhollis** [comment]
Yeah, that makes sense, though I'm not sure it'll alleviate people's confusion. I'll have to check because the data definitely has stats with +0...
