### ISSUE TITLE
Microsoft Store: Installation Error

### ISSUE THREAD

**Issue by Spuner** [DestinyItemManager/DIM#6463]
![Untitled](https://user-images.githubusercontent.com/30773815/105622649-98cbd800-5e2c-11eb-890e-4e37634aa5cc.png)

**Comment by kyleshay** [comment]
can you load other apps? there haven't been any updates to the dim windows app since we launched it. wondering if something is up with the ms store

**Comment by Spuner** [comment]
With other applications, everything is fine - they are installed without errors.

**Comment by kyleshay** [comment]
Ah, thanks for the update. Not much to work from since it's mostly out of our control. I'll see if I can forward this to a support team for the store once they work out some more of the kinks in their app store submission site. :/

<img width="1186" alt="Screen Shot 2021-01-26 at 12 30 08 PM" src="https://user-images.githubusercontent.com/424158/105901550-61972b80-5fd2-11eb-8c21-ba4b46b510ad.png">

**Comment by JudahGabriel** [comment]
@Spuner does your machine have the [new Edge](https://www.microsoft.com/en-us/edge) installed?

**Comment by Spuner** [comment]
> @Spuner does your machine have the [new Edge](https://www.microsoft.com/en-us/edge) installed?

Yes, but the problem resolved itself. Perhaps the problem was Windows updates.

**Comment by JudahGabriel** [comment]
Ah, yes, that's possible. The latest Windows version will have the necessary Edge dependency, so that was likely the issue. Glad it's working for you. 👍
