### ISSUE TITLE
Sunsetting Current Season Constant Incorrect?

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#6498]
**What version of DIM are you using?**
Version 6.51.1.1000203 (beta), built on 2/10/2021, 2:54:34 PM

**What Browser and OS are you using?**
All browsers on macOS

**Describe the bug and how to make it happen**
filter:     *sunsetsin:current*

This reveals items that were sunset at the end of *last* season (12), which is no longer the current season.  I expect that this filter would only show items that expire at the end of *this* season, the current season, 13.

**Comment by delphiactual** [comment]
sunsets _in_ : not sunsets _after_ :

**Comment by bhollis** [comment]
To elaborate on Delphi's comment:

"sunsetsin" tells you which season an item "became sunset" - things which stopped being able to increase light starting in that season. So "sunsetsin:current" highlights things like Perfect Paradox which only just became sunset in season 13.

"sunsetsafter" tells you the last season an item is *not* sunset. So for example, Seventh Seraph Carbine matches `sunsets after:current` because this is the last season it'll be infusible to max light.

In general, when filing bugs it's very helpful to include screenshots and other details to help with your issue. I can't tell which items you're talking about, so I can only guess that you misunderstood the meaning of the filter.
