### ISSUE TITLE
Search filter for item hashes that have no wishlist rolls

### ISSUE THREAD

**Issue by Shloub** [DestinyItemManager/DIM#6538]
Hi,

**Proposed change**
I would like a way to differentiate bad rolls from non-rated weapons. For instance, if the weapon is not in the wishlist at all, it could be a "?" instead of thumbs up, or a message "Weapon not found in wishlist" on details modal. D2 Checklist displays "No godroll info yet".

**How does this fit into your workflow?**
I usually dismantle weapons which are not good rolls. At the beginning of a season, it's pretty clear most weapons are not rated, so I keep most of them. However, sometimes I'm unsure whether my rolls are bad or just unrated. Is that new (random) exotic OK? What about that new Trials weapon (another tool says it's OK)? 

Thanks :)

**Comment by 48klocs** [comment]
I guess I can see some sort of value in adding an `is:wishlistunknown` filter (I'll leave the actual naming up to whoever).

Slapping a visible indicator where we show a thumbs/up down based on the lists would add way more noise than signal, so I'd strongly recommend against that.

Exotics are their own weird case, since lists I've seen mostly gloss over those (with good reason - Hawkmoon and Dead Man's Tale are the only two with random perks).

**Comment by RocheM** [comment]
I started looking into this issue, I began to implement a `is:wishlistunknown` as described by @48klocs  - when writing the logic for this filter, I realized this would essentially be the same as writing `not:wishlist`.

If I'm correct in my understanding, this issue is requesting the addition of logic to filter items which have not yet been considered for the wishlist. But I'm unsure how this would be accomplished as wishlists are incomplete, so it's difficult to say what has been considered and ignored, vs. not considered.

Am I missing something in this case? It would be trivial for me to add a `is:wishlistunknown` but if we're just going for the inverse of `is:wishlist` I don't see the value.

**Comment by RocheM** [comment]
Ah I think I see the issue, I reviewed a wishlist, against my own items and can see that the `is:wishlist` filter only returns if we have all matching perks.

So the `is:wishlistunknown` would match item id's alone, without considering perks. Apologies for the confusion, I'll see about implementing this.

**Comment by Shloub** [comment]
Thanks for your help. FYI https://destinyrecipes.com/vault has a similar feature, with the message "Perk ratings for this weapons are not available yet" (but the implementation may be buggy).

**Comment by gt6796c** [comment]
I took a shot at this in https://github.com/DestinyItemManager/DIM/pull/7968. Did a bit of a refactor to remove the concept of `null` == _missing_ since we lose some info there.
