### ISSUE TITLE
Sterling Treasure reporting within inventory when not there yet

### ISSUE THREAD

**Issue by sinicide** [DestinyItemManager/DIM#660]
Just noticed this today (reset day) But the sterling treasure that you normally get from the post master is already looking like it's pre-populated within my inventory. While that would awesome if it was true, but I know it's not since I have not yet logged into Destiny for reset today yet. So I would expect to see it under the postmaster, which it is not displayed there.

I'm currently running the beta version. 3.7.4.223, so I hope this is the correct repo to report issues in.
![sterling_treasure_issue](https://cloud.githubusercontent.com/assets/4177251/16587401/75fd66e0-4298-11e6-8740-4338f771fa68.png)

**Comment by bhollis** [comment]
Viewing your character in DIM is enough to give you the Sterling Treasure!
It's really there.

**Comment by SunburnedGoose** [comment]
This is a bug because we're not picking up that this is in the postmaster.  This is causing an issue since my inventory is now 21/20 on my main due to this error.  

![screen shot 2016-07-14 at 8 27 18 pm](https://cloud.githubusercontent.com/assets/984608/16860863/6db5a7d4-4a01-11e6-9a75-16cbfb0b288c.png)

When I take an item out and DIM shows 20/20, but in game it is 19/20.  When I try to move something into the consumables from the vault, I get an unrelated error.

![screen shot 2016-07-14 at 8 28 44 pm](https://cloud.githubusercontent.com/assets/984608/16860904/b34c6bde-4a01-11e6-8ef5-5a730919c2e4.png)

**Comment by SunburnedGoose** [comment]
The bug is here.

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimStoreService.factory.js#L275

The postmaster items are not getting their bucket set.

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimStoreService.factory.js#L436

When their current bucket is being generated, the item.bucket is undefined so it then defaults to "Consumables".  Dunno if that's the right way to deal with items that don't have a bucket; just dropping them into consumables.
