### ISSUE TITLE
DIM does not take into consideration the energy level of armour when selecting/adding mods 

### ISSUE THREAD

**Issue by Novoca1n3** [DestinyItemManager/DIM#6658]
You're able to select/add mods to armour whose total energy value exceeds the energy level of said armour. Total mod energy level should be <= armour level.

Armour energy level (left to right) however mods for each armour is 10
10, 9, 8, 9, 8

![DIM](https://user-images.githubusercontent.com/24946111/113957689-094a9880-9863-11eb-9742-39e681ec9b3d.JPG)

**Comment by ryan-rushton** [comment]
It is set at 10 because that is the max level of masterworked energy. If we were to do it to item energy level then armour pieces with only 1 energy but good stats would rarely be considered if you had a full mod loadout. 

The main issue is a balance between when people care about spending materials. Some users have so many ascendant shards they dont care about upgrading at all, others are willing to spend an enhancement prism or two.

What we need is a the ability to let users indicate what kind of materials they are willing to part with when considering energy requirements. Then if you are willing to spend legendary shards, we will assume 7 energy unless the item is higher.

The mod energy requirement is something on the roadmap in #6576.

**Comment by Novoca1n3** [comment]
So what's the point of the MasterWork button on the left then? Doesn't that force DIM to assume all armour is MasterWorked? If the only point of the LoadOut Optimizer page is to optimise stats for discipline, mobility etc etc then I understand what you're saying. i guess I saw the optimizer as a way to optimise my character from all perspectives ie equipping mods I'd like to use and saving as a template.

**Comment by ryan-rushton** [comment]
Initially we actually were using item level but we got a lot of feedback that it was too restrictive as per my initial comment. After that assume masterwork became a tool to purely increase the stats of all items so people can find the best set to spend all their mats on.

Yeah we want to move forward to it being more holistic and be more connected to actual loadouts but there is a lot of work involved in that and we all do this in our spare time. I am hoping to get a bunch of it done in the next month or two but I just have to see what happens.

**Comment by Novoca1n3** [comment]
Thanks for the explanation. Will close this off.

**Comment by ryan-rushton** [comment]
Just keep on an eye on what has gone into beta, I get right into build optimisation personally so I am hoping to get some stuff out that people find useful.

**Comment by Novoca1n3** [comment]
Cheers. DIM is definitely an awesome tool. Still able to customise mods etc a lot easier with it than in game.
