### ISSUE TITLE
Display a custom score based on armor stats

### ISSUE THREAD

**Issue by mlsof21** [DestinyItemManager/DIM#6833]
**Proposed change**
I'd like a way to quickly identify pieces of armor that don't have optimal stats by displaying a custom stat value for each armor piece on the inventory screen. I've done a rough draft (I'm no designer) on my forked repo:

![armor_score_vault](https://user-images.githubusercontent.com/8508338/121365916-48927580-c8f6-11eb-9ba6-0f72297a432e.png)

The number is a static calculation based on my own weighting system for each character (i.e., `3 * recovery.basestat + 2 * discipline.basestat + intellect.basestat` for warlock armor). Ideally, a user could add custom weights per character per stat. I've also added a search filter `armorscore:>##` and sorting option in Settings. 

The background color is determined from an array of colors in a gradient from `red` to `green` based on how low/high the score is.

I realize there is the `Custom Total` section in settings to sort of accomplish this, but this will present a very quick visual for the user that would help in the armor filtering process. I've only used it locally for a day, and it helped me out immensely.

**How does this fit into your workflow?**
With the amount of rewards given during/after an activity, my vault quickly overflows with pieces of armor that I'll probably never use. This would help me quickly evaluate a new armor piece and determine if I should keep/shard it.

**Comment by nev-r** [comment]
not gonna majorly address the putting-more-things-on-the-tiles here.. the general consensus is negative toward it in theory: [more] clutter is ehh. and tile view is for searching and dragging, not for judging. we have so many tools for judging.

<hr/>

regarding armor score, this has been tried a bit, the results so far are unsatisfying.

- the goal with stats is about your guardian's total. individual pieces can be great but only your overall numbers truly matter
- if it were extremely hard to hit a 100 at all, you might want to maximize every piece for just your favorite stat, but the fact is you don't have to collect forever before you start to see possible builds with mid 20s or low 30s in combined stat tiers
- so in choosing stats, it's about **balance** and optimizing for **multiple important stats**

.

- let's say we want to have some of stat `A` (*1), more `B` (*2), and even more `C` (*3)
- we do this with simple multiplication. 1 point of `C` counts for 3.
- on a long enough timeline this might work once you have a TON of pieces with maxed out `C`, and `B` starts being the tiebreaker
- but in the short and long term **it just favors things with really spiked `C`**
- we end up with a bunch of really abnormal armor, with non-ideal other stats, because it has good `C`

.

- the goal though, with this feature, is to establish a single **meaningful value to chase**
- the goal is a number you can say "well this is better than that" and maybe feel comfortable deleting the "that"
- so where this all goes wrong is that repeatedly keeping the best weighted armor piece, doesn't help you chase a similarly weighted total, you end up chasing a weirdly spiked total where you badly need to round out the other stats you care about

.

- this might just boil down to finding the right weights
- it could boil down to an algorithm that prefers stats but avoids huge spikes
- it could boil down to an algorithm that tries to find stats where the relative stat numbers are similar to the desired weights
- :woman_shrugging: 

.

- part of what's important is the end user understanding the output/value and how it got that way
- simple multiplication/averages/addition would be GREAT, if they didnt have the above problems
- it's less comfortable to dismantle something based on "DIM says a complex set of factors says this is bad"
- so a "black box" approach is less useful because it is less likely to make users feel comfortable taking action, so it doesn't save people time

.
this is not all direct feedback, just documenting what's going on in this direction. there's probably a custom stat editor coming that would support weights but doesn't use them yet. we'll see.

**Comment by bhollis** [comment]
Thanks for the detailed breakdown @nev-r. I'll close this in favor of the enhancements you're working on.
