### ISSUE TITLE
Transcendent Blessing mod missing from loadout optimiser

### ISSUE THREAD

**Issue by TheHandsomeCoder** [DestinyItemManager/DIM#6948]
**What version of DIM are you using?**
6.77.0

**What Browser and OS are you using?**
Chrome on Windows10

**Describe the bug and how to make it happen**
I was making a Last Wish loadout and expected to be able to add the two Transcendent Blessing mods I have but they are not available to select in the mod menu.

**Include devtools console logs**
n/a
![image](https://user-images.githubusercontent.com/1569604/128873916-fd1cf3c7-c5c0-4d3e-81d9-fecf9723db76.png)

![image](https://user-images.githubusercontent.com/1569604/128872808-c731ea82-7fe4-45e5-be8d-c92b5d5578e7.png)

![image](https://user-images.githubusercontent.com/1569604/128873804-c37fc4cc-419e-422c-808c-c59b9b337266.png)

**Comment by nev-r** [comment]
![image](https://user-images.githubusercontent.com/68782081/128912166-9169cbaf-4158-4947-9b89-19aee51ee91d.png)

transcendent blessing/riven's curse has always annoyingly followed none of the usual mod rules, so it's been difficult to keep it appearing in LO as bungie repeatedly revamps the mod system.

they live in the ubiquitous far left armor mod slot now, and can be applied to anything, not just reverie dawn/great hunt, so it's a very low priority since they aren't complicated to assign to an armor piece. so, unlikely to get fixed, we've actively decided through several LO iterations to just ignore them. but who knows. never say never :woman_shrugging:

**Comment by TheHandsomeCoder** [comment]
No worries, just wanted to flag it, it's not breaking or urgent :)

**Comment by bhollis** [comment]
Likely fixed by #6959 (by removing support for legacy mods entirely)

**Comment by ryan-rushton** [comment]
I think @nev-r is saying they live in the general mod slot but you need to have them in your inventory to be able see them. When we look for mods we only do so based off available mods for a given mod slot. I don't think these mods work that way so we would need special handling to be able to surface them.

**Comment by bhollis** [comment]
I don't think we're going to fix this.
