### ISSUE TITLE
Loadout Optimizer: Ability to show and sort by wasted stats 

### ISSUE THREAD

**Issue by eobert2493** [DestinyItemManager/DIM#6950]
**Proposed change**
For some of us armor nerds, we are always looking for the perfect stat distributions with no wasted stats. Like so:
https://cdn.discordapp.com/attachments/663244211671400491/874887669983895583/unknown.png

On the loadout optimizer, it would be nice to see a total wasted stat value next to your loadout. Stat values ending in '0' or '5' would count as 0 wasted stats as you can slap a minor & normal stat mods onto it. 

Example:
| Stat | Stat Value | Wasted Value |
| ----------- | ----------- | ----------- |
| Mobility | 60 | 0 |
| Resilience   | 43       | 3 |
| Recovery | 65 | 0 |
| Discipline | 77 | 2 |
| Intellect | 54 | 4 |
| Strength | 45 | 0 |

This would result in a total wasted value of 9 for this loadout.

Additionally, it would be nice to sort by total wasted stats. Currently sorting is based on the highest tier (which makes obvious sense), but wasted stat could be added as another sorting level (similar to the Item Display section under Settings).

![image](https://user-images.githubusercontent.com/50302290/128976760-60afe76d-89a2-4d33-be7b-eda61d9d6292.png)

**How does this fit into your workflow?**
This is somewhat of a trivial request. Functionally speaking, loadouts with wasted stats and no wasted stats will behave the exact same. This is more of a flex to show others your perfect build.

**Comment by nev-r** [comment]
i would do the "wasted stat points don't matter" speech but it sounds like you already understand that.
i am a huge fan of 0's too, and understand why you'd want to see 6 satisfying 0s. but:

because the LO checks all possibilities, the entire concept of "wasted points" is a bit misleading.
_normally_ a .9 might mean you're close to another tier, but LO already checked that and listed it, if it's possible to reach.

the point of LO is assuring you that we checked everything and is is the best you can manage,
so calling attention to "wasted" stat points would be against that, and kind of stress people out and cause unnecessary fomo
