### ISSUE TITLE
is:maxpower has a preference for vault items

### ISSUE THREAD

**Issue by jaramir** [DestinyItemManager/DIM#7011]
### DIM Version

Version 6.81.0 (release), built on 06/09/2021, 04:05:30

### Browser Details

Firefox 92.0b9 (64-bit)

### OS Details

macos

### Describe the bug

The search `is:maxpower` hightlights items in the valut even if there are items with the same light level in the inventory (either equipped or unequipped)

eg. 
Equipped 1320 boots
Unequipped 1322 boots
Vault 1322 boots

Searching for `is:maxpower` hightlights the vaulted ones. Tried to swap Equipped and Unequipped but still highlights the valuted ones.

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/225160/132184434-0f18c84d-8f81-462e-a382-aebba0a0efed.png">

Same for weapons:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/225160/132184567-186d0e53-ad8e-4482-89a9-5ab4dd7b3417.png">

The consequence of this is that the "Transfer search is:maxpower" will transfer to the inventory unnecessary items I could as well leave in the Vault.

Thanks!

**Comment by jaramir** [comment]
I think this is caused by the filtering for equippable which creates an interaction with the exotics in other slots.

`function calculateMaxPowerLoadoutItems(stores: DimStore[], allItems: DimItem[]) {
  return stores.flatMap((store) => maxLightItemSet(allItems, store).equippable.map((i) => i.id));
}`

If I understand correctly this makes "Transfer search is:maxpower" work the same way as "Maximize power"

<img width="365" alt="image" src="https://user-images.githubusercontent.com/225160/132188609-6fc11075-1100-49f4-8222-541143669427.png">

**Comment by bhollis** [comment]
I don't think your guess is right, but I'll take a look to figure out why it prefers items in vault.

**Comment by bhollis** [comment]
OK, I looked into this and maxpower has no preference for vault items. The preference for which item is selected when multiple are available is here:

https://github.com/DestinyItemManager/DIM/blob/a964cab0153975a6a3ac3f14d2eb300d3aa01289/src/app/loadout-drawer/auto-loadouts.ts?plain=1#L98-L117

What you're seeing is the fact that this is not the strictly max power items you have in each slot - it's the items that make up the maximum power *loadout* you could actually equip. Since you can only equip one exotic, it's selecting other items to make the highest max total power.

If you actually want the max power in each slot, that's a different feature request: https://github.com/DestinyItemManager/DIM/blob/a964cab0153975a6a3ac3f14d2eb300d3aa01289/src/app/loadout-drawer/auto-loadouts.ts?plain=1#L98-L117
