### ISSUE TITLE
Subclasses in Loadouts are not Equipping

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#702]
When applying a loadout with a subclass, the subclass will not be equipped if the loadout has to transfer an item to the character.

Create a loadout with one subclass, and one item.  It is important to recall which character owned the subclass you clicked on when creating the loadout.

Apply the loadout with the subclass to a different character of the same class.

The items will transfer, but the loadout will not apply the subclass.

If the character was the owner of the subclass that was added to the loadout, then it will equip if an item is transfered.

![screen shot 2016-07-19 at 12 16 55 am](https://cloud.githubusercontent.com/assets/984608/16939416/0ed200c0-4d47-11e6-81f7-3e454ca81a27.png)

![subclass](https://cloud.githubusercontent.com/assets/984608/16939421/1372108e-4d47-11e6-8481-b3a12f2345a8.gif)

**Comment by bhollis** [comment]
Hmm, my suspicion is that the subclasses for different instances of "hunter" or whatever are actually different items, to Bungie. Unfortunately I can't think of a good fix if that's the case. I also can't test any fix I would write, because I don't have two characters of the same class (and because moving items is boned right now...)

**Comment by bhollis** [comment]
@SunburnedGoose could you test my hypothesis by looking at the item IDs for those? My hunch is that it's like two Gjallarhorns - the same item, but different instances of it.

If that's the case, we could special-case class items to only look at their hash, not hash+id, sort of like we do with consumables (which is easier because their id is always 0...)

**Comment by SunburnedGoose** [comment]
That's how DIM transfered subclasses before your refactoring, by comparing them based on itemHash in the Loadouts transfers.  They were a special case.

https://github.com/DestinyItemManager/DIM/blob/v3.2.1/app/scripts/loadout/dimLoadoutPopup.directive.js#L288

In the `applyLoadoutItems()`, we would look for items that were `type='Class'` and instead of loading the pseudo by itemId, which is on the original character.   In this case, DIM would find an item on the target character that matched the itemHash.

**Comment by bhollis** [comment]
Then let's put that logic back.

**Comment by bhollis** [comment]
With a comment this time!

**Comment by bhollis** [comment]
OK, I think I fixed it. I can't test item movement on dev anymore, so I'm just pushing it so it'll go out in the beta and then you can tell me if it's really fixed (I don't have two characters of the same subclass).
