### ISSUE TITLE
Automatically add stat mods

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7090]
We should include stat mods in the calculation of stat ranges, based on the open slots. Then I guess if you request higher stats it can automatically add them or something.

1. Add to any stats until you hit the minimum
2. If any stats would go up a tier by adding a +5 mod, do that
3. Then fill up stats to the maximum, in order

**Comment by bhollis** [comment]
When we do this we should make sure to still prioritize builds that reach the desired stats "naturally" (with the fewest added stat mods).

**Comment by bhollis** [comment]
When I pick this up again (probably a rewrite), I think I'd like to change the algorithm to be:

Add to any stats until you hit the minimum
If any stats would go up a tier by adding a +5 mod, do that
Then fill up stats to the maximum, in order

**Comment by robojumper** [comment]
Status: I have a Rust-compiled-to-WebAssembly (WASM) implementation of LO that automatically assigns stat minimums at https://github.com/robojumper/dim-lo-process/ and a prototype for using it in DIM at https://github.com/robojumper/DIM/tree/wasm-lo.

TODO Checklist:

* [ ] Figure out a way to wrap the WASM FFI in a JS package and use that from DIM instead of copying everything into DIM. I have no idea how to best make webpack use a separate package with WASM.
* [ ] Properly define the API of that package. How many Destiny-isms (stat hashes, bucket hashes, plug category hashes) should it expose in its interface?
* [ ] Wire up the Loadouts autoStatMods property correctly. Right now they're shown in the generated sets but not used otherwise.
* [ ] Figure out the correct way to sort sets and design a way to give the user details about generated set stats. The implementation ignores the stat boosts from auto mods and also ignores any tiers going over a specified maximum, but the displayed sets do take all of these into account, which can lead to sets showing a "lower" total tier set higher than a "higher" total tier set and that's confusing.

**Comment by robojumper** [comment]
Status: Automatically adding stat mods to hit stat minimums in the JS loadout optimizer was implemented in #8605 and it seems to perform relatively ok-ish performance-wise. A natural-feeling extension would be adding stat mods according to stat priorities beyond the required minimums, which has been requested a bunch of times, but I've previously said I have no idea how to manage complexity-wise, so let me elaborate on that. First I need to explain the complexity of the current problem though:

The heart of the issue is that LO also always assigns combat mods and thus has to check combat mod permutations (up to `5! = 120`) and for each permutation a different seqeunce of remaining energy capacities is available, so for EVERY armor set, for EVERY permutation of combat mods, LO needs to check for the feasibility of picking stat mods to hit the required minimums. The work in #8605 was essentially making that last step relatively cheap, and when the assignment is easy to find, the combat mod loop can make an early exit. And when the armor is energy-constrained, the greedy approach seems to reject infeasible assignments quickly enough.

Some more comments about the current implementation can be found in https://github.com/DestinyItemManager/DIM/blob/01a82805a869c1aa05817e3fbdf3cbb2fd3bcb20/src/app/loadout-builder/process-worker/auto-stat-mod-utils.ts

I believe for this feature DIM must always find a possible mod assignment if there is one. DIM isn't the only site with this feature and when users see site A generate 391 sets and DIM generate 27 sets, then what's the point in using this feature in DIM?

To illustrate the combat mods problem, these settings are a good starter for a stress test:

![grafik](https://user-images.githubusercontent.com/14299449/195435655-ec57cf7f-b9ba-40ef-a896-0e3d591c2dd4.png)

because the locked element, different mod elements and costs will cause LO to not group class items (multiplying number of sets by 4) and create 125 combat mod permutations (though with no other mods picked, auto mod assignments are usually either trivially feasible or trivially infeasible, so some bucket specific mods should be played around with).

A necessary consequence is that currently, **LO ignores stat contributions from auto stat mods when sorting sets**. This is because sets that require many mods to hit the minimum stats will actually end up with a much higher stat tier simply because LO picked additional mods, and sorting by the resulting stats would be backwards -- we want to show sets that naturally hit the minimum stats!

This of course would not be necessary if LO always just picked the objectively (as in, defined by some objective function) best set of mods, because all sets would benefit from additional stat mods, but this is a relatively difficult thing to implement an efficient algorithm for. Here are some approaches to solve this problem:

1. "Simply" find the objectively best assignment at *process time* (i.e. in the process worker, for all of the *millions* of possible armor sets). Come up with a fantastic algorithm and/or integrate an external solver. I can't come up a solution that does this efficiently for millions of sets, and haven't found relevant literature to map our problem to an existing well-studied optimization problem (at the very least, it's not a linear problem because 1 +5 mod does nothing about half of the time while 2 +5 mods always do something).
2. After finding a feasible assignment for minimum stats, use a heuristic and pick some stat mods at process time. This might be worth a shot but I don't like heuristics, and the moment someone looks at a generated set and notices an obvious way the assignment is not objectively optimal, the feature may leave a bad taste. Users already think DIM is malfunctioning if it suggests a change of class item element type they consider unnecessary!
    1. A heuristic also means our set sorting might be bad again -- there might be good sets that the heuristic failed to pick the good mods for and that set just goes missing and isn't in the 200 returned sets.
3. Keep the LO process working as it is working right now, and instead assign auto stat mods *at render time* (i.e. only for the 200 sets returned from the process worker).

Personally I think 3. is the most promising. This was actually already suggested by @ryan-rushton in #7262 but considered "a lot harder" than initially thought:

> I think it would be better to do this at render time rather than in process. Reason for this is if we do it here we lose the ability to exit early when we find any combination of mods that will fit (that is what canTakeSlotIndependantMods does)
> [...]
> As discussed outside this, the issue is a lot harder due to correct sorting of sets.

The trouble is that if we did all of auto mod assignment at render time, then there's no guarantee that any of the first 200 returned sets could actually fit enough mods to hit the stat minimums, so the algorithm could plain say there's no result when there in fact are feasible solutions, because the stats where we would need mods are down in the stat order.

So what I think would be promising is keeping the minimum stats check in the process worker, but do stat optimizing beyond minimums at render time. This means we don't have to do that for a million sets, but instead only for 200 sets, and the algorithms could be a lot more . The downside of course is that we might miss sets that could fit more stat mods than the first 200 sets, but this is quite unlikely because armor with a lot of energy capacity tends to be masterworked and already has good stats, but I tell LO all my armor is masterworked anyway. So maybe this is more of a downside for users without tons of golfballs?

Anyway I just felt like writing this down to explain what the sticking point about picking all and any stat mods according to stat order is, both in order to discuss our various options and to provide a starting point in case someone wants to tackle this.
