### ISSUE TITLE
We can no longer compare archetype without the slot filter

### ISSUE THREAD

**Issue by RenierZA** [DestinyItemManager/DIM#7101]
### Proposed change

For example (Succession):
![image](https://user-images.githubusercontent.com/1150349/135236845-a32bc90a-fd0b-4529-aad1-503a7263c57d.png)

We used to be able to select all Aggressive Frame snipers, ignoring the slot.

Please add a button for archetype only.

### How does this fit into your workflow?

When deciding to keep a weapon, sometimes it's useful to know if you have others of the same archetype even if it's in the other slot.

**Comment by bepoli** [comment]
I think the new filter is more useful than the previous, but having both shouldn't hurt.
It would be ideal if we could combine filters together, let's say if we had two buttons, one for element type and one for archetype, and just select them both to obtain the combined filter. I don't know if it's too much hassle to implement, though.

**Comment by nev-r** [comment]
> When deciding to keep a weapon, sometimes it's useful to know if you have others of the same archetype even if it's in the other slot.

i don't really think so, which is why that option didn't make the cut. the buttons had gotten way out of control size-wise, taking up a lot of space, taking up several rows, etc. so we had to narrow the options somewhat

you need "at least one void sniper and one kinetic sniper", far more than you need "at least one aggressive sniper".
frozen orbit and occluded finality compete directly for equippability in a way that frozen orbit and succession never will.
having 1 in kinetic slot and 1 in energy, and keeping only the energy, will severely limit your loadout options. so element comparison takes priority.
happy to hear why you disagree though

**Comment by RenierZA** [comment]
I agree the current selection is better, but it's a pity the other option is gone now.  My vault is always overflowing, so sometimes I have to restrict copies of an archetype I keep.

A more advanced drop-down button with all the options would be nice.

But I can certainly live with the current buttons. Just a nice-to-have request, I guess.

**Comment by nev-r** [comment]
definitely! there's a more customizable set of dropdowns coming to Compare in the future.
and a workaround right now might be this:
![image](https://user-images.githubusercontent.com/68782081/135335476-e58604f9-ad03-4337-9349-76b8592eafd4.png)

( this stuff autocompletes with s n i [tab]  a g g r [tab] )

**Comment by RenierZA** [comment]
I did not know about that "Compare Items" menu.  (Since most searches are usually across different weapons, so it's greyed out.

That solution will work for the rare occasion that I need this.

Thank you very much.

**Comment by bhollis** [comment]
Be sure to check out the Organizer as well, which is intended for this sort of super flexible slice-and-dice to choose which item to keep.
