### ISSUE TITLE
Weighted custom stat

### ISSUE THREAD

**Issue by geevensingh** [DestinyItemManager/DIM#7120]
### Proposed change

The custom stat feature is binary - either you care about a stat or you don't.  But if it could be weighted, then it could be much more granular and then more useful.

The query engine and display of custom stats wouldn't have to change at all.  But there would need to be some new settings UI to set the custom weights (presumably for each class).

### How does this fit into your workflow?

For example, imagine a warlock cares most about intellect and recovery but they still care a bit about discipline and strength and hardly at all about mobility.  If they could set up weights for stats (like 1 for int and recov, 0.5 for disc and str, and 0.1 for mobi), then there could be a single value that would help them decide whether to keep gear without completely ignoring some stats.

**Comment by nev-r** [comment]
it's in the cards, just. it's important that it be helpful in collecting armor. see here for more info https://github.com/DestinyItemManager/DIM/issues/6833#issuecomment-860134547

**Comment by geevensingh** [comment]
You say "it's in the cards, just" but it seems to be quarriable as well with something like "basestat:custom:>20", for example.  Or did I misunderstand your comment?

As for your comments in issue #6833, respectfully, I'm not sure I agree with your analysis. You say:
> let's say we want to have some of stat A (*1), more B (*2), and even more C (*3)
we do this with simple multiplication. 1 point of C counts for 3.
on a long enough timeline this might work once you have a TON of pieces with maxed out C, and B starts being the tiebreaker
but in the short and long term it just favors things with really spiked C
we end up with a bunch of really abnormal armor, with non-ideal other stats, because it has good C

So yes, obviously this will prefer gear with large values of C.  But - with your example weights - one point of A and one point of B will be equivalent to a point of C.  So items with 5/5/10 and 10/10/5 will have an equivalent custom score.

This feature is not meant to replace the loadout optimizer _at all_.  But lots of people use DIM to know what they should keep around because it _might_ be good... because it _might_ go in a loadout in the future.  And having a custom gear score is a nice, high-level way of quickly knowing if the gear works for them or not.  And being able to write a simple query against basestat:custom means that filtering/tagging/moving particularly good (or bad) gear becomes much easier than complex queries like: -((basestat:intellect:>14 basestat:recovery:>17) or basestat:intellect:>20 or basestat:total:>61) is:armor is:warlock -is:classitem
(which is an actual query I use myself)

**Comment by nev-r** [comment]
> You say "it's in the cards, just" but it seems to be quarriable as well with something like "basestat:custom:>20", for example. Or did I misunderstand your comment?

i don't understand

> So yes, obviously this will prefer gear with large values of C. But - with your example weights - one point of A and one point of B will be equivalent to a point of C. So items with 5/5/10 and 10/10/5 will have an equivalent custom score.

ssssssss... i think? what is the "but" here? what is the argument?

> This feature is not meant to replace the loadout optimizer _at all_.

i don't understand what this has to do with anything

> complex queries like: -((basestat:intellect:>14 basestat:recovery:>17) or basestat:intellect:>20 or basestat:total:>61)

weighted custom stats cannot precisely replace this query at all

**Comment by TiemenSch** [comment]
I think his query means to filter out some lower totals with some spikes in preferred directions. 

The power of this feature using multiplication only (e.g. integers) would mean you can get fairly accurate. 

For example, I have thought starting off with the costs of slapping on a +10 mod as the "quality" each stat contributes: 

3 * mobility
3 * resilience
4 * recovery
3 * discipline
5 * intellect
3 * strength

The absolute value does mean rather little and naturally you **could** normalize to a quality percentage by dividing with the sum of the multipliers (meaning your custom "total" would end up around 60-70, too). I would like to use this as a baseline since the sandbox is perpetually changing.

The funny thing is, if you would multiply it with your desired final tier levels, you would actually predict your "best average" armor minus some RNG that would need the loadout optimizer to puzzle the right pieces together. I know you can use "specialized" armor single-spec pieces to obtain your tiers, too. But on average, it would constitute a useful filter IMHO.

For instance, I might be interested in this for myself as a Titan main in the live sandbox. 

1 * mobility (more of a tie-breaker, I almost couldn't care less)
60 * resilience
100 * recovery
80 * discipline
60 * intellect
30 * strength

**Comment by dmfigol** [comment]
Would love to have this feature. Comparing gear is one of my primary use-cases for DIM.
Currently I use the custom total based on stats selected in organizer:
![image](https://user-images.githubusercontent.com/1923704/175778069-c3ebee6a-834a-45c1-aad0-86320d99e394.png)
however, I currently value mobility + resilience on hunter more than discipline and strength (though I do care about them) and if I could assign weights stats resulting in more granular custom total, that would be amazing help for my needs.
