### ISSUE TITLE
'Show Mod Placement' places some mods in less than optimal places

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#7198]
### DIM Version

Version 6.88.1.1000808 (beta), built on 10/29/2021, 8:40:00 AM

### Browser Details

Version 96.0.4664.18 (Official Build) beta (64-bit)

### OS Details

Windows 10

### Describe the bug

I have setup a loadout on my Hunter with 'Powerful Friends' specifically on my arc helmet which is a raid helmet and it has the extra modslot for slotting an arc mod with 1 cost.  This is so that I can get the +20 mobility wihout using another arc charged with light mod on another armor piece.  When I click the 'Show Mod Placement', DIM randomly assigns the mods to my armor pieces but puts the 'Powerful Friends' mod on the leg armor which doesn't have the extra raid mod slot.
![2021-10-29 16_39_12-DIM](https://user-images.githubusercontent.com/6478196/139371871-e1ff32f8-cd83-42b2-9034-e1b8d9e62420.png)

Also another issue is that the Mobility stat is showing as 142 which is way too high.  It should be 102.

**Comment by ryan-rushton** [comment]
Yeah I would have never thought of that. I will need to do some tweaking to the algorithm that assigns mods. At the moment I am optimising for minimum number of wasted mods, i.e. mods that fit into anything. We need to create some rules to compare two sets so that we also activate mods with conditions like this. Unfortunately that probably means hardcoding some rules to do it.
