### ISSUE TITLE
Lost all tags and notes

### ISSUE THREAD

**Issue by DanishAce** [DestinyItemManager/DIM#7282]
### DIM Version

Version 6.91.2.1000858 (beta), built on 11/17/2021, 12:50:19 AM

### Browser Details

Edge 95.0.1020.53

### OS Details

Windows 11

### Describe the bug

I did not check if my tags and notes were available before I checked my D1 items, but when I came back to D2 items, I discovered that all my tags and notes were gone.
I have tried to restart DIM using it as an app from Edge, and I also signed out, then back in, but with no luck :-(
Do you know what can make this happen, so I don't do it again, this is a pain in the bud, as I have a full vault and have marked all my items for keep, favorite, archive and infuse + notes on several items.
All my settings are fine and has not been messed up.

I am a Senior software developer myself, and I don't do silly mistakes, and I am sure I did not do anything for this to happen.

Best regards,
Bill

P.S.: I closed DIM several times after the issue, so the logs are not there anymore, sorry.

**Comment by bhollis** [comment]
Thanks for the info! Folks have occasionally complained about this, but haven't been able to provide enough detail to identify the bug. However, I am now able to reproduce this as a race condition when switching accounts. To avoid this until the bug is fixed, please do not switch accounts while data is loading (the spinner is spinning).
