### ISSUE TITLE
Screen rotation not working

### ISSUE THREAD

**Issue by Jaz54-Cloudwalker** [DestinyItemManager/DIM#7558]
Hi for the last couple of times that I've used DIM (beta) the screen rotation is not working it opens up in portrait mode.
I've checked the settings on my tablet and its set to allow screen rotation.
Normal version of DIM is working perfectly. Has a setting been added that I'm not seeing?
Regards
Jaz

**Comment by bhollis** [comment]
@Jaz54-Cloudwalker can you please fill out the info for the bug report template? Browser, version, etc?

**Comment by kyleshay** [comment]
Maybe we just remove that prop from the json manifest entirely? Sorry about that. Sounds like maybe the default/fallback varies browser to browser or something?

**Comment by Jaz54-Cloudwalker** [comment]
Chrome 96.0.4664.104
Android 8.1.0
Lenovo TB-X304F Build/OPM1.171019.026

**Comment by CrashPro1** [comment]
Same issue,  hence finding this github. 
Samsung Tab S6 Lite
Android 11 UI 3.1
Edge 96.0.1054.62
Chrome 96.0.4664.104

Use same browsers on my phone (Samsung Note 20 Ultra) which is also a stylus enabled device running same version of Android. This doesn't make sense to because it rotates as expected on my Note, so I expected Tab S6 to work too given they're practically the same.  

Rotates as expected while in actual browser. Installed version is forced portrait mode.  Unable to even add shortcut to functioning browser page to home screen since it reverts to "install" version.  

Even opening installed app while in manually locked portrait mode, DIM overrides it and even changes drop down menu function,  despite the icon still showing the locked Horizontal landscape icon.  Screen switches back to landscape as it should be when leaving DIM app.

Noticed Edge had a setting to open new tabs in desktop mode by default, changed to mobile and still didn't fix issue.  Couldn't find similar option in Chrome.  

Tablet is brand new, so this is first time using these browsers and trying to use DIM on this device. However, it worked on a previous tablet I had a couple years ago (although still using same browsers and have been long time Beta user, especially since I realized tags didn't sync across versions. May be changed now but stopped using standard DIM years ago for this reason).

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/issues/7506 you might need to uninstall / reinstall

**Comment by CrashPro1** [comment]
> 

Don't have normal "Uninstall" other than simply removing the icon for the app, but I've done that 2-3 times from each browser, even removing cookies and such in between. 

To be safe,  I uninstalled edge altogether, made sure open in mobile was set by default first,  then installed again and same issue.

**Comment by bhollis** [comment]
Tags sync between beta and app

**Comment by bhollis** [comment]
Can we get an update on this? It's still a pretty common complaint that landscape rotation no longer works.

**Comment by CrashPro1** [comment]
> Tags sync between beta and app

Thank you for the update on this. Hence why I was sure to detail it has been several years since trying because I had a feeling that may have changed, especially with the new integrated syncing that was added awhile back.

**Comment by CrashPro1** [comment]
Thanks for the fix!  Confirmed rotating now as expected.
