### ISSUE TITLE
RFC: Remove spreadsheet export

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#756]
I like the idea behind the spreadsheet data export, but @wein3967 [still does his own thing](https://www.reddit.com/r/DestinyItemManager/comments/4whrgg/updated_dim_export_script_color_and_category_fix/) and I suspect this feature is so niche that it has few users (and those that would use it have enough special requirements that they'd be better off doing their own thing, like @wein3967 does). My worry about it as a continued inclusion in DIM is that we'll never test it, so we will likely break it without knowing.

/cc @dcaslin for comment

**Comment by wein3967** [comment]
I like the spreadsheet export, personally, as well. The only real reason I continue to maintain my script is because it allows to me keep track of decisions I've made regarding various items (e.g. keep, infuse, store). I can't trust lock states, since I swear they change on their own sometimes. If DIM supported common tags, notes, or custom tags that persisted on items, I could move away from the script. I wouldn't advocate removing the current feature, but I would understand based on the actual user base.

**Comment by SunburnedGoose** [comment]
As long as it is maintained, I'm fine with it.  There are those who enjoy having an export of their items and this fits that use case.  If we get error reports from users regarding this feature, and no one updated the service, then I would support removing it from DIM.

**Comment by dcaslin** [comment]
I'm not sure of a good way to unit test it reliably offhand, eyeball testing is pretty easy though as when things go wrong entire columns tend to show it (typically empty). Full disclosure, much like @wein3967  I don't actually personally use this feature myself since I have a more customized extension I wrote for tagging and spreadsheet stuff. 

From a bigger picture perspective, two questions: 

1) I thought I met someone that was volunteering with QA help, are they any test scripts that folks are running through pre release? If so, adding an "eyeball the spreadsheets" would make sense.

2) I see hooks to Google Analytics in DIM, doing something like sending [GA custom events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) during these functions would probably be a really good idea. I assume right now we're just a couple folks speculating about the usage patterns for the broader DIM audience. I imagine such a function is best implemented by someone with access to the GA account to make sure it works. With that data in hand I'd suggest the obvious, if almost no one is using it, nix it (or consider upping it's visibility to users), if it's widely used keep it. In lieu of that data, an informal poll on the subreddit or Twitter might be useful. With the GA it would be really cool to know how often people are using, for example, the T-12 optimizer.

**Comment by kyleshay** [comment]
I'm wondering what else is stopping you from using the tool in DIM. If we did implement #471 (Tags and notes on items) would the export tool be better (would you still need an export script, since it seems you're exporting currently because you want tags + notes on items?)

Guessing in excel it's easy to compare, sort, an filter items...

**Comment by dcaslin** [comment]
@kyleshay Are you asking me? It's really a very different UI sorta like an interactive spreadsheet. If you haven't tried it, try it https://chrome.google.com/webstore/detail/destinychecklistnet-gear/feapilfcgikmmcdhledhnaefdjjfdomm

I'd say I use mine 30% and DIM 70%, I almost never use straight Excel sheets (namely b/c I've tweaked my own extension exactly how I like it, the value for Excel, IMO is that you can customize it however you want; so I'm sure it's much more valuable to someone that isn't able or willing to build their own). What are my uses cases for that 30%?

1. Tagging. Every week I'll go in and search on unmarked items and go through and mark them. Then I trash all the stuff marked trash and look about combing things marked for infusion with things marked for upgrade. Finally I go through my "Keep" items slot by slot to see what I no longer need to keep (perhaps I just got a 100% arc bonus shotgun bonus Warlock chest piece, this making my poor 95% roll of that expendable; so i mark that for infusion fuel instead).

2. Differentiating like items. I still have about 20 grasps from the farm. In DIM it's quite tedious figuring out which is which. Tagging would help with that, but also seeing and sorting on stats help (my best GoM has the highest stability, so I can sort the table on stability and see it; I also added a text note to it saying "USE THIS ONE")

3. Min maxing stats. I just read an article arguing that range is the most important stat on hand cannons, so I'll filter by "Hand Cannon" and then sort by range to see what I've perhaps been ignoring.

4. I'll often use the above with DIM's loadout tool to equip things perfectly then hop over to DIM and do do the one-click "build loadout from equipped" thing.

So to completely obviate my extension I'd probably want to see DIM offer tagging AND a completely different tabular UI option. Though that slick sidebar item properties feature might also help a lot (having to hover over an icon to read a perk text bugs me).

The other, totally personal thing for me, is that I don't particularly like Destiny's aesthetics outside of the game (dark and icon heavy). I prefer the cleaner white interface, in fact I only added the weapon icons later after someone requested them. In this, I suspect, I am very much in the minority so I wouldn't suggest even considering changing anything like that for DIM (unless you wanted to look into theming/skinning; but the support and testing probably isn't worth it IMO)

**Comment by wein3967** [comment]
@kyleshay

All in all, my use cases are similar to @dcaslin. I use DIM about 90% and my spreadsheet 10%. I don't need my spreadsheet for T11/12 planning anymore, since DIM does a much better job. I really just use my spreadsheet for tagging/notes on items. Just like @dcaslin, every few days I do a dump and tag new items as Keep, Store, or Trash. Like-wise awhile back I had 4-5 PDXs sitting around. In spreadsheet form it is much easier to compare perks of similar items. Finally when I am not in front of my console, it is nice to be able to make a list of some in-game decisions for later (e.g. junk Comedian at Postmaster to make room for Her Memory. Pull class item on Alt2 to infuse into Witness mark).

So, yeah, nothing really new to add that hasn't been brought up before: Tagging/Notes, and potentially an option to view everything or just filtered items in a spreadsheet-like UI.

**Comment by bhollis** [comment]
Closing - we get enough bug reports that it's clear people are using this.
