### ISSUE TITLE
Filter Masterwork plugs based on plugCategoryHash, of currently inserted masterwork

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7575]
![image](https://user-images.githubusercontent.com/4798491/147514642-ffb95ab2-baca-4198-85cd-2b54d6016c06.png)

![image](https://user-images.githubusercontent.com/4798491/147514692-a31d17c5-1b77-4e4b-843e-1b504fc9c225.png)

with a sort on iconWatermark via d2ai possibly

**Comment by bhollis** [comment]
That'd be great!

**Comment by robojumper** [comment]
Filtering in the popup itself should be pretty easy based on the approach in #7660, but filtering to higher-tier versions of the currently applied masterwork only makes sense for instanced items -- in the armory, for example, we'd want to show all valid masterworks for this weapon type. And it might make sense to show these too for instanced items?

However, determining the valid masterwork stat hashes for items seems to be non-trivial because the info doesn't appear to be in the manifest or API (stats are wonky anyway... https://github.com/DestinyItemManager/DIM/blob/89b13c5ef7261b084944393dfb2f179e2af3acb5/src/app/inventory/store/stats.ts#L157-L183)
