### ISSUE TITLE
Share subclass config in loadout

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7592]
We can configure subclass in LO and Loadouts now, but because they're not part of LoadoutParameters they aren't shared with build links. 

I'm sorta thinking we should switch to sharing the entire loadout and then puzzling out what we can reuse on the viewer's side. I had intended for LoadoutParameters to encode the item-independent pieces but I'm not sure that scales.

**Comment by ryan-rushton** [comment]
Since subclasses have special handling maybe its worth splitting them out of items entirely. This would make it easier to include in shares and we wouldn't need to "find, then find the correct one for the store, then filter out of items" each time we want to do something with it. We could just save the hash and socket overrides.

**Comment by bhollis** [comment]
Linking #7929
