### ISSUE TITLE
Loadout Organization

### ISSUE THREAD

**Issue by ghost** [DestinyItemManager/DIM#7663]
### Proposed change

I would like a feature where I could categorize loadouts into folders/categories for better organization and convenience.
Thinking along the lines of just opening the character dropdown menu and then adding another collapsable layer to the builds. So instead of this:
![image](https://user-images.githubusercontent.com/94243772/148211835-31edabab-8a4c-422e-b935-f8e357f7c398.png)
We'd have customizable folders/categories like this (excuse the awful illustration):
![image](https://user-images.githubusercontent.com/94243772/148213935-c30c0444-5088-40c0-8c6f-b14504716cf1.png)
The left side shows how the current system functions which could definitely stay and be supported and the right side shows my idea. Maybe there could be subcategories too but that's not really a dealbreaker.

This would avoid a lot of the clutter with builds and incentivize creating more due to it taking up less space in the list.

### How does this fit into your workflow?

An example would be having multiple builds for let's say Ophidians but separate ones for HC+Sniper, separated for 6v6 and 3v3, an Ophidians build for a specific shotgun build, you name it.

It would be great if I could put these into a category of their own without it instantly taking up 10 lines the moment I open up the character dropdown menu. Currently, the lack of this feature is the biggest thing preventing me from creating more builds, a simple list just introduces way too much clutter with a high number of builds saved.

**Comment by bhollis** [comment]
Have you tried switching to sort by name, and then giving them common prefixes so they group together?

To be honest, it's super unlikely we'll add "folders" or anything like that.

**Comment by inexorableAce** [comment]
yeah I dunno if folders is the answer but I do agree that at some point we will need to solve the issue OR make loadouts a lot more complex to handle these scenarios. as it stands with mods and now looks... things are gonna get blown out FAST even for a modest loadouter like myself my character drop-down is almost full screen

**Comment by bhollis** [comment]
I'm open to non-folder ideas for sure

**Comment by zacgoodwin** [comment]
How about tagging loadouts with the ability to filter them on the loadout page?

**Comment by bhollis** [comment]
You can already filter them

**Comment by Korrasera** [comment]
Folders would add a 2nd axis to the visualization, so if it's the aesthetic of folders that you want to avoid, is there another way to add a 2nd axis to display loadouts with?

Three ideas that come to mind:

1) A mode selector switch that can be toggled between two or three states, each state having a different loadout list. Not sure if this idea is workable though, it adds more complexity to the inventory page.

2) An option to expand the loadout picker into a double or triple wide size, based on your display. Obviously this wouldn't help much on mobile, but mobile devices handle long lists very easily because they're based around scrolling, whereas a tablet or desktop display could afford to go big and chonky on the loadout picker.

3) Illusion. Add a selector to loadouts that let you preference them for the 1st, 2nd, or 3rd order sort priority. In settings, you add the ability to rename the 3 buckets. The loadout picker then displays each group in order. This would effectively extend the alphanumeric sort already being used by adding a new bucket sort to it, which would give you a 2nd axis without significantly changing the current UX and without requiring additional visual elements.

Bonus Suggestion: If buckets are a workable idea, then adding a small line separating each bucket would make them more visually distinct as well.

**Comment by bhollis** [comment]
Try out the new UI in Beta (make sure to add hashtags to your loadouts) and let me know what you think.

**Comment by Korrasera** [comment]
The hashtag loadout filter pills are really good and I do have some thoughts.

-

Filtering by hashtag is really easy, so that's a big plus. This really adds dimensionality and makes the feature easy to use.

-

The pills don't look like they integrate with the DIM look very well, but I assume that's because the look and feel will get tweaked once the feature gets finalized.

-

Adding hashtags to the titles is functional, but somewhat cumbersome. It increases the clutter of the name, and you can see the hashtags in the title of the loadout, even on the dropdown picker. That could be avoided by making the loadout picker not display the hashtags in the dropdown, or alternatively moving the hashtags to their own field on the loadouts themselves.

-

I think that the feature needs an option to default to a restricted view rather than a comprehensive one, so that I'm not opening the loadout picker and clicking a hashtag every time I want to change loadouts, since that just adds another click to the current functionality. Right now, if you click on a hashtag to filter, and then close the loadout picker and reopen it, it's back to an unfiltered list.

Three options could achieve this, off the top of my head:

1) Default to filtering out anything with a hashtag, so that the default unfiltered list exempts anything that's tagged. Functional, but not particularly intuitive, because it trains an unobservant user to expect that adding a hashtag renders that loadout invisible.

2) Make the filters sticky, so that if I want I can leave my loadout picker set to always show [#pve #pvp #raid] if I want. I think this option is much better, personally, but I think we can do one better.

3) Give the filter pill three states that you can choose between by clicking it. Off, Include, Exclude, and each state is sticky. This could be represented by a glow and an inverse glow on the buttons, or some other sort of visual artifact. As an example, if I left it set to [+pve +pvp -archive] it would show me the pve or pvp tag but exclude any that also have the archive tag and it would show that to me every time I open the dropdown picker.

I think #3 is the best option. I could easily just set it to -archive and leave it like that, or build a filter that's much more complex.

**Comment by inexorableAce** [comment]
Re: fit the look
Filer pills have been a part of the DIM UI for years now... this is a reused component. 

Re: tags should have their own field
They do! Tags are meant to be added to the notes field, not the name. If they work there that's just base covering.

**Comment by Korrasera** [comment]
Thanks, I honestly can't remember the last time I saw the pills pop up in the UI, so they seem oddly out of place.

And thanks, I completely ignored the notes field. That renders item 3 irrelevant.
