### ISSUE TITLE
Support number ranges, nested parentheses, and comments in the filter syntax

### ISSUE THREAD

**Issue by ahydronous** [DestinyItemManager/DIM#7670]
### Proposed change

**Number ranges**
Current workflow:  `(basestat:recovery:<13 or basestat:recovery:>25)` for finding armor pieces with less than 13 or more than 25 Recovery.
Proposed workflow: `-basestat:recovery:[13,25]` (take note of the negator at the beginning).

**Nested parentheses**
Current workflow:  `((basestat:resilience:<4 or basestat:resilience:>10) and (basestat:recovery:<13 or basestat:recovery:>25)) or ((basestat:discipline:<13 or basestat:discipline:>25) and (basestat:strength:<6 or basestat:strength:>15))` has the same result with or without the outer parentheses.
Proposed workflow: the above query now respects the outer parentheses.

**Comments**
This is more of a nice-to-have, but it would be nice to be able to put `#my_comment#` at the beginning of a search, so that if I bookmark it I can recognize instantly what it is for. Currently I have this jerry-rigged with `-id:my_comment⦘  `

### How does this fit into your workflow?

These two changes would allow for extremely fine-grained searching throughout the vault, meaning you can set up a range search with double parantheses, bookmark it, and periodically delete all armor that doesn't have a combination of your proposed stat ranges.

**Comment by robojumper** [comment]
I take it "without the outer parentheses" means `(basestat:resilience:<4 or basestat:resilience:>10) and (basestat:recovery:<13 or basestat:recovery:>25) or (basestat:discipline:<13 or basestat:discipline:>25) and (basestat:strength:<6 or basestat:strength:>15)`? Are your sure your parentheses are being ignored? From a cursory look at the query parser, that query is equivalent to the one with more parentheses because the explicit `and` has a stronger binding power than the explicit `or`, while the explicit `or` has a stronger binding power than the implicit `and` between two search terms.

I don't see it documented anywhere, so it'd be nice to document that behavior.

https://github.com/DestinyItemManager/DIM/blob/f4f4594c74324eff3afd67f1f33cfdd45b00cbc9/src/app/search/query-parser.ts#L107-L121

**Comment by bhollis** [comment]
Overall I'm wary of adding more syntax to searches unless it provides a capability that's impossible today. Searches are a very niche power user feature, and folks who know how to use them can build and favorite longer searches.
