### ISSUE TITLE
Loadout optimizer: can't select subclass other than Shadebinder.

### ISSUE THREAD

**Issue by kosmiciatakuja** [DestinyItemManager/DIM#7709]
### DIM Version

Version 6.98.0.1001173 (beta), built on 1/9/2022, 6:44:33 PM

### Browser Details

Chrome Version 97.0.4692.71 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

When I click "Select subclass" in Loadout Optimizer, the only subclass listed is Shadebinder. Nothing happens when I try to search, for example for "voidwalker" or "void" or anything. The only subclass listed is Shadebinder. 

Here's a screenshot if needed: ![screenshot](https://i.imgur.com/b3Tb0zE.png)

Opened devtools but nothing new appeared in console after clicking "select subclass".

**Comment by bhollis** [comment]
It is the only subclass you have that has "mods" that can affect stats. The Light subclasses haven't yet been moved over to the new system. So there's not much point in configuring them as part of Loadout Optimizer because it won't change your build. But you can add any subclass you want from the normal loadout editor.

**Comment by ryan-rushton** [comment]
Yes this is intentional, with the say I have built it, when the new subclasses become available they should "just work".
