### ISSUE TITLE
Weapon/armor comparison tool

### ISSUE THREAD

**Issue by SnowWolf75** [DestinyItemManager/DIM#772]
As my vault and inventory full up, I find the needs to compare items and remove the junk. Say, for hand cannons you like Impact, but also want a decent reload. A table to show all items of a type, giving you a quick way to compare and triage your options, would be ideal.
It's a definite change from what DIM currently is, but if I could fork the project and use the back-end stuff (CSS, login, style, etc), then maybe it could be merged back in an a module within DIM later?

**Comment by kyleshay** [comment]
If it helps, have you tried checking out the export to spreadsheet button in the settings dialog?

other than that we do have some thoughts at issue #494 on what we might want to do in that area.

eventually we'd like to work in tags + notes on items so that users can determine what things to get rid of.

**Comment by SnowWolf75** [comment]
Oh yeah... I also see some talk in #515 too.

**Comment by kyleshay** [comment]
I'll close this one then in favor of those two. Feel free to move some discussion there. 

Until DIM has something like that, feel free to check out this tool by @dcaslin: https://chrome.google.com/webstore/detail/destinychecklistnet-gear/feapilfcgikmmcdhledhnaefdjjfdomm

It's quite a bit more useful for comparing things! :)
