### ISSUE TITLE
Wish Lists: recommendedPerks is not iterable

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#7723]
### DIM Version

Unknown 

### Browser Details

Chrome

### OS Details

Windows

### Describe the bug

A player is reporting an issue using DIM with the following error message. 

t.recommendedPerks is not iterable. 

![B53E9A97-68B0-4C92-A162-2C32226FCD91](https://user-images.githubusercontent.com/984608/148893989-755c26dd-45e5-4c27-8cff-100c0236c789.jpeg)

**Comment by bhollis** [comment]
Not enough to go on, unfortunately. This has something to do with Wish Lists (do they have a bad wishlist?) but there's no matching report in Sentry and we have no logs.

**Comment by MENtos224** [comment]
i have the same issue as well. It was working fine yesterday and suddenly after i finished my trials game dim just stopped working and i kept getting this error code. tried logging out and back in and still no use.

**Comment by delphiactual** [comment]
what wishlists do you have loaded?

**Comment by MENtos224** [comment]
> what wishlists do you have loaded?

nothing i have no wishlists loaded. i was using it as usual transferring my guns through vault and other characters. After a while i opened dim and i kept getting this error. and it hasnt worked ever since. for the time being i have been using beta dim and its working so far. but i would like for the original dim to start working as it should

**Comment by bhollis** [comment]
Still not enough info, unfortunately. Feel free to reopen if you can get us console logs and a screenshot of your Wish List settings.
