### ISSUE TITLE
Error Moving Items with empty Inventory

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#778]
Here's a couple videos that demonstrate an error I was experiencing.  The core issue is I'm trying to equip an item that is currently equipped on another character.  I can repeatedly recreate a bug that cycles between two different states where the transfers fail at different locations.  

Double click was never successful at equipping an item, and would silently fail.

https://youtu.be/SsFz97ZePD4

MoveTo and Drag and Drop would succeed the first time, and fail the second time.  This time I get an error message.

https://youtu.be/z0oClQ76ayQ

**Comment by bhollis** [comment]
Thanks. I'll puzzle this out next time I get a chance.

**Comment by galador** [comment]
I think I got a similar issue. Mine, I tried to use the "Item Leveling" option. DIM was trying to transfer a heavy weapon from a new character I just created. It was the only weapon that this character could equip, so there was nothing to put in his heavy slot.

After I purchased a dinky second heavy for my new character, the Item Leveling option worked again.

Here's what I was seeing in the Dev Console when there was an error:

![Error](http://i.imgur.com/k2UKrib.png)

**Comment by bhollis** [comment]
OK, there are three separate bugs here. I think I've fixed @galador's bug, and @SunburnedGoose's first bug. The double-clicking thing was due to some bad logic in the double-click handler such that double-clicking an equipped weapon from another character would never equip it.

Goose's second problem, with the `maxStackSize` error message, is hard to figure out without having gotten to see a stack trace. My guess from looking at it was that it was a bug I fixed a while ago having to do with items changing out from under you while you were moving them. If you see it again, grab a stack trace and I can figure it out.
