### ISSUE TITLE
Empty mod socket shows up in the "Perks, Mods & Shaders" column of Organizer

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7817]
Not on every item, but on some:

<img width="481" alt="Screen Shot 2022-02-04 at 11 12 37 AM" src="https://user-images.githubusercontent.com/313208/152589054-37ccd66e-06f0-449c-bf58-a6676cf7bae3.png">
<img width="743" alt="Screen Shot 2022-02-04 at 11 12 33 AM" src="https://user-images.githubusercontent.com/313208/152589058-40fa14dd-384c-471e-8622-a9acf2cf165a.png">

**Comment by robojumper** [comment]
This reliably happens to Dreaming City armor's general mod slot (because the singleInitialItemHash is Riven's Curse) and Artifice armor's extra artifact mod socket (because the singleInitialItemHash is empty, which loadouts already accounts for). These need to be fixed.

I also have one armor piece with an empty combat style mod socket as shown in the screenshot: Holdfast gauntlets from the Arrivals pass, this one has a plugged hash of `4153634494` which is empty but not the correct empty mod socket. There's an alternative empty plug available in the mod chooser, I suspect plugging a mod and emptying it again fixes it.

**Comment by bhollis** [comment]
Do we need a d2ai-generated list of all the empty plugs?

**Comment by robojumper** [comment]
With #8197 merged, this should be largely solved: We don't show an empty mod socket anymore for artifice armor sockets or Dreaming City armor, which is where this would happen on a regular basis.

The Holdfast piece I mentioned above and the Insight Rover Boots in the screenshot still show the empty socket and that's because the "Empty Mod Socket" plug is actually the wrong variant of the plug; it appears Bungie changed the PlugSet at some point to reference a different empty plug and existing items now have the wrong kind of empty mod socket. Plugging the proper empty plug through DIM or game (or plugging anything else) would fix it permanently for the item.

In a sense, these behave exactly like deprecated amor mods, and should be treated the same: Hiding these leftover empty plugs also ought to hide the deprecated armor mods based on the fact that they're not a valid option for this socket in the first place.
