### ISSUE TITLE
Glob syntax in searches?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7998]
Would it be useful to give more control over string matches in filters? E.g. `perkname:"* Frenzy"`?

**Comment by bhollis** [comment]
@nev-r @delphiactual @robojumper, any thoughts on this?

**Comment by robojumper** [comment]
I'm not sure how useful it would really be; I haven't needed it yet. I assume the main motivation is ensuring `perkname:"Frenzy"` doesn't match Feeding Frenzy, and it'd be useful for that.

* A fair number of filters can't support that syntax, e.g. `season:redwar` is `season:=1`. What is `season:"*ris*"` or `season:">*ris*"` (could match `osiris` and `risen`)? We'd want a good way to tell users which filters support that syntax and which don't.
* About `perkname` in particular: Contrary to what its name implies, that filter searches a bit more than just a name, and I've been using `is:crafted -perkname:"additional minor stat boost"` to get crafted weapons without an enhanced intrinsic (because it looks at tooltip notifications). Switching it over to require a full match by default for any string would be a breaking change and the fix is maybe not super discoverable?

**Comment by bhollis** [comment]
Fair enough. Best I can think without breaking backwards compatibility is to have glob search mode activated by having a glob in the string, and that's pretty mind bending.

**Comment by nev-r** [comment]
i cannot fathom using it or what to use it for but maybe that's a failure of imagination on my part
