### ISSUE TITLE
Update Item Feed to use custom search

### ISSUE THREAD

**Issue by ThatGerber** [DestinyItemManager/DIM#8056]
### Proposed change

Currently, the Item Feed shows a list of all items, with a toggle to hide tagged items. I think it would be a better design if the item feed opened to the current size it is, but could be “dragged” a little wider, or float over the window, and allow a custom search to be used to populate the feed. Creating a resizable or floating window would also allow more or less of the item data to be shown. The search logic `tag:none` could still be used to replace the “Hide Tagged” toggle.

### How does this fit into your workflow?

It’s not part of my organization style to tag everything. In fact, I usually only tag only a few things (because of the lack of custom tags, I actually will use loadouts as a way of tagging items). As such, my item feed has items in it from months ago at the top. It’s hard to notice at a glance while playing whether a new item is there that I’m interested in. 

I’d love to be able to filter it by something like `is:maxpower OR (stats:custom:>40 stats:base:>65)`, then I can see when a new item appears and I want to use it.

I mean, ideally, it would also be functionality that could be worked into a custom event-based system or custom tagging, like “Apply tag ‘Keep’ and move to vault all items that match this filter” so that I could create multiple feeds and multiple actions to perform against them (“All Items with Modslot : VoG and custom stats > 40, tag ‘VoG Raid Gear’ and ‘High Stat rolls’ and move to vault”). But for now, allow a feed of relevant items would help me tremendously, especially here in the new expansion sorting through all of the new stuff.

**Comment by bhollis** [comment]
That's not really what the Item Feed is for - it's mostly for tagging everything. If you're not into that, you should close the item feed.

If you're looking for search results in a drawer, you can tap the thing in the search field that says "N items" and it'll show any search.

The last of your suggestions is logged as #7219.

**Comment by ThatGerber** [comment]
That's one use of the Item Feed, but I don't understand why it has to be the only use. The enhancement wouldn't change the functionality of the Item Feed, or even the default functionality. Item drawer gives me a large amalgamation of items each time I enter the search, but it's not going to give a constantly updated list of them always visible on the screen.

I'm not understanding what the argument against updating the Item Feed to use a search result instead of how it exists now, populating it with everything except maybe things that are tagged?

Again, it assumes that the user is tagging everything or wants to tag everything. Telling me to hide it if I don't like it is very dismissive and unhelpful to what would be a non-invasive update to functionality. Why not just tell me to "use another app if I don't like it"?

**Comment by inexorableAce** [comment]
The item feed was designed to as a tag all things feature. It's to get people using the very specific workflow that DIM tagging facilitates. Custom tags have also been implemented via the notes field. adding a # before text will add a new custom tag that is then auto-completed after using # in the notes field or search bar. 

The main argument I see is that everything you want to do in the item feed, because you dislike DIMs tagging workflow, can be done in the inventory view. There is no real reason to complicate the item feed with it.

**Comment by ThatGerber** [comment]
Again, I reiterate that I fail to see how this unnecessarily complicates the interface. Every enhancement by nature complicates the interface. The Item Feed is a complication to the interface. Adding a search bar to the top of the item feed to filter the results is a very minor addition to the item feed. Why does the Item Feed have to be defined as anything more than "A feed of items". Why not provide a sane default and allow the user to choose how that list is populated?

It seems like the reason I'm getting is, "This is an app built for us, not for you," and if I don't want to follow your tagging conventions and use the app the same way you do, I should use another one. Maybe my confusion is the use of the term "Tag". Tags are not finite, categories are. DIM has rigid system of categorization that permeates the UI, and a simpler system of tagging that is done exclusively via the Notes section? Is this functionality documented anywhere? Is there a way to make it clearer for people like me to who don't like to use the rigid category list?

I've contributed to lots of OSS projects, and I'd be happy to brush up on my Node and try to contribute the enhancement, but I don't want to invest the time and effort if it's just going to be tossed away as, "This isn't the way we like to use the app," because twice now that's the response I've gotten. This is really the first time I've been told by a project that they won't consider my request period because it's not the way they like to use the software.

**Comment by inexorableAce** [comment]
I think you're overreacting a bit... I don't use the item feed at all, I'd imagine there are other contributors that also don't. As I said, why do you want the item feed to do what you can already do on the inventory page without it? 

"Just because" is a valid answer but likely not one that's going to convince someone to spend their free time and effort on it amidst a brand new season of destiny where new things need to be added and old things need to be updated to accommodate it. 

And yes custom tagging is documented multiple places. Both here where we have an FAQs section that details the "I want more tags" question and lists our solution of # tagging. As well as in the user guide, which can be found linked all over the app including in the menu. 

Anyone is always welcome to PR but you're right I dunno how many people would be interested in expanding the item feed... at some point it's just another inventory on top of inventory. Which is beside organizer, yet another cut of inventory.

**Comment by bhollis** [comment]
It's not so much an issue of "how we want to use it" as it is a question of product design. We don't put everything in the product, because we're trying to design it a particular way. Part of that is having a purpose for each piece, and not complicating it by adding other options that at least so far as I understand the description of them, don't add to that design. It's possible there's something there but I think you'd have to dig into the description of how you'd use it more (and focus in on one suggestion) for us to get to something, together, that fit with the product and added general value. In the meantime, and assuming we can't come to that conclusion, I've offered you some alternatives to what you're interested in doing - the search results page still sounds like what you're trying to do.

As far as documentation, it's linked from "About DIM" and various other places in the app, and is open for contributions: https://destinyitemmanager.fandom.com/wiki/Category:User_Guide

**Comment by ThatGerber** [comment]
> I think you're overreacting a bit... I don't use the item feed at all, I'd imagine there are other contributors that also don't. As I said, why do you want the item feed to do what you can already do on the inventory page without it?

Please don't tell me how I'm feeling. How you think I'm reacting isn't relevant my point.

I want a feed of relevant equipment because if there is going to be an Item Feed as a permanent fixture on the inventory UI, it would be nice if the user could customize how it was used. Even minimized, it's a permanent fixture of the UI. If asking to customize the item feed is too much because it can be worked around, why even have an item feed at all since it can be worked around in the same way? Because for some of us, it would be nice to have. Cars don't need heated seats, but they are pretty nice to have. 

For me, it's about eliminating noise and work. The Inventory page is filled with noise. The item feed is filled with noise. Every drop exists in the item feed until it has been categorized or dismantled. If I want to be able to see at a glance that some new item has dropped that falls within my search parameters, then I need to go to the inventory page, refresh, hit search, look through the list of items, and if something new is there, click on the item, click on the note box, enter in a tag, and then go back to the search results and see if I missed one, and repeat. There's too much noise, and too much work, to just be able to see that a new item has dropped at with 20+ int and 40+ custom stats and add a `#candidate` tag to review it later. Or see that a shotgun has dropped with one-two punch and Full choke or an auto rifle with subsistence. 

I'm trying to eliminate the amount of time I have to spend fidgeting with DIM by getting rid of noise and displaying the most relevant information prominently because most of the time I'm trying to do it in between glancing at the game or trying to move something to my character quickly before a new encounter. 

Categorizing every piece that comes in is a labor intensive solution that does not eliminate noise. It generates more noise. With the feed, I need to look at every single item that comes in and determine if it is the thing I want. No one should have to make that many value decisions at once. It's just generating decision fatigue to populate a UI where someone has to make a decision of value based on every single thing that comes in. It's exhausting. I can't mark it as "viewed" and have it drop from the feed without categorizing it. And with the item drawer, I need to open up a submenu to look through every item and see if there is a new one that matches my criteria. Currently the suggested way to eliminate that noise is again to categorize everything, further cluttering the UI with category icons on every single item. If I try to glance on my inventory to find a recent drop to pull to my character to equip, I'm mentally filtering through the note icon, category icon, lock icon, and new item icon, which are all tiny and visually similar, and there's very little left of the actual item icon for me to see what it is. Leaving categories and notes off makes it a little bit easier to visually locate the item I'm trying to find, but now I need to add the note icon instead. Seeing them in a chronological feed helps look through "what has dropped within my parameters since I last reviewed" so that I can pull out the relevant items and ignore the rest, but instead I need to see everything that has dropped chronologically and look through those to find the things I'm looking for to actually review them.

I want the app to allow me to use the functionality it has in a way that is customized by me to my preferences to make the chore of managing items easier. Until Destiny gives us 1000 or more vault slots, I will have to spend all too much time and energy making decisions about which guns to keep and which to get rid of. Being able to automate the work of managing it and replace mental processing, which is expensive, with computer processing, which is cheap, removes a lot of the chore and toil of trying to manage gear in this game.

For now, I'm just going to stick with using loadouts to tag gear. Adding tags in Notes, as far as I can tell, does not provide a way of seeing in a list all of the tags in use. Unless there is somewhere and it's just not documented anywhere in the "Filters Help" tab (filtering by `#tag` is never mentioned in that tab, either, as far as I could find). The search dropdown cuts off the list of tags currently at 6 and only shows the most recent 6 used. So, I'll just continue to use the loadouts. Good luck.
