### ISSUE TITLE
Filter deepsight weapons by those with patterns that haven't been unlocked yet

### ISSUE THREAD

**Issue by MeatSim** [DestinyItemManager/DIM#8176]
## Current filters
While you can currently filter by `is:craftable is:deepsight`, this would still include weapons with patterns that you've already unlocked. Individually excluding unlocked patterns (e.g., `-name:"syncopation-53"`) would become more tedious as unlocked patterns increase.
## New filter description
This new feature would add a filter like `craftable:unlockable` (idk the naming convention) to filter deepsight weapons with patterns that haven't been unlocked yet, i.e., incomplete pattern progress in Records > Patterns & Catalysts:
![image](https://user-images.githubusercontent.com/31776312/158923621-0187c99c-2fa3-4e62-9dc5-0916ce70d21b.png)
## Related issue
This issue is related to #8085 in that it needs information from `Records`.

### How does this fit into your workflow?

This would be useful when I want to focus on unlocking crafting patterns without going back and forth between `Inventory` and `Records`. I could see on the Inventory page which deepsight weapons to use to gain pattern progress.

**Comment by bnb** [comment]
Just opened up GitHub to create this issue. As we've gotten further in the season, it's become more clear that this would be helpful in farming weaponcrafting materials since we've got an abundance of deepsight weapons and it's obvious that prioritizing finishing locked patterns would be useful. 

The following seem like reasonable names to me, presuming DIM wants to stay as close to the in-game naming as is possible:
- `pattern:unlocked`
- `pattern:locked`
