### ISSUE TITLE
Clear item feed

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8180]
For folks who want to have the item feed only for a "session", it'd be nice to have a command to store a high water mark in settings and not show items below that. We'd also need a command to clear the high water mark.

**Comment by renro988** [comment]
I wholeheartedly agree with this; a session-only item feed would be nice. Perhaps, bind it to 'Farming Mode'? Do not know about others but I never user farming mode because I dislike trash flowing into my vault. Having a _farming session item feed_ would allow me to rather simply review what I've farmed.

**Comment by DHager** [comment]
I'd rather not tie it to Farming Mode, since I don't use FM. (Vault is too close to full.)

**Comment by bhollis** [comment]
It would not be tied to farming mode

**Comment by jstaudenmaier** [comment]
I think this issue was addressed in https://github.com/DestinyItemManager/DIM/pull/8860
