### ISSUE TITLE
"Strip sockets" search action

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8419]
We've gotten some requests for an ability to bulk-reset items by removing their mods. I was thinking we could have a single action that reset all pluggable sockets to their initial state - mods, ornaments, shaders, etc. Thoughts?

**Comment by robojumper** [comment]
I'm in favor of this, though it should be possible to clear only cosmetic or gameplay sockets.

In addition to the artifact mods weirdness, it also turns out the API is sometimes unable to replace deprecated mods, so this season I had to manually remove the deprecated mods in-game before applying loadouts succeeded. If a clear action existed I'd use it at the end of every season.

**Comment by DHager** [comment]
Would that also include stripping mods from weapons? That seems like a way people might shoot themselves in the foot, since (unlike armor loadouts) there's no way to consistently or automatically put them back again.

Another option is a specialized search action which only strips seasonal mods.

**Comment by bhollis** [comment]
I'd expect if you don't want to remove mods from weapons, you wouldn't include weapons in your search?

**Comment by bhollis** [comment]
If we want to have a ton of configurability of this, it'll have to wait until we have a decent dialog component.
