### ISSUE TITLE
Classified (Duality) gear is not accounted for in max light calculations and Is:maxpower unless equipped

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#8430]
### DIM Version

Version 7.18.1.1001748 (beta), built on 5/27/2022, 11:52:51 AM

### Browser Details

Chrome101.0.4951.64 

### OS Details

MacOS

### Describe the bug

Received pinnacle gear from Duality dungeon which should be the highest light item I have in the slot.  Item currently is classified.

If the item is in inventory and not equipped, its light is not accounted for in the "Maximum Power of all gear" calculations.  It will also not be highlighted if doing "is:maxpower".

However, if you equip the item, then it will be accounted for and also highlighted.

**Comment by thomaskchan** [comment]
Forgot to mention that my duality item is armor.  I did not receive a weapon so cannot say if it affects both weapons and armor.

**Comment by vivekhnz** [comment]
Unfortunately, Bungie's API doesn't return the class type of classified armor pieces. Even though DIM knows the Power level of the item, we don't know if it is the highest Power item because we don't know whether it's for Hunter, Titan or Warlock.

This doesn't affect classified weapons (because they are class-agnostic*), which is why DIM can include their contribution when calculating max Power (provided the item is on your character, since the API won't return the Power level of a classified item if it's in the Vault).

* Unless the classified weapon is class-specific for some reason e.g. Exotic Glaives, some swords
