### ISSUE TITLE
Typo in Season 18 Challenges

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#8656]
The new season 18 challenge, "The Astral Seas," is marked as a +2 Power challenge in DIM. This is incorrect, it's actually a +0 Power challenge, and it's marked in the in-game interface as Powerful (Tier 1) which corresponds to a +0 Power drop.

**Comment by robojumper** [comment]
The definitions say this is a pinnacle reward, so that's what we show. Historically these rewards have been quite unreliable and we have a workaround, so we should consider extending this workaround to correctly clock these as T1 powerful https://github.com/DestinyItemManager/DIM/blob/44e6550aacfd6d643edd2838e9a38ca1e00f7d0f/src/app/progress/engrams.ts#L48-L63
