### ISSUE TITLE
[Feature Request] Optimize the assignment of subclass sockets when applying a loadout

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#8718]
### Proposed change

Change the loadout system to avoid trying to apply an aspect/fragment to a socket when another socket on that same element contains the aspect/fragment in question.

I suspect that mods are already handled like this in the loadout system, as it seems like DIM calculates the distribution of the mods when the loadout is applied. What I'm suggesting is that loadout system should handle subclasses in the same way.

### How does this fit into your workflow?

If I have two loadouts with Solar subclasses that use the same fragments, but the fragments were selected in a different order while building each loadout, trying to load one loadout after the first one was applied will result in DIM reapplying the fragments. Even though both loadouts have the same fragments, just built in a slightly different order. 

Here's an example, in case one is needed:

Loadout 1
Ember of Torches
Ember of Ashes
Ember of Wonder
Ember of Searing

Loadout 2
Ember of Ashes
Ember of Wonder
Ember of Searing
Ember of Torches

Applying Loadout 2 after Loadout 1 has been applied will result in every fragment being stripped and then reapplied, only in a different order. Torches will be overwritten with Ashes, Ashes will be overwritten with Wonder, and so on, until all of the fragments have been reapplied even though the order of the fragments is irrelevant.

This would improve the speed at which a loadout is applied, and it's something I noticed during the recent API problems that occurred during the launch of Season 18 and the influx of new players from the Epic Games Store release.

Currently, you can workaround this problem by manually editing each loadout so that you've chosen similar fragments in the same order on each loadout using the same subclass (I always choose Torches first and Searing 3 when building, etc), but that's not a very flexible solution to the problem when it could just be handled in logic.

**Comment by bhollis** [comment]
Hmm, I would've expected it to work the way you describe - ignoring order. @ryan-rushton do you have some idea?

**Comment by robojumper** [comment]
https://github.com/DestinyItemManager/DIM/blob/7a208bf5d73790bc2f3ee613c268f7e03d253446/src/app/loadout-drawer/loadout-apply.ts#L902-L922

Right now Loadout application uses `socketOverrides` for subclass plugs, which specifies a position for every subclass socket, and DIM will make sure they are slotted in these positions. Two ways to solve it would be:

* Consistently sorting subclass sockets in the loadout, so that all future loadouts will put them in the same order (this is easy but doesn't solve already saved loadouts or stuff people apply in-game)
* Doing something smarter when applying socket overrides, e.g. noticing when plugs are specified for a different socket in the same (subclass only?) socket category.
