### ISSUE TITLE
Show pattern unlock progress on vendor items

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8748]

**Comment by robojumper** [comment]
Also see #8576. The heart of the issue is that these vendor items are fake items with a different hash, so when we look at the definition we think it's not craftable.

https://github.com/DestinyItemManager/DIM/blob/7c1aaec83f889c145f7e1d89e4e173850d86303c/src/app/inventory/store/patterns.ts#L25-L46

The way this currently works was discussed in https://github.com/DestinyItemManager/DIM/pull/8420#pullrequestreview-985964609, the primary consequence being that the legacy versions of some reissued craftable weapons do not show the pattern unlock progress.

Replacing the `if (!recipeItemHash)` with a `if (!item.bucket.inWeapons)` should fix this and the related issue, but will also make more things match (like the aforementioned legacy versions of items). I'm not sure there's a good way to recognize these fake items.
