### ISSUE TITLE
Improving experience when finding armor to fit a new loadout

### ISSUE THREAD

**Issue by ciaran** [DestinyItemManager/DIM#8796]
### Proposed change

I recently tried to create a loadout from a DIM link, and when clicking the Optimise Armor option for the loadout I get no results and a non-obvious message:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/3736/197195243-589d8d9b-d973-4a07-ac60-4fc8c7090e85.png">

After trial and error removing mods I found the issue was that I didn't have an artifice armor piece for one of the slots, so one mod couldn't be placed.

### Changes

I’m hoping to improve this experience, I’ve made some PoC changes which I’m sharing here to get feedback:

First, clearer callout for the error with a new option:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/3736/197195731-fc75c159-7cfb-4914-9d35-468f66f9cc83.png">

Second, after choosing this option we now get a list of results, with mods which couldn't be assigned shown for each set:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/3736/197195949-b48e67ec-857d-4a65-b87c-be01a4ef0439.png">

### How does this fit into your workflow?

This is based around the workflow of opening a shared loadout link, and using the armor optimiser to find a set which fits the loadout.

**Comment by robojumper** [comment]
Showing sets that can't actually fit all mods is not really what LO is meant to do and recent changes (on beta, where we automatically assign stat mods) make this even more difficult because that part respects all mod costs.

Also builds may contain stat constraints (like T10 Resilience) and this option wouldn't do much there.

But I do agree that a better way to see *why* no sets were found would be good. Maybe we could even offer some interactive suggestions to relax stat and mod constraints. LO already tracks why it rejected a set, and the artifice thing in particular is really easy to detect because we assign bucket-specific mods before even starting the worker process.

**Comment by robojumper** [comment]
Basically, here's how we could show that you don't have an artifice helmet

![grafik](https://user-images.githubusercontent.com/14299449/197350807-7b513fa9-f7c1-49e5-8d1b-d326abcbc1ff.png)

see #8798.
