### ISSUE TITLE
Loadout builder issue

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#886]
Hey

Loving the perk selection for the load out builder.

However upon trying it this morning i came across a small issue.If you change your mind and select a different perk, the previous one is not deselected and still active as the one that count for the search results. See screenshots attached

![screen shot 2016-09-10 at 11 09 33](https://cloud.githubusercontent.com/assets/2083273/18409760/e7374748-7747-11e6-9f1a-40b02f25bb36.png)
![screen shot 2016-09-10 at 11 10 11](https://cloud.githubusercontent.com/assets/2083273/18409761/e76c8d90-7747-11e6-9b08-222c8b05a622.png)

**Comment by kyleshay** [comment]
I believe that is intentional. If you click multiple perks, they are 'OR'd, if you hold shift and click multiple perks, then it will 'AND' them. To unmark something, you need to click on it again.

<img width="528" alt="screen shot 2016-09-10 at 8 03 21 am" src="https://cloud.githubusercontent.com/assets/424158/18410329/1cc9ac4a-772d-11e6-9a8a-205739abcb83.png">

@ericnelson0 ?

**Comment by ericnelson0** [comment]
@kyleshay That's right.

**Comment by shockthealien** [comment]
oh i see. I Don't see that copy/ legend anywhere. Mine goes straight into search and displays the results

**Comment by shockthealien** [comment]
Also playing with it now, if you are wanting to do AND you have to SHIFT click the first item too, not only the second one. So if you go in and click on one, and later on you want to AND another you have to deselect the first one and shift click it again then shift click the second one

**Comment by ericnelson0** [comment]
Yeah, that's the expected behavior. So people can choose a set of perks or any other perks.
