### ISSUE TITLE
Sort by newest

### ISSUE THREAD

**Issue by Sleazus** [DestinyItemManager/DIM#8876]
When I'm trying to sort out this to junk, I transfer them to a character, put an exotic in the vault as a marker, then back to the vault, so I can go into the game go to the vault and quickly dismantle or check what I want.

It'd be nice to have a sort by newest feature, as opposed to having to check where I was up to dragging and dropping.

Also not sure if there's a feature to transfer searched for items to a character then straight back to the vault.

I just think sort by newest would be a handy feature

**Comment by robojumper** [comment]
To clarify, "newest" here means "most recently transferred" similar to how the in-game vault sorting option works? I'm afraid DIM can't sort items the exact same way as the game, since we don't have those details when item transfer happens in-game.

> feature to transfer searched for items to a character then straight back to the vault

Search for some items, click your character emblem, and choose "transfer search". Works with the vault emblem too, and you can also do this by clicking the three dots ("bulk actions") in the search bar after entering a search.

**Comment by Sleazus** [comment]
Yeah, thanks for that. I also realised just today I could probably

Make a temporary currently equipped Loadout
Move equipped to the vault
Transfer an exotic to a character and back to the vault as a marker
Turn on farming mode
Do a search
Transfer search
Turn off farming mode
Re equip loadout
