### ISSUE TITLE
Bring back ability cooldown info

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8994]
https://github.com/Database-Clarity/Character-Stats

**Comment by StardustD2** [comment]
Commenting here in case I'm needed for discussion about the linked repo (suggestions/questions/possible improvements/etc).

**Comment by bhollis** [comment]
@StardustD2 is the info from the linked repo accessible from the Clarity DB site, or is it meant to be consumed as a subrepo? Has it been updated for Lightfall changes? Was thinking of taking a stab at this.

**Comment by StardustD2** [comment]
@bhollis I got the Lightfall numbers after 12 hours of mind-numbing testing and number crunching. Did a bit of restructuring as well to have a way to account for exotic armor (the ones that passively change cooldowns) in the future (not yet added).

Everything should be (close) to finalized so you can start working on it whenever.

**Comment by bhollis** [comment]
Awesome, this should be really useful.

What I was asking about the hosting - for the descriptions database, we load it from `https://database-clarity.github.io/Live-Clarity-Database/descriptions/dim.json`. It'd be great if this file was also available from the same domain `database-clarity.github.io` so we could load it at the same time.

**Comment by StardustD2** [comment]
It is! Listed the links to both versions in the readme.

Also, I have another hotfix coming very soon that changes a few minor things because I realized I failed to account for Bleak Watcher properly.

**Comment by StardustD2** [comment]
Hotfix is now live.

**Comment by StardustD2** [comment]
@bhollis just a quick heads-up because I'm implementing a minor but breaking change to how "Overrides" are handled. Not sure if you've started work on implementing things yet but it should be a quick fix if you have. I've updated the changelogs file with the necessary info as well.

This should be good enough of a structure to handle anything I would need to add in the future so I don't expect any more breaking changes. But I also changed up the `update.json` file just in case so I'd have a better way of dealing with breaking changes if necessary.

**Comment by bhollis** [comment]
Awesome thanks. Haven't gotten to it but hoping to soon.

**Comment by StardustD2** [comment]
Small update on my side of things:
Did some cleaning, adjusted the rounding settings, and finally added everything remaining that messes with ability cooldowns. Would still strongly suggest rounding the results for display but at least this provides an added level of precision for the underlying client-side math.
