### ISSUE TITLE
Target Light for Character

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#903]
https://twitter.com/fuzzle_hc/status/775671533628956672

Community wants to create game types that want players to meet a target light level.

**Comment by FuzzleHC** [comment]
Since we don't have damage modifiers in the current private matches options we want to make our own.

Using light level advantages we will figure out what light level players have to be at to do a certain amount of damage depending on the gametype (Infection for example).

I would love to have a text input window that I can input an integer in (for example 150 light), DIM would then scan my inventory for the combination of gear that would come closest to that light level and equip it.

If you have any questions shoot, thank you very much <3

**Comment by SunburnedGoose** [comment]
Are there requirements for specific weapons or exotics?

**Comment by FuzzleHC** [comment]
Community GameTypes are varied and dynamic, sometimes specific gear like exotics or ornaments are a requirement, often multiple at once.

This might overcomplicate the feature though but that's your call.

Suggestion: Maybe include 9 checkboxes (3x3) users can select to lock certain gear in place before starting the algorithm with a button. 

So I want to play zombies with light level 150, I want to keep my sword in hand for melee and I want to keep the sprint lock artifact and the Taken helmet.

I open DIM and equip a sword, the artifact and the taken helmet. I click on the light level feature, a window appears. I see a text field with "Input desired light level", underneath I see 9 checkboxes with text "keep primary, keep secondary, keep heavy, keep ghost, keep helmet, keep gauntlets, keep chest, keep boots, keep artifact". At the bottom is a "submit" button.

I input 150 in the text field and I check "keep heavy, keep helmet, keep artifact" and hit submit.

DIM then equips gear to get closest to 150 light but keeps the Sword, helmet and artifact the way it is.

Done, customs can be played

**Comment by kyleshay** [comment]
Linking #568

**Comment by bhollis** [comment]
This is a fun idea but unlikely to be implemented - it's a lot of custom UI for a niche feature.
