### ISSUE TITLE
Loadout Optimizer is miscalculating

### ISSUE THREAD

**Issue by Gille2k** [DestinyItemManager/DIM#9047]
### DIM Version

7,54,0

### Browser Details

Firefox 109

### OS Details

Windows 10

### Describe the bug

Hi Lads,

I was trying a new loadout today and DIM was telling me this would be the necessary stats

![image](https://user-images.githubusercontent.com/122526870/216335034-a66793b7-71e9-4dc4-ab32-763a173a8cc9.png)

As you can see, to get all my mods in the armor Helmet and Breast need to be Energy Level 9

So technically they don't need to be masterworked, but as soon as I switch "assume masterwork" to legendary only or none, the result is, that the loadout is not possible anymore.

![image](https://user-images.githubusercontent.com/122526870/216335865-7843fe5c-5025-4fa9-888b-59325428c2e7.png)

I would expect I see the same result, with the info I need to upgrade to level 9.

**Comment by robojumper** [comment]
If you're not assuming masterworked armor, armor will only be implicitly considered upgraded to energy level 7, since levels 8+ need endgame materials (enhancement prisms and ascendant shards). The "None" option mentions as much, but admittedly this is not mentioned in the "Legendary" option.

![image](https://user-images.githubusercontent.com/14299449/216364808-d8ec2074-06a5-48f3-8456-2e2be71ae11c.png)

**Comment by Gille2k** [comment]
Ah ok, so if I would upgrade the helmet to 9 the legendary option would show, that this combination would work, while assuming the L3 breast is masterworked.

Yep the tooltip could solve this with a little more info, thanks :)
