### ISSUE TITLE
Never choose to replace an exotic with another exotic when de-equipping

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9083]
### DIM Version

Version 7.56.0 (release), built on 13.02.2023, 05:24:26

### Browser Details

Chrome 108.0.0.0

### OS Details

Windows 10

### Describe the bug

I was wearing Lorentz Driver (LD), but swapped to Gjallarhorn in game. Then I wanted to move LD to the vault, but DIM failed because LD was still equipped in DIM and DIM was trying to replace LD with the exotic glaive. After I moved glaive to the vault, DIM was able to move LD.

https://user-images.githubusercontent.com/35541026/219216461-1b3d0317-914a-4eeb-b38e-d6f98e2f86cb.mp4

For me looks like a bug. There were plenty other non-exotic stuff in my inventory to replace Lorentz Driver that actually was not equipped all that time.

[Logs](https://github.com/DestinyItemManager/DIM/files/10748964/app.destinyitemmanager.com-1676502740319.log)

**Comment by bhollis** [comment]
I wouldn't necessarily call this a bug - it's more of a choice in implementation. DIM doesn't know the exact current game state, and if you do things in DIM when it's not up to date you'll get odd results no matter what. In this case it thinks LD is equipped, so it must be de-equipped to move it, which means equipping something else.
https://github.com/DestinyItemManager/DIM/blob/44641160e4e5f702fdf0d27a2e0bbda9f0508989/src/app/inventory/item-move-service.ts#L248 is where we decide which item to choose. Right now, it chooses to replace an exotic with another exotic to keep the equipped item as similar as possible, and that's probably not how it should work - it should ignore exotics insted.

However keep in mind that even with that fix, something random would have gotten equipped because DIM doesn't know LD isn't equipped. Always best to make sure you're up to date before doing moves.

I suppose we could also extend the "blind moves" capability to cover moving *from* a character, which would have handled this, though DIM would have gotten *very* confused as it would then believe there is no equipped item at all.

**Comment by Prometheus3375** [comment]
> Always best to make sure you're up to date before doing moves.

From the start of the season 19 I noticed that sometimes it takes plenty of time to get updated data. I think the issue lies on Bungie side. In the attached video you can notice that game state was not updated for ~2:50 before it finally got an update. When I started recording the video, state was not updated for ~1:35 and I got error-coded in game. This did not help to get up to date state to my surprise (ex. going into activity or orbit usually helps).

**Comment by bhollis** [comment]
That's correct, but unfortunately the principle stands - DIM can only be so effective without up to date information
