### ISSUE TITLE
Check for mod assumptions

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9102]
@robojumper you'd mentioned that we might have some mod assumptions that could crash DIM after all the mods are changed in Lightfall?

**Comment by robojumper** [comment]
This

https://github.com/DestinyItemManager/DIM/blob/ff621a5cde00ed7621da032ed8f4e2dfc227ea1c/src/app/loadout/loadout-ui/Sockets.tsx#L47

will throw if there's any mismatch between what `fitMostMods` and `pickPlugPositions` think is true. The former relies on all the curated metadata in https://github.com/DestinyItemManager/DIM/blob/ff621a5cde00ed7621da032ed8f4e2dfc227ea1c/src/app/search/specialty-modslots.ts and it's very likely to be all wrong, while the latter actually inspects the items and their PlugSets.

Thinking about it however, it might not be a huge concern because we already have a workaround for deprecated mods https://github.com/DestinyItemManager/DIM/blob/e19eca0bd4cebe8403a3d3b10b27632f3f956af4/src/app/loadout/mod-assignment-utils.ts#L81-L88 so mods that the game data says don't fit into any socket will not even use our hardcoded assumptions.

We also have hardcoded costs in LO

https://github.com/DestinyItemManager/DIM/blob/ff621a5cde00ed7621da032ed8f4e2dfc227ea1c/src/app/loadout-builder/process-worker/auto-stat-mod-utils.ts#L6-L27

these need to be updated but I think they won't cause crashes.

Could still be useful to `try/catch` that bit in `Sockets.tsx` until we're confident we've modeled the Lightfall mods correctly.

Oh and we should probably make this optional because the mod or its perks might simply go away

https://github.com/DestinyItemManager/DIM/blob/ff621a5cde00ed7621da032ed8f4e2dfc227ea1c/src/app/utils/plug-descriptions.ts#L129-L130

**Comment by bhollis** [comment]
Good to close this?
