### ISSUE TITLE
Can't delete all deprecated mods

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9166]
Clicking the X doesn't do anything. Some of them worked...

**Comment by robojumper** [comment]
Oh right, this is because we lie about the mods obliterated by Lightfall by mapping them to a different hash. Would have to detect our magic deprecated hash here https://github.com/DestinyItemManager/DIM/blob/d3d160a2e45b72758b90e8b52c6ec4cb0022674e/src/app/loadout-drawer/loadout-drawer-reducer.ts#L318-L339
and eliminate one of these obliterated mods I guess?

**Comment by ItchyLizardKing** [comment]
Still having the same issue today :( x woný remove deprecated mods when editing loadouts.

Will they be automatically removed with patch?

**Comment by bhollis** [comment]
Well this isn't resolved yet so I wouldn't expect it to have been fixed.
