### ISSUE TITLE
Power Level summary not popping up (beta)

### ISSUE THREAD

**Issue by prunetracy** [DestinyItemManager/DIM#9291]
Clicking on my power level is not bringing up the power level summary panel at the bottom of the screen.

On the beta branch. Release branch still working.

**Comment by robojumper** [comment]
Can you give us more information, such as device, OS (version), browser (version)? Are you using a mouse or a touch screen?

**Comment by prunetracy** [comment]
Web app, Chrome browser Version 111.0.5563.111. Running on Windows 10 Home.

Using a mouse.

**Comment by vivekhnz** [comment]
I can repro this in beta (Chrome 111 on Windows 10).
```
Version 7.61.0.1002420 (beta), built on 3/23/2023, 2:46:06 PM
Chrome 111.0.0.0 - Windows 10
```

This only happens when using a mouse. It works correctly in the same browser with touch (simulated using browser dev tools).

Appears to be caused by [this commit](https://github.com/DestinyItemManager/DIM/pull/9283/commits/6920358988ec604f38c2c0ac35562bb593e1fdd6)  (#9283) to prevent dragging while pressing the tooltip.

Commenting out [this call to `setPointerCapture`](https://github.com/DestinyItemManager/DIM/blob/8b9bf5423a2e26924e4fbcac4e0922836afe38b3/src/app/dim-ui/PressTip.tsx#LL294-L294) resolves the issue for me locally. Perhaps we should only capture the pointer if the `PressTip` was opened from a `pointerdown`?

**Comment by THATDONFC** [comment]
I'm seeing the same issue on beta. I'm on macOS 13.2.1 running Brave Browser v1.49.120

**Comment by bhollis** [comment]
Hm yeah I thought that's what I did but maybe I need to delay the capture somehow? The interaction between the pointer events and click event are very confusing.
