### ISSUE TITLE
Stackables in Loadouts fail when I have insufficient amounts.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#936]
If I put five heavy in my loadout, and only have 3 total across all characters, the loadout fails. 

I would like to change this feature so that when applying a loadout, it will source as much as 5 instead of exactly five.  This would require the app to scan the account for all items and build up a plan to move as much as five to the target character.

**Comment by bhollis** [comment]
That's actually the current behavior. If you don't have enough of an item, we'll transfer as much as you do have (scanning across all characters and the vault), and then let you know that we didn't have as many as you asked for.

I'll tone down the info panel to be less error-y, since it makes it seem like nothing happened.

**Comment by bhollis** [comment]
Closing in favor of #946.
