### ISSUE TITLE
Allow selecting subclass plugs that aren't unlocked

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9399]
Apparently people want to "theorycraft" for things they haven't unlocked

**Comment by robojumper** [comment]
Who is asking for this? Loadout Optimizer already does that because Bungie.net returns wrong info (https://github.com/Bungie-net/api/issues/1572#issuecomment-1494412191), only SocketDetails on the subclass item popup uses this bad info...

**Comment by robojumper** [comment]
Unless of course this code doesn't do what it says and Bungie.net doesn't even respond with some plugs

https://github.com/DestinyItemManager/DIM/blob/fd382b720c643ec8f7edf3b684f8da3a11643963/src/app/loadout/SubclassPlugDrawer.tsx#L249-L271

but it should because the game always shows all subclass plugs, just greyed out with a "here's how to unlock" tooltip. So I guess this could be a bug and we need a profile response where stuff is missing from the subclass plug drawer.
