### ISSUE TITLE
getting weasel errors in D2 when DIM is on

### ISSUE THREAD

**Issue by SlartiBartFast74** [DestinyItemManager/DIM#9464]
I am getting "Contacting Destiny 2 servers" warnings in Destiny 2 at the exact moment when DIM is updating from Bungie servers. This repeats itself until I am booted out of the game with weasel error.
Logging out of DIM solves the issue.
I could almost reproduce this, but not really sure, as it is not exactly on a timer.

**Comment by bhollis** [comment]
If this is happening you should be able to reproduce it with any other app, including the official companion app. 

Since DIM only interacts with the Bungie API, same as all the other apps, this would have to be a bug in that API and not something DIM could fix. So this bug report needs to go to Bungie.
