### ISSUE TITLE
Revision Zero catalyst showing as incomplete

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#9525]
### DIM Version

Current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

Revision Zero is still being selected by the catalyst:incomplete filter even when all 4 of the catalysts have been applied and equipped.

In DIM, it shows as having a Catalyst reshaped option, which does not show anywhere in game.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/6958a8b1-8760-4ca4-9aae-df61dacd073a)

**Comment by robojumper** [comment]
If you go to Records -> Patterns & Catalysts -> Exotic Catalysts -> Kinetic Weapons, what does the Revision Zero Catalyst trumph say? If it's not marked as completed, that's why DIM highlights it and that's where the checkbox comes from.

You could also try doing a reshaping of the weapon with no changes and see if that completes the objective.

**Comment by philkernick** [comment]
R0 catalyst truimph is shown as complete.  However Vexcalibur isn't, and this has the same words shown.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/e0b20695-dd50-4999-bc56-e42cea369caf)

Is it possible that the R0 and VC catalysts have been swapped?

**Comment by philkernick** [comment]
Confirmed that the catalysts are swapped.  I just completed the Vexclalibur catalyst triumph, and now Revision Zero no longer shows as having it's catalyst incomplete.

**Comment by robojumper** [comment]
Got it, thanks

**Comment by robojumper** [comment]
Fixed by #9532.
