### ISSUE TITLE
Highlight loadouts that could have better stats

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9554]
This is a bit of a long shot but it's something we'd discussed on the Discord at some point. The idea is, on the Loadouts screen, to run the LO algorithm on each of the loadouts and highlight which ones could better meet their stat goals (or just hit a higher overall tier) with different armor.

**Comment by robojumper** [comment]
The usefulness of this will depend a lot on the definition of "better". If I take the second result from LO instead of the first one, that loadout would immediately gain a highlight, and sometimes the only T33 build has a really awful stat distribution so I opt for a T32 build instead and it'd not be great if it also was highlighted for that reason.

So I would suggest that this uses a "strictly better" approach, where a loadout is only highlighted if there's a set that's better or equal in all relevant stats, and better in at least one relevant stat.

**Comment by robojumper** [comment]
Also linking #9161 and #9470 because a better LO workflow would really make this feature much more useful:

1. If the loadout has missing armor items, the "Optimize Armor" button should say "Choose Armor" or "Pick Armor" and starts Loadout Optimizer in the "Enumerate Sets" mode where it just enumerates your best builds (that match the loadout parameters).
2. If the loadout has armor, the "Optimize Armor" button starts LO in the "Optimize" mode where the existing Loadout is pinned at the top of the screen and the worker process tries to find sets that improve upon the stats of the reference set. The way they improve upon the reference set could be visualized in some way in the loadout rows.
3. That way, clicking the "Optimize Armor" button with a loadout highlighted due to this "auto-optimization" feature opens Loadout Optimizer with the automatically found better sets directly present.

One concern I have about the auto-optimization feature is how much we can trust the saved loadout parameters -- people might not be aware of whether a saved Loadout has auto mods turned on, or whether a loadout has "assume masterworked" turned on, and I think it's better to be a bit optimistic here and automatically turn "assume masterworked" on for a loadout that has fully masterworked armor, or turn auto-mods on for a loadout that has saved stat mods. Maybe worth experimenting with if we leave that feature in beta for a bit.

**Comment by bhollis** [comment]
That's definitely the direction I was hoping to go. I may have time over the next couple weeks to pick at that workflow, but also feel free to take a stab at it.

**Comment by robojumper** [comment]
This is effectively implemented in beta with #10012 - we just need the Optimize Armor button to launch LO with the required LoadoutParameters (which are available in the analysis results) and a special "strictly better tiers only" flag (which is implemented on the worker side).

**Comment by bhollis** [comment]
This is working just as I'd hoped it would, in beta now.
