### ISSUE TITLE
Data visualization for armor tidying purposes

### ISSUE THREAD

**Issue by JagetYohan** [DestinyItemManager/DIM#9561]
Hi DIM team, and thanks for your amazing work.

I'm a data scientist and I work on R (so far: exclusively), thus making me not as familiar as I should with all the developer tools (I shall not pretend to be a developer). Sorry about that.

However I just coded a script to bind every armor item in the inventory (from the .csv you provide, thanks for the triple " in the Id column by the way '>_< ) to the best builds it belongs to, the number of occurrences in each build tier (I mean total stats of the masterworked build — 31, 31.5, 32, ... —, with all the constraints it implies) from a limit value parameter (in the example below, what you formerly coded as 31.5 and I as 31.1; the column 30.1 appears because this is the best tier build for a low stat exotic), ordered by those occurrences.
This is because I am not always sure I should recycle an armor item and my inventory is full; so that allows me to trash a 64 gauntlet without remorse.

The calculation takes under 4 seconds to execute for 14 millions combinations on a 2014 MacBook.
I can implement this script either as an embed html component (that would require a little research because I haven't done this before, but it works), or as a docker file for you to call via rest API (that I'm familiar with). It may also output a .csv.

Would you be interested in such an add-on ? I can show you the script if you want to know more about it, and we could discuss improvements at will.
Below is a sample of the results:

<img width="1174" alt="Capture d’écran 2023-06-08 à 11 35 41" src="https://github.com/DestinyItemManager/DIM/assets/108350389/6d537acf-c872-40ea-a0e5-9ea10e8fb58d">

Thanks again, I hope we'll talk soon.
Yohan

**Comment by robojumper** [comment]
Hi Yohan,

that looks exciting! A way to identify which armor to keep that's more accurately based on your vault and which builds it could support (rather than proxies like stat totals, "stat distance" (https://github.com/DestinyItemManager/DIM/pull/9508#issuecomment-1571487307), or clustering) is definitely something that could be very useful, and it's something I wanted to investigate too.

Since you didn't post your code, I can only make some assumptions about what your script does, but I want to quickly go over the things that make this complicated:

1. Different exotics/different subclasses care about different stats. My Graviton Forfeit build has the additional constraint that it wants 100 Strength, which maybe we should respect in some way. Further, my Arc Assassin's Cowl build doesn't care about Mobility/Strength/Recovery while my Solar Assassin's Cowl build wants more Mobility, and so on. So even per exotic there is no single "best build".
2. Builds have access to +3 artifice mods in addition to +5 and +10 general stat mods. DIM automatically assigns these to builds based on the stats the user cares about and the *order* of these stats (though it does optimize for total enabled tier first, but stat enabled-ness is still something to consider). Not sure if your script handles artifice armor pieces but I feel like it's quite important for such a feature to do that.

In general these additional constraints/properties are already present in saved Loadouts, so I was thinking we could instead define the builds to optimize for by considering all the loadouts for this user/character and taking the parameters from there. I feel like there's an overlap with #9554.

> I can implement this script either as an embed html component (that would require a little research because I haven't done this before, but it works), or as a docker file for you to call via rest API (that I'm familiar with). It may also output a .csv.

Is there anything about R that uniquely supports your script? Would it be possible to get comparable performance with JavaScript or WebAssembly, or does it use R libraries with no JS/WASM counterpart? If we're talking about integration we'd prefer if all this code runs locally in the browser with no dependency on external APIs or file formats, ideally reusing/sharing code with DIM's existing Loadout Optimizer (https://github.com/DestinyItemManager/DIM/tree/master/src/app/loadout-builder/process-worker, https://github.com/DestinyItemManager/DIM/wiki/Loadout-Optimizer).

**Comment by JagetYohan** [comment]
Hi RoboJumper (someone's playing an Exo ?),

What is this feeling? Is it... what it feels like to be acknowledged ?  :'D
Yeaaaah, sorry, I've been working freely on a health care (diabetes) algorithm for 2 years, for a startup that so far couldn't raise funds... call it an after-effect.

So.
Spoiler: it will be long.
There are many ways to consider how someone would like to tidy his inventory. I can add them all, and think further, the main thing being done. Could use plots as well, even though reading them sometimes requires some skills.

Answer to point 1:
Sure. Filtering high (or low) stats in some skills just as your loadout optimizer does is just a parameter to add in my function. 20' work.
Nevertheless, it was not the main idea, since the table output shows the whole inventory belonging to a >lim (lowest tier you ask as a parameter) build. I can filter with a specific exotic too, no problem.

"The best build" is in fact the highest tier you can reach (because I understand how questionnable such an election would be). My script won't elect a single build, but highlights all the builds that reach this highest tier, still showing the others. I'm not a hardcore gamer, I've been playing Destiny 2 for a year now, enough to discard builds under 32. So if I have the means to reach 32, I won't make a build for 31, I'll just wait.
Since we talk about tiers, I chose to classify them as follows:
31.1 is 31 and one half-way (e.g. one skill between 55 and 59)
31.2 is 31 and 2 half-way
etc...
Because I estimated a 31.2 is more valuable than a 31.1 (less points in mods).

Answer to point 2:
I understand why you did it, I appreciate that you did, but I do not use these features, no offense. I know how I'll deal with my own mods, especially since elemental wells/warmind cells are off (that was hell of a mind blower, and reason n°1 I searched for a DIM. I was stunned by the quality of your team's work, you made me save A LOT of time. Thank you all).
I gain a better visibility when, err... things are nude.
Technically, I intended to work with Bungie's API, because my script was just an exercise while waiting for the next (canceled...) contract, but presently I am not familiar with API requests, thus I firstly used the .csv you allow us to extract from the organizer. It does not contain info on mods, I could code them but it seemed a useless work for me as a first shot. Again, not difficult to add this small database though.
Last point, I sorted the table by reachable tiers; sorting it by skills would cancel it. In fact that was the whole thing: in the loadout optimizer, I'm quickly overwhelmed by the number of combinations, that is why I needed another tool.

About the "increase your loadouts" feature, the structure of the tables I built (and obviously the one you built too) makes it super easy to implement. We could also think about a margin (I ask for 7 in mobility, with a tolerance).

Now R.
R uses a dedicated language, and I sadly admit it's the only one I'm at ease with. As I mentioned, I'm not a developer, I was not even supposed to be a coder in the first place.
I used the data.table library, which is known to be super fast as it does not copy a table for join purposes (divide the other libraries' benchmark by 10-20). But after all, all I did was manipulating tables, and summarize, which could be done in SQL as far as I know. The table (in base R) function counts the number of occurrences of a label in a column and rebuilds a table from it (that's how I counted the tiers). I cannot tell if it would be as fast and convenient in JS/WASM, but I guess it is.
I fully understand why you would not accept another API, even internally (the REST call would be on your own server) that's why I suggested to embed it in html, but that would mean to store my own web app (library "shiny" in R, no download needed for the user) on a server too. Note that I've not done this yet, but that would mean to implement the graphics, etc... a lot of work this time.
SO, I can simply share my code and decipher it if you want to, so as you convert it in the language you like. If so, should I do this in this post? Maybe a video call to explain? What suits you best ?

Anyway, I love my job. I dunno if I have good ideas, but I have ideas nonetheless.
I enjoy solving problems, and sharing my findings. So if you want my opinions on anything regarding ways to have insights on data, just ask.

Yohan

**Comment by bhollis** [comment]
Closing this as I don't see anything actionable here, but feel free to continue the discussion and/or open a PR with code.
