### ISSUE TITLE
Theme feedback

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9634]
Collecting some feedback on the beta themes here, starting with my own but we can add user feedback as we get it.

### Pyramid Fleet (Dark Theme)

* The red key color feels like too much
* Having the store header be transparent (seeing items behind it) is distracting and makes the header harder to parse.
* Black polaroids for masterworks feels weird and reduces their visibility rather than highlighting them.

cc @guise

**Comment by nwLSteam** [comment]
Agree on black frames for masterwork feeling off. *However*, this is only because they are relatively darker. I love the design of the masterwork frames – the first thing I saw was my fully masterworked inventory and it looked great, only afterwards did I discover the non-masterworked weapons, whose grey looks kinda… muted and dull. (and obviously too bright against the masterworks)

Disagree on the red key color being too much – it’s a very aggressive theme by design, and the implementation of the red color seems well done for that goal.

**Comment by lowPolySkeleton** [comment]
In general, I think we need some additional variables. 

Specifically for the icon colors in the emblem header area, pretty much no conceivable way to make a light mode without changing those to be darker. 

Additionally the element colors probably need vars as well. Strand strait up disappears on some of these themes long with ark. 

We could probably get away with just binaries for these, dark icons or light icons. 

Border thickness would be great too or just full control over the borders for item tiles.

**Comment by guise** [comment]
Tracking some tweaks in #9634 

- Renamed the pyramid theme file to follow the location-based naming convention
- Pyramid: made header solid fill (the transparency was a hangover from experimenting with the glass effect)
- Added variable + theme specific colours for redeemed records
    - I've switched from using a sass-color function to a basic opacity knock-back for the `<p>` tint on this because the colour function doesn't play nice with CSS variables
- Adjusted background tints to improve contrast (europa, throne world)
- Adjusted/added P3 primary accent variant (pyramid, vex, europa, throne world)
    - I adjusted the pyramid theme primary orange a touch so that it's hue is closer to the 'pyramid tech' orange (the original ultra-vibrant orange was picked before making the themes location-based)
- Pyramid: Changed masterwork polaroids to yellow/gold
- De-coupled red dot 'new' notification from primary accent and made it into a variable
    - This is a sass variable rather than something that can be customised per-theme

**Comment by robojumper** [comment]
Some unthemed parts in Loadout Optimizer: The tooltip for stat mods explains auto stat mod behavior. The idea was to color these in the DIM color (as in "DIM is taking control over these"), but the tooltip code apparently doesn't support CSS vars due to usage of sass functions

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/3225ebda-0787-4e9f-a882-5f3c40fcb3d9)
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/dc28ec39-cb5f-4deb-b4b9-54ef07fc91d5)

Additionally, the aggressive pyramid red for auto mod borders makes LO's set rows very busy, but maybe that part goes away soon with @bhollis' LO UI redesign 
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/242d238c-910b-4f41-badb-9751f99e74d3)

**Comment by lowPolySkeleton** [comment]
I also think if we are going to allow MW border color changes with themes, we need to remove the border from the overlay. It causes both clashing and just general weirdness. 

before: 
![image](https://github.com/DestinyItemManager/DIM/assets/29002828/e1246eb8-48d1-455b-8888-f87b2cab9781)


after (with some additional changes to positioning that was accounting for this extra border) 
![image](https://github.com/DestinyItemManager/DIM/assets/29002828/b1ef7345-ab56-4449-85e2-ba1e1764b74b)

**Comment by guise** [comment]
> Specifically for the icon colors in the emblem header area, pretty much no conceivable way to make a light mode without changing those to be darker.

Yeah this was the main factor for not having light themes initially — I think the idea was (still is?) that we add light theme support in a follow up since there are a fair few other changes that will likely be needed. 

The header icons would all need to be SVG. At the moment some are black or white pngs (Total power level, Artefact power level, all the character stats). I wasn't able to find SVG sources for these; but if they can be swapped out the header icons could be given the same fill colour as the header character text (which does have a variable). Not sure if anyone knows if/where svg icons could be sourced? 

The other main issue with light themes is legibility of the quest thumbnails on the progress page. Some thumbnails show white icons (with png transparency) but they aren't differentiated from regular graphical quest thumbnails so they can't really be re-coloured or tinted. 

A potential remedy for this could be adding a background colour (via a variable) and + adding thumbnail padding to ensure white icons are always visible — but this would end up affecting all quests which didn't always look good. 

> Additionally the element colors probably need vars as well. Strand strait up disappears on some of these themes along with arc.

Agree the legibility of some of these is bad, i'll check options for improving. 

We do have system/sass variables for elements which I was reluctant to override or deviate from since they're used in other places (loadouts, tooltips). The main difficulty here is ensuring legibility on normal + mastworked polaroids since they can be wildly different colours within and across themes.

**Comment by guise** [comment]
> I also think if we are going to allow MW border color changes with themes, we need to remove the border from the overlay. It causes both clashing and just general weirdness where it looks like things are not contained in the border.
> 
> before:  
> ![image](https://user-images.githubusercontent.com/29002828/254888143-e1246eb8-48d1-455b-8888-f87b2cab9781.png)
> 
> after (with some additional changes to positioning that was accounting for this extra border)  
> ![image](https://user-images.githubusercontent.com/29002828/254888301-b1ef7345-ab56-4449-85e2-ba1e1764b74b.png)

The border gradient was an intentional design choice to give a 'sheen' effect to masterworked items. 

I've adjusted how the border renders which has cleaned up the harsh fade to transparency — which looks to be the cause of the weirdness. Colours also tweaked across themes

<img width="111" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/6bb5aca4-f646-4d3a-867b-adf4f6466673"> 
<img width="112" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/bc551f1c-ca8c-4d22-948d-beaf0c11935a"> 
<img width="111" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/29999f77-6f18-4e5b-af3f-f3025cf3c869"> 
<img width="112" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/a323d5f9-b9c7-494d-ac53-140b4b3c0024"> 
<img width="113" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/66b2c4e3-72f8-4973-aeee-84cdb993e999"> 
<img width="111" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/5922eee6-137a-42ac-b04c-22ee14be3c8d">

**Comment by lowPolySkeleton** [comment]
> The header icons would all need to be SVG. At the moment some are black or white pngs (Total power level, Artefact power level, all the character stats). I wasn't able to find SVG sources for these; but if they can be swapped out the header icons could be given the same fill colour as the header character text (which does have a variable). Not sure if anyone knows if/where svg icons could be sourced?

not necessarily, currently all? of the icons or most of them both in the emblems header area and the elements have filters applied to them to alter the color / brightness, we could just add vars to affect those filters. some of the emblem header Icons for instance are currently inverted to make them light at all. I think we could just offer binaries for these by setting up filters to make them light or dark and allow the themes to chose one of the binaries.

**Comment by robojumper** [comment]
Non-default themes: The strand color fix now rotates the non-white plug border color 
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/d5635dc4-332c-4b0f-ad48-7d455ec17e0a)

**Comment by guise** [comment]
> Some unthemed parts in Loadout Optimizer: The tooltip for stat mods explains auto stat mod behavior. The idea was to color these in the DIM color (as in "DIM is taking control over these"), but the tooltip code apparently doesn't support CSS vars due to usage of sass functions
> 
> ![grafik](https://user-images.githubusercontent.com/14299449/254880450-3225ebda-0787-4e9f-a882-5f3c40fcb3d9.png) ![grafik](https://user-images.githubusercontent.com/14299449/254880501-dc28ec39-cb5f-4deb-b4b9-54ef07fc91d5.png)
> 
> Additionally, the aggressive pyramid red for auto mod borders makes LO's set rows very busy, but maybe that part goes away soon with @bhollis' LO UI redesign ![grafik](https://user-images.githubusercontent.com/14299449/254880853-242d238c-910b-4f41-badb-9751f99e74d3.png)

Ah yeah, I forgot about this - I left the auto-picked section as a hardcoded value for expediency to get the initial theme scaffolding in. 

I've managed to get it working ok using [`color-mix()`](https://caniuse.com/mdn-css_types_color_color-mix) since support is fairly broad now. It should fallback to the DIM orange for browsers that don't support it. 

<img width="341" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/8d335bff-e03f-463d-8db4-5e9aec662296"> 
<img width="340" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/cdaab8f4-f657-4c81-b2af-0d992a35320b">

**Comment by lowPolySkeleton** [comment]
couple more things I noticed when making a theme that we may want to add.

the DIM tracked border colors
![image](https://github.com/DestinyItemManager/DIM/assets/29002828/16d07c51-3233-4406-89b2-4089eb786bd4)

the icon colors on the organizer page
![image](https://github.com/DestinyItemManager/DIM/assets/29002828/5a087e98-4378-48d3-8c5f-ce34cf2dbdab)

**Comment by guise** [comment]
> Non-default themes: The strand color fix now rotates the non-white plug border color
> ![grafik](https://user-images.githubusercontent.com/14299449/254967486-d5635dc4-332c-4b0f-ad48-7d455ec17e0a.png)

This is a tricky one. Can't find a way to adjust the image colour independently from the border, so might have to roll with the least egregious fix

- Top row (current inverting colour method):very obvious in a couple of themes (neomuna, pyramid) 
- Bottom row (dark green background): kinda obvious in most themes if you more than glance 

![image](https://github.com/DestinyItemManager/DIM/assets/1396158/af0726e2-d2cc-4717-a04b-8c1734d068d7)

OR since this fix is abit of workaround to begin with, we could adjust the fix per theme. Unless of course there is a way to check if Bungie are serving newer corrected assets?

**Comment by robojumper** [comment]
> Unless of course there is a way to check if Bungie are serving newer corrected assets?

DIM always uses the current assets, so the moment Bungie fixes the icons, our workaround will start looking very obviously wrong. If it's too much effort to fix currently, I think it's okay to keep the current behavior -- Bungie has fixed the exact same issue for Solar and Arc before.

**Comment by robojumper** [comment]
From the Discord (https://discord.com/channels/316217202766512130/333470465274150912/1131362753639104553): Item badge + border for "capped" stacks of items always use an unthemed gold color, which stands out a lot on most themes.

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/d39e701e-edf7-45e0-9420-0b86bdbf79b9)

**Comment by robojumper** [comment]
Some inconsistencies in square plug border colors

Item popup: mostly unthemed borders (special color for the masterwork plug) 
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/96b3a630-9a18-4957-98c7-760ebdff1177)

Loadout shaders/ornaments/mods: themed borders
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/fdc0902b-8c60-49fe-b381-e1d642645e94)

in-game loadout popup: mostly grey/unthemed borders
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/614d63a1-c1cb-4d9d-8db5-038613ad53d6)

Loadout optimizer: themed borders
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/78c91d7c-3e6d-4531-85bd-45095d2e8645)

**Comment by lowPolySkeleton** [comment]
we've had several complaints now about the new MW overlays being too much. I don't know if the solution is just to reduce the opacity a bit more to make it fall more inline with the old PNGs or what.. no one has been all that descriptive beyond "it bothers me" and no one has come here to talk about it yet so.. just adding it in myself so we have it documented.  discord messages about it below for reference. 

![image](https://github.com/DestinyItemManager/DIM/assets/29002828/c88b6f57-a407-4939-b21d-f7af52d8e8d4)

![image](https://github.com/DestinyItemManager/DIM/assets/29002828/01aa55fd-834e-4446-9c6a-e5a3ac10c28b)

![image](https://github.com/DestinyItemManager/DIM/assets/29002828/2915f2bb-3c3e-4e06-b2bc-c7eb698dbf0d)

**Comment by guise** [comment]
I'm sure the opacity can be dialled back to be more balanced — I suspected this would need fine tuning. It is fairly prominent on mobile and low-density resolutions. 

I suspect the overlay is also more noticeable because legendary masterworks were previously missing the patterned (despite the item popup header including it). 

I did experiment with rendering the overlay using `mix-blend-mode` which helps considerably making it look 'part of' the image, but it resulted in a noticeable lag when scrolling which makes that approach a non-starter IMO.

**Comment by guise** [comment]
I may have identified a potential (but currently hacky) fix for item border mis-alignment issue at specific display scales — details in PR #9675

**Comment by nev-r** [comment]
why are masterworks overlaid with a pattern at all? am i missing something? it's not an in-game feature so where is it coming from? did d2 have it but remove it at some point?

![image](https://github.com/DestinyItemManager/DIM/assets/68782081/f82d068d-b69b-4a4f-b5af-465c6d0927af)

**Comment by lowPolySkeleton** [comment]
> why are masterworks overlaid with a pattern at all? am i missing something?

I think only exotics do it in game?

**Comment by nev-r** [comment]
that explains a lot about why it looks so out of place and contrasts so unexpectedly strongly
