### ISSUE TITLE
Wish list perk column grouping gets confused by guns that have had the same perks in multiple columns

### ISSUE THREAD

**Issue by OverlordEclipse** [DestinyItemManager/DIM#9711]
### DIM Version

7.80.0

### Browser Details

Opera 101.0.4843.33

### OS Details

Windows 11

### Describe the bug

I made a custom wishlist for destiny 2 weapon rolls and when i went to check out them, most were fine however my vouchsafe had some oddities show off. Attached are 2 pictures, one is of the weird behavior shown by dim and the other is the wishlist details added for said roll. https://imgur.com/a/1GOaLI8 . When you have 2 closely related rolls such as non enhanced and enhanced versions of the same perk, the show up more or less under the same god roll, however somehow the third slot perk got push into the bottom two (in both the 3rd and 4th slot perk slots) and the 4th slot got put on top in both the 3rd and fourth slot, for all 3 rolls i made for this gun. This is the only gun it has done this for and i have no idea whats happening.

**Comment by robojumper** [comment]
This is happening because over the years, Vouchsafe has had some perks shuffled around between the columns (Rapid Hit and Outlaw are valid in both the third and the fourth column), and since the Armory wish lists view organizes perks in columns, it gets a bit confused with how it should best display that fact.

**Comment by bhollis** [comment]
Closing since this is an edge case that will likely not get fixed before wish lists are revamped.
