### ISSUE TITLE
Don't count artifice + non-artifice as dupe

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#9735]
### DIM Version

Version 7.81.0 (release), built on 14/08/2023, 03:50:13

### Browser Details

Firefox

### OS Details

Windows 11

### Describe the bug

I believe they're currently counted as dupe with the `is:dupe` filter

**Comment by bhollis** [comment]
Could you elaborate a bit on what you're looking at, what happens now, and what you'd expect to see?

**Comment by Revadike** [comment]
> Could you elaborate a bit on what you're looking at, what happens now, and what you'd expect to see?

Thanks for getting back to me. Currently, with the `is:dupe` filter, both an artifice armor piece and a non-artifice armor piece of the same name get selected. I wouldn't count them as dupe.

**Comment by robojumper** [comment]
I don't quite see why DIM should do that -- the only difference between an artifice armor piece and a non-artifice armor piece are some stat points. But we don't stop highlighting dupe armor pieces just because their stats are different...

How are you using the `is:dupe` filter and how would this change benefit your workflow?

**Comment by Revadike** [comment]
I process artifice armor differently compared to regular armor
