### ISSUE TITLE
Destiny 1 DIM max light button showing incorrect max light

### ISSUE THREAD

**Issue by teebles** [DestinyItemManager/DIM#9742]
### DIM Version

7.82.0, built 8/20/23

### Browser Details

Firefox, Chrome, Microsoft Edge

### OS Details

Windows 10, Android 10

### Describe the bug

When showing the max light available, or when showing the max light button, it usually shows a light level around 20 levels under my actual max. I believe it's taking the speed of my sparrow into account, as it attempts to swap my sparrow if I have one under 160 speed, and putting that number into the max light estimate.

**Comment by robojumper** [comment]
Wonder for how long this has been broken. I can't test D1 but I think the bug is this line (introduced by #7184):

https://github.com/DestinyItemManager/DIM/blob/227095e4dd8bd6c2918861137c30ac8a6c100d43/src/app/inventory/store/d1-item-factory.ts#L350

which unconditionally sets the "power" to the primary stat, and only afterwards

https://github.com/DestinyItemManager/DIM/blob/227095e4dd8bd6c2918861137c30ac8a6c100d43/src/app/inventory/store/d1-item-factory.ts#L390-L392

sets power to the same value if the item actually has power.

**Comment by bhollis** [comment]
Yeah probably at least that two years. Easy enough to fix though.
