### ISSUE TITLE
Missing loadouts / Loudouts i didnt make

### ISSUE THREAD

**Issue by drag0nzkin** [DestinyItemManager/DIM#9849]
### DIM Version

Version 7.84.0.1002895 (beta), built on 9/6/2023, 6:41:31 AM x- 

### Browser Details

Chrome 116.0.0.0 

### OS Details

Windows 11

### Describe the bug

My loadouts are no longer available and three are loadouts that I have never created with names I have never created in my loadouts page. I know i didnt create them becasue the loadouts use armor or weapons that I dont ever use.  also for one of my characters i NEVER use stasis and yet there are like 10 stasis loadouts that I hve never even saved

### Logs

```shell
[app] DIM v7.84.0.1002895 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:132 Language Detected: en-us
instrument.ts:132 Language Assigned: en
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F7.64.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.googletagmanager.com/gtag/js?id=G-MYWW38Z3LR:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:132 [dim sync] globalSettings Object
banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89 Unrecognized Content-Security-Policy directive 'prefetch-src'.
OpenCollectiveWidget.inject @ banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89
script.tagged-events.exclusions.js:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v8b253dfea2ab4077af8c6f58422dfbfd1689876627854:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry.io/api/1736806/envelope/?sentry_key=2ab0f7da3f56423d940f36370df8d625&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.53.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
logo.png:1     Failed to load resource: the server responded with a status of 404 ()
logo.png:1     Failed to load resource: the server responded with a status of 404 ()
```

**Comment by bhollis** [comment]
Can you share a screenshot of the debug page? Go to About DIM, click on Debug.

**Comment by drag0nzkin** [comment]
![dim debug](https://github.com/DestinyItemManager/DIM/assets/144261574/7a85ecd3-5130-4f4c-b14e-2bfa370e577a)

**Comment by bhollis** [comment]
I can see 34 loadouts for your account, with names like "Paralyze Perfected Hunter". Have you ever shared your login with someone else, or had you ever changed which Bungie.net account you have associated with your Destiny account?

**Comment by drag0nzkin** [comment]
No, I have never shared password. Same bungie account since I started  playing . I noticed all the names and like I said. I never created.them. I had maybe 2 or 3 per character, which are gone, and now there are many more. None of which I created.

**Comment by bhollis** [comment]
OK. I think I have an idea of what's going on but I'll have to do some more investigation.

**Comment by bhollis** [comment]
Can you provide a screenshot of your Loadouts page?

**Comment by drag0nzkin** [comment]
you want the whole page for each character? or justmain page

**Comment by drag0nzkin** [comment]
![lOADOUT2](https://github.com/DestinyItemManager/DIM/assets/144261574/d3bd0aae-7020-43f9-bc49-4a2c022ba261)
![lOADOUT3](https://github.com/DestinyItemManager/DIM/assets/144261574/bb3e6ec8-a22a-4fcc-83d8-071361249ef3)
![lOADOUT1](https://github.com/DestinyItemManager/DIM/assets/144261574/5b70182a-eb87-4383-992c-3e4
These are titan loadouts

**Comment by drag0nzkin** [comment]
![lOADOUT1](https://github.com/DestinyItemManager/DIM/assets/144261574/ff038972-0992-4aa1-8da0-b59e0136c63d)

**Comment by bhollis** [comment]
Have you ever imported data from a JSON file into DIM Sync, from the Settings page?

**Comment by drag0nzkin** [comment]
today, thinking it would have my old loadouts

**Comment by bhollis** [comment]
What did you do? Export and then reimport the file? I can see that all the loadouts were created at the same time which is consistent with an import. Unfortunately that also gets rid of some of the information I could use to figure this out. 

Also, have you used any other third party Destiny tools?

**Comment by drag0nzkin** [comment]
no third party tools. I downloaded it from dim then uploaded it

**Comment by bhollis** [comment]
If you completely log out of DIM, select "log in with a different bungie.net account" and log back in, are they still there?

**Comment by bhollis** [comment]
Also do you remember the name of one of the loadouts you're missing?

**Comment by drag0nzkin** [comment]
Let me check. Yes they are. One for warlock was called sungod. . Also for warlock, I know for a fact I never named one Stacy's curves. And it also shows my ship as they hushed syrynx which is a trials flawless chest, and rng drop.. I don't play trials. So I don't have that ship

**Comment by bhollis** [comment]
Well, obviously this is very concerning - the DIM Sync service is designed very carefully to only allow access to your own data, but somehow you've gotten someone else's. What we know so far:

1. The profile ID and membership ID in your screenshot are your actual IDs, or you wouldn't be able to see your actual items.
2. The loadouts stored in DIM Sync under that ID are the ~34 loadouts you don't recognize. They exclusively include items you don't have. We're not returning data for the wrong accounts, and this isn't just a local data problem.
3. These loadouts' IDs are not duplicated on any other account, and for many of them the names are unique to your account (some others are clearly from loadout shares), meaning you haven't gotten a *copy* of someone else's data or imported it into your account accidentally (unless the original data has since been deleted from the origin account).
4. It's possible that some of the above were different (e.g. we did return the wrong user's data at one point), but you exported your data and re-imported it which means it definitely is your data now in the eyes of the database. This also would've wiped out any remnants of your original data that were still associated with your account.

While I'm very worried that there's something wrong with how we're storing or serving data from DIM Sync, I'm out of ideas for where to look to figure out how that could be. You should probably click "Delete All DIM Sync Data" to remove all the unknown data and start over. We'll keep an eye out to see if this happens to anyone else.

**Comment by drag0nzkin** [comment]
Thank you for all your help. Kinda had a feeling I would have to start over.. I do appreciate you trying to help. Hopefully this doesn't happen again

**Comment by bhollis** [comment]
If it does, definitely let us know.
