### ISSUE TITLE
Dropdown hover selection is weird on Firefox

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9925]
Maybe a Firefox bug, but we should see if we can work around it.

**Comment by liamdebeasi** [comment]
Do you have steps to reproduce this issue? I'd be happy to take a look into fixing this.

**Comment by bhollis** [comment]
Hm, the extreme example doesn't reproduce for me anymore - it used to be that the effective cursor position was wrong so it was very difficult to actually select from the dropdown. Now the only thing I see is that there seems to be a very slight delay updating the items on hover - perhaps the difference between a hover CSS style and something applied after a React update. You can see a little "flashing". It's not significant:

<video src="https://github.com/DestinyItemManager/DIM/assets/313208/3b6f321f-ce31-4688-a8c9-734a1458368c"/>

**Comment by liamdebeasi** [comment]
I'm able to reproduce this with Firefox on macOS. Do you have any advice for how to test DIM locally in Firefox? When I try to access `https://localhost:8080` I get an `SSL_ERROR_RX_RECORD_TOO_LONG` error:

![CleanShot 2024-06-17 at 22 26 31](https://github.com/DestinyItemManager/DIM/assets/2721089/c83731b5-da5a-4854-82ac-25fe56beb217)

I'm not aware of a way to bypass this, and I didn't see anything regarding this in the [contributing guide](https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md#development).

**Comment by liamdebeasi** [comment]
The [useLayoutEffect](https://github.com/DestinyItemManager/DIM/blob/7dd043fb65940312efb5bc368329d44732590d5f/src/app/dim-ui/usePopper.ts#L141-L163) usage for `usePopper` appears to be the culprit here. Hovering over each item in the dropdown causes `highlightedIndex` to change. This causes the React component to re-render. However, re-rendering causes `useLayoutEffect` to run again. The body of this hook destroys and re-creates the popover every time it runs.

This seems to trigger a quirk in Firefox that causes `downshift` to think the mouse pointer left the menu (likely because of some painting/compositing change since the styles `popper` configures can impact that). When this happens, [downshift changes the `highlightedIndex` to `-1`](https://github.com/downshift-js/downshift/blob/ee2a828ac70035c1e6156523b72c11abae4c07e4/src/hooks/reducer.js#L24) which causes the hover effect to disappear. As you move your mouse, Firefox then dispatches another `mousemove` event. This causes [downshift to set the `highlightedIndex` to the correct value again](https://github.com/downshift-js/downshift/blob/ee2a828ac70035c1e6156523b72c11abae4c07e4/src/hooks/reducer.js#L18).

Unfortunately, since these all cause re-renders, the popover is destroyed and re-created which then triggers that Firefox quirk again.

------

In terms of fixing this, my initial thought was to make `reference` and `contents` dependencies of `useLayoutEffect` so that hook only fires whenever the references change. However, this causes the position of the popover to be wrong for some reason. I have not dug into why that is. This bug also impacts the dropdowns on the Loadouts screen: 
![CleanShot 2024-07-24 at 22 56 55](https://github.com/user-attachments/assets/61f74a27-281b-4d35-b82f-f11f6d95831a)

**Comment by liamdebeasi** [comment]
PR created: https://github.com/DestinyItemManager/DIM/pull/10660
