### ISSUE TITLE
Equip On and Pull to buttons are not using proper emblem icon beneath the guardian class symbol.

### ISSUE THREAD

**Issue by nathanpete1** [DestinyItemManager/DIM#9975]
### DIM Version

Version 7.89.0 (release)

### Browser Details

Brave 1.58.137, Chromium 117.0.5938.153

### OS Details

Android 13

### Describe the bug

As seen in the bottom of this image: 
![Screenshot_20231013_082701_Brave](https://github.com/DestinyItemManager/DIM/assets/90541353/bf3d4559-1887-4a56-b3a7-73d1959b4b1b)
The emblem artwork beneath the class symbol seems to be a square crop of the center of the full emblem artwork. As can be seen by the orange and blue corners in the **Equip on Hunter** button (compare the artwork in the button to the emblem artwork at the top of the screenshot if you do not understand.)

I'm not sure if this is the official terminology, but Destiny Emblem Collector calls the square artwork the _Emblem icon_' and the longer artwork, like what is at the top of the screenshot above, the _Secondary emblem icon_. 

It should be using the Emblem icon underneath the guardian symbol layer, rather than a crop of the secondary emblem icon. 

Like the correct artwork is in use when looking through my equipped and equippable emblems in my inventory. 
![Screenshot_20231013_081745_Brave](https://github.com/DestinyItemManager/DIM/assets/90541353/eb4fcb45-f111-45a2-9198-28773c2e630b)

**Comment by robojumper** [comment]
This is intentional - the emblem icon is visually very busy, so it often clashes very aggressively with the class icon, or the class icon obscures much of the icon, making identification difficult too. Here's what it'd look like otherwise:

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/2c1bcc32-6174-46e2-8bae-1662000c0f14)

for reference, the same emblems currently:

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/48135b2a-ddc4-49df-a434-665ccedd83aa)
